### ISSUE TITLE
outline doesn't switch according to the file switch

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#2644] opened 2019-07-11 14:45 UTC
when switch file, it's amazing that the outlines on the left panel refuse to switch accordingly.

It's a crazy bug affects daily life, please manage to repair asap.

**Comment by leewi9** [comment] 2019-07-12 02:33
@abnerlee urgent

**Comment by abnerlee** [comment] 2019-07-21 08:50
How to reproduce this?

**Comment by leewi9** [comment] 2019-07-22 02:27
open multiple file in a folder, each file with some headlines, then try to switch between those files, perhaps you will see.

**Comment by leewi9** [comment] 2019-07-26 02:10
@abnerlee could you please solve it as soon as you can, it really hurts!

**Comment by abnerlee** [comment] 2019-07-29 15:23
@leewi9 I still cannot reproduce this. If possible could you take a screencast to us <hi@typora.io>?

**Comment by leewi9** [comment] 2019-07-30 02:36
@abnerlee https://drive.google.com/open?id=1dqJRlS2jOEM2uDx5IRZ-CjZplYhh8F4W

**Comment by leewi9** [comment] 2019-07-30 07:24
@abnerlee  any update?

**Comment by abnerlee** [comment] 2019-08-03 15:02
should be fixed

**Closed by abnerlee** 2019-08-03 15:02 UTC
Labels: bug

**Comment by leewi9** [comment] 2019-08-03 15:05
may I know the reason? @abnerlee
