### ISSUE TITLE
Use of Shift+Enter causes insertion of new lines for each character typed

### ISSUE THREAD

**Issue by douglasprodocimo** [typora/typora-issues#1711] opened 2018-08-22 20:53 UTC
On windows, typora version 0.9.56 (x64).
(three lines text)
1 - Type a simple text and use "Shift+Enter" to go to new line. (line 1)
2 - Write some text and use "Enter" to go to new line. (line 2)
3 - Write some text (line 3)
4 - Go back one line and delete using "Backspace" until delete a linha. (line 2)
Now you can see new lines been inserted for each char entered.

**Comment by abnerlee** [comment] 2018-08-23 01:08
I'm not able to reproduce this bug.

So what's your OS? Do you use American-English Layout keyboard or something else, and nay more detailed steps to reproduce it?

**Comment by douglasprodocimo** [comment] 2018-08-24 01:08
![captura de tela 30](https://user-images.githubusercontent.com/7575877/44559480-ba3aae00-a720-11e8-92e8-895a09893004.png)
The keyboard layout is Brazilian ANBT
There is a video reproducing the bug.
[Typora 23_08_2018 16_11_26.zip](https://github.com/typora/typora-issues/files/2316674/Typora.23_08_2018.16_11_26.zip)

**Comment by douglasprodocimo** [comment] 2018-08-24 01:13
The keyboard layout is Brazilian ABTN
![captura de tela 30](https://user-images.githubusercontent.com/7575877/44559613-a5124f00-a721-11e8-9916-388b7f219819.png)
A made a video ware I reproduce the bug!
[Typora 23_08_2018 16_11_26.zip](https://github.com/typora/typora-issues/files/2316680/Typora.23_08_2018.16_11_26.zip)

**Comment by boxofnotgoodery** [comment] 2018-08-24 12:33
Same issue here.
Happened right after I updated to 0.9.56

**Comment by abnerlee** [comment] 2018-08-25 08:47
@boxofnotgoodery were you also using Brazilian ABTN keyboard layout ?

**Comment by abnerlee** [comment] 2018-08-25 14:26
@boxofnotgoodery I tried Brazilian keyboard on Windows 10, but I still cannot reproduce it.

When it happens, could you open DevTool by menu bar (`View` -> `Toggle DevTools`) and show us the log in console ?

**Comment by douglasprodocimo** [comment] 2018-08-27 14:09
Did you see the video?
This is everything that log showed.
[-1535378845018.log](https://github.com/typora/typora-issues/files/2324159/-1535378845018.log)

**Comment by douglasprodocimo** [comment] 2018-08-27 14:14
There is one more.
[-1535379311526.log](https://github.com/typora/typora-issues/files/2324182/-1535379311526.log)

**Comment by boxofnotgoodery** [comment] 2018-08-27 15:30
@abnerlee No, I use standard US keyboard, doesn't do it if I switch to "source code mode"

**Comment by abnerlee** [comment] 2018-08-27 15:55
@douglasprodocimo 
I saw the video, but I cannot reproduce it on my Windows 10 PC. 
If you create a new untitled file by ctrl+n, can this bug still be reproduces on your PC?

**Comment by douglasprodocimo** [comment] 2018-08-27 16:59
@abnerlee yes. The bug still happening when I create a new file using (ctrl+n)
PS. This ocours with "souce code mode" off.

When the "Rendering" tool is activated, the (shift+enter) line, persists even after delete it.
[Typora 27_08_2018 13_49_14_Trim.zip](https://github.com/typora/typora-issues/files/2324824/Typora.27_08_2018.13_49_14_Trim.zip)

**Comment by abnerlee** [comment] 2018-08-27 17:39
@douglasprodocimo Thanks for the video. Sorry, but I still need your help since I cannot reproduce it on my PC.

Could you Make the visible area of the Dom Tree under "Element" tab bigger in DevTools, 
expand the dom `body>content>#write` (which render the documents), and record a video. 
So that I could see the dom changes in "Rendering" view when this bug happens?

**Comment by douglasprodocimo** [comment] 2018-08-27 18:09
No. Using "Edit->Delete Range->Delete Line/Sentence" the bug disappear.

[Untitled - Typora 27_08_2018 15_07_24_Trim.zip](https://github.com/typora/typora-issues/files/2325055/Untitled.-.Typora.27_08_2018.15_07_24_Trim.zip)

**Comment by abnerlee** [comment] 2018-08-28 02:52
Thanks, I'm able to reproduce it now. I will fix this asap

**Comment by git-chc** [comment] 2018-08-29 09:48
Hello:

[2018-08-29_17-29-51.zip](https://github.com/typora/typora-issues/files/2331616/2018-08-29_17-29-51.zip)

coming from https://github.com/typora/typora-issues/issues/1707

Not only delete will insert a new line, but typing also will add a new line after shift+enter. (see video)
It happened in same p block, after leaving / losing focus from that p block / tag, became normal.

Try to alert keyboard key with no success. (have not enough time to do so)

**Comment by abnerlee** [comment] 2018-09-01 06:51
Fixed in new release

**Closed by abnerlee** 2018-09-01 06:51 UTC
Labels: bug
