### ISSUE TITLE
[Feature Request] Improve UI of file explorer

### ISSUE THREAD

**Issue by justnealpatel** [typora/typora-issues#2825] opened 2019-09-12 19:20 UTC
Hi. First off, I can't thank you enough for creating Typora. It's truly a great experience to use. I just wanted to make a suggestion to make the app have a better UI (of course this is in my eyes so you may have a different opinion).

I was thinking of [Quiver](https://happenapps.com) when I was thinking of a great built-in file system. Quiver allows for nested notebooks which, I think, could be translatable to folders. The only part I see as a wildcard is files that aren't markdown files. I also realize that the current file explorer is just a file explorer and could contain items that aren't markdown files. If you could somehow merge the idea of this UI into a representation of a file explorer, I think that would be great. 

As of right now, I face several bugs when using the file explorer, such as:

- when creating a file and I want to rename it, it sometimes says file X cannot be found and immediately closes the entire tree
- when I create a file, it automatically names it Untitled.md and moves it

macOS Version 10.14.5
Typora Version 0.9.9.28.5 (3442)

I think with a UI like this, these common bugs could be avoided as we'd be able to create files and folders through the UI. It's a lot more intuitive in my opinion.

Again, thanks for creating Typora. If you're ever looking for any type of contribution, I'd love to help.

**Comment by abnerlee** [comment] 2019-09-16 16:06
Duplicate of other existing issues, like rename fail, file filters, etc

**Closed by abnerlee** 2019-09-16 16:06 UTC
