### ISSUE TITLE
After in-line graphic, cannot move past graphic, necessitating going to source code to hit <space>

### ISSUE THREAD

**Issue by foofoo5** [typora/typora-issues#3881] opened 2020-09-29 05:25 UTC
I am using small in-line graphics in a user's manual (specifically, small icons for "clicked-on" or typed actions), and after pasting in the small graphic, I cannot move further than the graphic without going to the source code view and typing a space past the graphic. Example: 

Text: "Enter the new rule name [and here is pasted in a small round icon with the number "1"] and select the destination stylesheet."

Code: * Enter the new rule name <img src="/.../typora-user-images/image-20200928185043765.png" alt="image-20200928185043765" style="zoom:33%;" /> and select the destination stylesheet."

Immediately after pasting the code for the graphic. I cannot move past the graphic (the cursor seems to be blinking behind the graphic), making it necessary to go to the the source code view and hitting the space bar once to get passed the end of the image code ...;" /> to continue.

**Comment by abnerlee** [comment] 2020-10-08 15:49
I'm not able to reproduce this. 

What your typora version, and possible to send us <hi@typora.io> a screencast?

**Comment by foofoo5** [comment] 2020-10-09 05:20
Of course now I can’t replicate the issue as well! This leads me to think that, as I was trying a number of themes, the problem was related to a specific theme, as opposed to Typora itself, and specifically to the copying & pasting of image date. This is the first time I have ever submitted an issue & it was apparently “self-healing." I apologize for taking your time and effort, and if the problem happens again, I will be more diligent in providing a screenshot & more details. Typora is an awesome app!

ALWAYS wash your hands

**Comment by abnerlee** [comment] 2020-10-13 15:47
Sure, don't worry, I'm closing this since it might be issue of certain 3rd themes. 

Which theme did it happened,btw?

**Closed by abnerlee** 2020-10-13 15:47 UTC
Labels: Need more info, cursor / selection, images / resouces
