### ISSUE TITLE
Spellcheck crashes the application every time

### ISSUE THREAD

**Issue by ttunguz** [typora/typora-issues#533] opened 2017-02-15 17:08 UTC
Hi, I love the product. I use it almost every day. But every time I try to check spelling, which I initiated by using the keyboard shortcut, the application freezes. It has no problem getting through the front matter, but as soon as it hits the text, the spellcheck crashes the application.

I'm on a 2016 MacBook Pro with  16 GB RAM, the latest version of Mac OS X, 10.12.3. Looking through Console I see this stack trace immediately after the program crashes

default	09:06:35.470202 -0800	Typora	Started app
default	09:06:35.470329 -0800	Typora	current version: 0.9.9.9.0
default	09:06:35.470382 -0800	Typora	forceUpdateTheme: 0
default	09:06:35.470558 -0800	Typora	init theme folder : 1
default	09:06:35.471860 -0800	filecoordinationd	Received claim <private>
default	09:06:35.471939 -0800	filecoordinationd	Claim 5A184DE4-141B-4D2F-AE72-856F9C735D97 granted in server
default	09:06:35.472137 -0800	filecoordinationd	Claim 5A184DE4-141B-4D2F-AE72-856F9C735D97 invoked in server
default	09:06:35.472329 -0800	Typora	Claim 5A184DE4-141B-4D2F-AE72-856F9C735D97 granted in client
default	09:06:35.472364 -0800	Typora	Claim 5A184DE4-141B-4D2F-AE72-856F9C735D97 invoked in client
default	09:06:35.479613 -0800	Typora	subsystem: com.apple.clouddocs, category: default, enable_level: 0, persist_level: 0, default_ttl: 14, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
default	09:06:35.480023 -0800	Typora	readFromData
default	09:06:35.481072 -0800	filecoordinationd	Added presenter 183D5704-326E-4CE1-9230-727F7F968689
default	09:06:35.481504 -0800	filecoordinationd	Ignored new presenter 183D5704-326E-4CE1-9230-727F7F968689, because one with the same ID already exists
default	09:06:35.481596 -0800	filecoordinationd	Claim 5A184DE4-141B-4D2F-AE72-856F9C735D97 was revoked
default	09:06:35.492915 -0800	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	09:06:35.494225 -0800	sharedfilelistd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.494295 -0800	sharedfilelistd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.494380 -0800	sharedfilelistd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.494433 -0800	sharedfilelistd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.494589 -0800	sharedfilelistd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.494734 -0800	sharedfilelistd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.494884 -0800	sharedfilelistd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.495044 -0800	sharedfilelistd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.495128 -0800	sharedfilelistd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.495181 -0800	sharedfilelistd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.495461 -0800	sharedfilelistd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.495515 -0800	sharedfilelistd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.499690 -0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	09:06:35.529290 -0800	Typora	Could not find image named 'NSImageNameTouchBarTextListTemplate'.
default	09:06:35.564176 -0800	Typora	Faulting in NSHTTPCookieStorage singleton
default	09:06:35.564237 -0800	Typora	Faulting in CFHTTPCookieStorage singleton
default	09:06:35.564262 -0800	Typora	Creating default cookie storage with process/bundle identifier
default	09:06:35.585643 -0800	Typora	#WK: Starting frame load, frame = 0x107dc5000, main = 1
default	09:06:35.591818 -0800	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	09:06:35.592584 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.592636 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.592698 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.592745 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.592878 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.592937 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.593004 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.593060 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.593137 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.593188 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.593261 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.593311 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.593681 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.593736 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.593792 -0800	tccd	MacOS error: -67050
default	09:06:35.596987 -0800	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	09:06:35.597749 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.597800 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.597861 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.597905 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.598052 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.598105 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.598167 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.598221 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.598296 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.598348 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.598420 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.598469 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.598828 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.598876 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.598934 -0800	tccd	MacOS error: -67050
default	09:06:35.602739 -0800	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	09:06:35.603625 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.603710 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.603804 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.603864 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.604000 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.604098 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.604169 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.604223 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.604299 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.604352 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.604433 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.604481 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.605007 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.605070 -0800	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	09:06:35.605126 -0800	tccd	MacOS error: -67050
default	09:06:35.606012 -0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	09:06:35.606237 -0800	mds	directQueryOpenReply 290817 1795162112 0
default	09:06:35.606308 -0800	mds	QueryOpen succeeded (0) for store <private>
error	09:06:35.892325 -0800	Typora	NSURLConnection finished with error - code -1100
error	09:06:35.893667 -0800	Typora	NSURLConnection finished with error - code -1100
default	09:06:35.942720 -0800	Typora	#WK: Finished frame load without error, frame = 0x107dc5000, main = 1

The details of the message say security_exception, so I wonder if it's a permissions issue. Thanks for the help.

**Comment by abnerlee** [comment] 2017-10-30 07:56
I'm closing this since I cannot reproduce this.

Please reopen this issue if this still happens on the last version of Typora

**Closed by abnerlee** 2017-10-30 07:56 UTC
