### ISSUE TITLE
can't selected with the keyboard "save" "don't save" "cancel" options

### ISSUE THREAD

**Issue by Eskander88** [typora/typora-issues#1589] opened 2018-06-28 12:37 UTC
When I close the application a confirm window is displayed with options: `Save` `Don't save` and `Cancel`

![default](https://user-images.githubusercontent.com/24587938/42034289-3e8b447c-7ae8-11e8-90ec-ae1fbf0b528b.png)

When I pressing button `←`, `→`, `tab`, `esc`, `enter` is nothing happens

It would be great, if user pressed key and option is been chosen.

OS; Win10x64
Vers. Typora: 0.9.53 beta

**Comment by abnerlee** [comment] 2018-06-30 04:22
duplicate of https://github.com/typora/typora-issues/issues/1469

**Closed by abnerlee** 2018-06-30 04:22 UTC
