### ISSUE TITLE
Strange bmatrix rendering

### ISSUE THREAD

**Issue by VicaYang** [typora/typora-issues#2367] opened 2019-04-05 10:56 UTC
$$
R\left(\begin{bmatrix}0&1&1\\0&1&0\\1&0&0\end{bmatrix}\right)
$$

The formula rendered has a strange block

Acrobat Pro DC 2015
![image](https://user-images.githubusercontent.com/22126501/55622755-aafe0180-57d3-11e9-896e-760c38255a1c.png)

Chrome: 73.0.3683.86
![image](https://user-images.githubusercontent.com/22126501/55622849-eac4e900-57d3-11e9-950f-56137500eaff.png)

Edge: Microsoft EdgeHTML 17.17134

![image](https://user-images.githubusercontent.com/22126501/55622923-2069d200-57d4-11e9-9643-280bc4e9cc9d.png)

[test.pdf](https://github.com/typora/typora-issues/files/3047545/test.pdf)

I think it is a rendering bug, but I don't know whether it is because typora or others engine in my computer

**Comment by abnerlee** [comment] 2019-04-12 15:32
It is rendered as: MathJax -> SVG -> Chromium -> PDF, you could try export as HTML, which looks fine in Chrome, then print as PDF in Chrome, then open with Acrobat Pro DC, the issue stills there. So this would be a "Chrome -> PDF" issue or PDF rendering issue.


We will close this, since we will put other issues with higher priority before this, and we properly cannot do much about this if it is caused by Chrome's PDF printer or MathJax's SVG output

**Closed by abnerlee** 2019-04-12 15:32 UTC
Labels: bug
