### ISSUE TITLE
Auto-saving on Windows broken?

### ISSUE THREAD

**Issue by Crissov** [typora/typora-issues#910] opened 2017-09-15 12:02 UTC
The Windows 7 system I'm currently on automatically restarted yesterday to finish some software update. Typora was running at the time with two unsaved, untitled documents. Luckily, Typora's [Auto Save option](http://support.typora.io/Auto-Save/) was enabled. I found both files in the `draftsRecover` folder. There was much rejoicing. Too soon.

I realized, that although the newer, almost empty file seemed complete, the two-weeks old file with lots of words in it now consisted only of the top heading and the first sentence. Inspecting the file further, it had been created two weeks ago, but **the draft file never got updated**. The activity protocol in `typora.log` has entries for today, but none for yesterday or the day before, although I worked on the file several times in the past 72 hours (And had opened it about a week ago). There are several `ERROR`s like this recorded in the log:

```
wrapExeFunc Timed out window.onWindowFocus && window.onWindowFocus()
```

Today, there were also `INFO`s like this seconds before that error message, for every file I had opened:

```
addRecentDocument
secondary instance would exit
```

Unless I'm missing something, Typora 0.9.36 seems to have a serious bug there. Is there any other place I should be looking for a temporary file that may still hold my lost content?

PS: I'm usually using Mac OS X and are probably spoiled by its beautiful system-level auto-saving. That's why I didn't bother to manually save the files I was working on.

**Comment by abnerlee** [comment] 2017-09-16 04:50
On Windows, auto save will save the file in-place every 5 minutes by default, auto-save can only work on files that exists in your file system.

"draft file" in `draftsRecover` are used only for recovery in case typora get crashed, or lose content, so it will not get update, but keep creating new files. They are not the auto saved files, but only backups.

However, we will limit the total size of `draftsRecover` in future updates.

The Error in your log will also be fixed in next version up

**Comment by Crissov** [comment] 2017-09-16 06:19
I don't believe losing content in any situation is or should be intended behavior. Whether it should have created a new draft or updated the existing one doesn't really matter as long as the content is still there to be recovered.

**Comment by abnerlee** [comment] 2017-09-16 07:57
No, losing content is not a intended behavior. But we do backup, just in case

**Comment by Crissov** [comment] 2017-09-16 09:07
but I still lost content ...

**Comment by abnerlee** [comment] 2017-09-16 11:00
@Crissov Sorry, that is our critical bug, could you send us <hi@typora.io> the `typora.log`? And what happened before you find the data lose, or can we reproduce it? Also does the files in `draftsRecover` help?

**Comment by Crissov** [comment] 2017-09-16 11:20
Like I said, Windows Update wanted to reboot automatically and forced all applications too quit, including Typora. Your app did not crash in the process as far as I can tell. The file in `draftsRecover` did not help, because it only contained a _very_ old state of the content. I can send you the link when I'm back at the computer, but as far as I can tell it won't show anything I didn't already mention above.

**Comment by abnerlee** [comment] 2017-12-15 03:53
Should be fixed in new release. Backup will be written in `draftsRecover`.

But forced quitting applications is still risky.

**Closed by abnerlee** 2017-12-15 03:53 UTC
