### ISSUE TITLE
0.9.92 + pandoc 2.10 failed to export word(docx) while markdown file has tables.

### ISSUE THREAD

**Issue by juejian** [typora/typora-issues#3697] opened 2020-07-13 12:59 UTC
**config :** windows10 x64 + pandoc-x86-64 v2.10(pandoc-types 1.21)

**markdown content**

```
测试导出含表格的 markdown

| title1 | title2 |
| ------ | ------ |
| 20     | 30     |
```

**markdown preview**

![image](https://user-images.githubusercontent.com/12257223/87306621-dc26bf00-c54a-11ea-9f65-3ea91b28f342.png)

**export word error** `couldn't read native`

![image](https://user-images.githubusercontent.com/12257223/87306744-11331180-c54b-11ea-938a-ee1b3897387a.png)

**typora.log output**

![image](https://user-images.githubusercontent.com/12257223/87306846-34f65780-c54b-11ea-999e-eee4cd0805ab.png)

**after delete tables,export word sucessfully**

![image](https://user-images.githubusercontent.com/12257223/87306911-4e979f00-c54b-11ea-8bc9-9b504c551181.png)

**and after testing, only if markdown has tables, the above error  will occur. but while having images and codes,exporting word is sucessful**

**pandoc version**

![image](https://user-images.githubusercontent.com/12257223/87306569-c913ef00-c54a-11ea-9cac-3ab8221ba83e.png)

**Comment by abnerlee** [comment] 2020-07-20 14:59
caused by https://github.com/jgm/pandoc-types/issues/73

If we support pandoc 2.10, then we have to drop support for pandoc < 2.10

**Comment by xzhang777** [comment] 2020-08-04 18:28
Is there a workaround of this?

**Comment by abnerlee** [comment] 2020-08-06 15:10
For now, workaround is to downgrade the pandoc version before 2.10

Typora will support version 2.10 in next version up

**Comment by abnerlee** [comment] 2020-08-30 03:37
should be fixed

**Closed by abnerlee** 2020-08-30 03:37 UTC
Labels: import/export
