### ISSUE TITLE
Export more meta data in YAML Front-matter when export

### ISSUE THREAD

**Issue by admin-teametry** [typora/typora-issues#1333] opened 2018-03-18 14:29 UTC
Hi,

Typora actually only exports the <title> attributed of the Front-Matter.
Author, date, tags, keywords, subject are not exported.

Seems to be a bug for me.

Andreas

**Comment by vassudanagunta** [comment] 2018-04-12 15:12
Not a bug. YAML is an open ended space for metadata. There are no standard metadata items, though there are some, such as those you list, that are supported by many tools that process Markdown (e.g. Jekyll). For those Markdown-based tools all Typora has to do is write the YAML header properly in the Markdown file.  

Is there some specific other output format that Typora supports (e.g. PDF) for which Typora should translate additional metadata fields? If so, please name them. Otherwise, I think you can close this @abnerlee.

**Comment by RootofalleviI** [comment] 2018-12-11 15:48
Can Typora export "title", "category", "author", and "date" to exported html in some sort?

**Comment by jgclark** [comment] 2020-01-11 14:15
@RootofalleviI said:

> Is there some specific other output format that Typora supports (e.g. PDF) for which Typora should translate additional metadata fields? If so, please name them. Otherwise, I think you can close this @abnerlee.

Your challenge got me to look up the [PDF documentation at Adobe](https://helpx.adobe.com/acrobat/using/pdf-properties-metadata.html). They say:

> The title, author, subject, and keywords may have been set by the person who created the document in the source application, such as Word or InDesign, or by the person who created the PDF. You can search for these description items to find particular documents. 

Therefore it would be natural to have PDF export include info from YAML fields for author, subject and keywords/tags where given.

**Comment by ChaunceyHoover** [comment] 2021-03-08 19:05
Just wanted to re-visit this since it's been a year instead of opening a new issue. Any updates or ETA for this feature?

**Comment by abnerlee** [comment] 2021-04-27 08:41
supported, see https://support.typora.io/Export/#export-yaml-meta
and https://support.typora.io/YAML/#use-as-variables-on-export

**Closed by abnerlee** 2021-04-27 08:41 UTC
Labels: import/export
