### ISSUE TITLE
typora wrongly escapes # to %23 in hyperlink which contains non-ascii chars

### ISSUE THREAD

**Issue by guyingzhao** [typora/typora-issues#2850] opened 2019-09-24 02:52 UTC
normal case:
`[foo](https://www.foo.com#bar)`->`https://www.foo.com#bar`

error case:
`[foo](https://www.foo.com#中国`]->`https://www.foo.com%23%E4%B8%AD%E5%9B%BD`

In error case, `#` was unexpected escaped to `%23` and would leading to a mistaken url.

**Comment by abnerlee** [comment] 2019-09-26 16:18
I cannot reproduce this, what's your Typora version?

**Comment by guyingzhao** [comment] 2019-09-27 01:55
![image](https://user-images.githubusercontent.com/22538408/65736224-e63b1680-e10c-11e9-8220-1739a6b3b375.png)

**Comment by abnerlee** [comment] 2019-10-13 17:21
should be fixed

**Closed by abnerlee** 2019-10-13 17:21 UTC
Labels: bug
