### ISSUE TITLE
folder browser and multiple tabs

### ISSUE THREAD

**Issue by jeffreyjohnens** [typora/typora-issues#296] opened 2016-09-18 00:04 UTC
This is quite easily the best looking markdown editor.
Is it possible to have a folder browser panel on the side and support for multiple tabs.

Thanks for your consideration

**Comment by pravin** [comment] 2016-09-28 16:27
+1 For the folder view. Often I work with multiple files and it would be so awesome to have a panel like textmate/atom/sublime

**Comment by yfwz100** [comment] 2016-10-17 01:07
I think it should be implemented as an extension if Typora has the plan for it.

**Comment by vassudanagunta** [comment] 2016-10-17 20:04
Dupe of #57

**Comment by abnerlee** [comment] 2016-10-18 02:26
Dupe of #57

And for macOS users, upgrade to macOS sierra, and multi tab is supported.

**Closed by abnerlee** 2016-10-18 02:26 UTC

**Comment by mc90716** [comment] 2016-10-31 11:33
The typora looks great,and when typora support multi tab,thanks.

**Comment by mhenry1384** [comment] 2019-03-18 18:57
Not having tab support is more irritating than I would have imagined.
