### ISSUE TITLE
Pandoc import not work on mac os

### ISSUE THREAD

**Issue by czhiling** [typora/typora-issues#1038] opened 2017-11-10 09:43 UTC
Typora Version 0.9.9.10.9 
pandoc 2.0.1.1
Mac os High Sierra 10.13.1 (17B48)

I have tried to install pandoc via Brew as well as pkg downloaded from pandoc official website. 

When I drag .doc files to typora.,an empty window opened and nothing imported or converted to the typora. 
When I click 'import' from file menu, nothing happed.

**Comment by abnerlee** [comment] 2017-11-11 04:34
> When I click 'import' from file menu, nothing happed.
You mean even no open file dialog pop up to select files for import?

**Comment by abnerlee** [comment] 2017-11-11 08:21
@czhiling Hi, I tested with Pandoc v2.x, it seems OK. If possible, could you send us (hi@typora.io) a sample docx file that cannot be imported ?

Best Regards

**Comment by czhiling** [comment] 2017-11-14 13:58
Thank you very much for your reply. I mean there were no open file dialog pop out to select files. 
I turned on debug from Typora menu. 
![console__6_messages_](https://user-images.githubusercontent.com/218637/32783355-0a470072-c911-11e7-905f-e837b8a83499.jpg)

**Comment by cbertelli** [comment] 2017-11-25 10:52
The same happens for me with pandoc 1.19.2.1 installed with brew on MacOS 10.9.
Choosing **import** from the File menu does not open any dialog to open files.

**Comment by czhiling** [comment] 2017-11-26 06:33
Many thanks! @cbertelli It works.

**Comment by abnerlee** [comment] 2017-11-26 16:53
The settings is irrelevant with pandoc import... And I cannot reproduce this on my Macbook

**Comment by cbertelli** [comment] 2017-11-26 22:19
I cannot explain the logically unrelated phenomena, but I can reproduce this behaviour. I (unreasonably) think that checking the OS (to tell if iPic is available) does something useful. Obviously pandoc works on the command line with no connections to Typora. Consider my OS is 10.9 and pandoc is installed via brew (there is no pandoc framework), it's a peculiar configuration by the time being.

**Comment by czhiling** [comment] 2017-11-26 23:48
I an using MacOS 10.13.1 (17B48). I have tried both brew installation and pkg installation. Same prbolem and got no lucky. 
I was trying to find something useful from logs but...

**Comment by abnerlee** [comment] 2018-01-14 05:04
@czhiling I added some logs in v0.9.9.11.2 on the process of checking pandoc installation.

Could you try open `Console.app`, clear logs, then use Typora to export something as docx, then check newly printed logs in `Console.app`.

You could search by keyword Pandoc, and the paste or send us (hi@typora.io) related logs that  mentioned "Pandoc".

**Comment by cbertelli** [comment] 2018-01-14 09:16
Here is a log, trying to export to Word (docx):
https://gist.github.com/70333664305047e2ec51d59f445e28fc

**Comment by abnerlee** [comment] 2018-01-14 09:38
@cbertelli Thanks, From the logs, seems Typora failed to detect the path of pandoc.

Could you try input `/bin/bash` and return in terminal.app
then input `which pandoc -l -c`, and tell us the full output?

**Comment by cbertelli** [comment] 2018-01-14 09:59
I think it's unrelated, but I will try to upgrade pandoc to version 2.1.

**Comment by cbertelli** [comment] 2018-01-14 12:51
... and here is the log with version 2.1
https://gist.github.com/ed118e44131e59827e0ecccb0c8d137d

**Comment by abnerlee** [comment] 2018-01-25 03:24
should be fixed in latest version.

**Comment by abnerlee** [comment] 2018-01-25 03:24
also relates https://github.com/typora/typora-issues/issues/1169

**Closed by abnerlee** 2018-01-25 03:24 UTC
Labels: bug

**Comment by RXHem** [comment] 2022-01-26 12:49
tried installation on an M1 Silicon Mac and it works like a charm.
