### ISSUE TITLE
Sometimes the symbol  "  may make typora out of work.

### ISSUE THREAD

**Issue by stonejing** [typora/typora-issues#250] opened 2016-08-05 09:19 UTC

**Comment by abnerlee** [comment] 2016-08-05 09:50
@stonejing I received such bug report, but I still cannot reproduce it, do you know how to reproduce it.

Also, it seems same to #240, could you reproduce that either ?

**Comment by stonejing** [comment] 2016-08-06 12:54
Description:
  Indeed, it may happen in a special case when I input a second " " symbol
to include a long sentence.
  It is hard to reproduce it again, but I tried a lot times to ensure that
the bug was real, typora stopped worrking when I input a second ".

  Environment:
  windows 10
  typora 0.9.15 (beta)

2016-08-05 17:50 GMT+08:00 AbnerLee <notifications@github.com>:

**Comment by stonejing** [comment] 2016-08-07 06:03
Today, i met this case for two times. And the following piuctures are the
mistake. When i input  "  at last, then typora will stop working, but
it will still cost too much resource of CPU.

​

2016-08-06 20:54 GMT+08:00 Jing Stone <stonejing1817@gmail.com>:

**Comment by abnerlee** [comment] 2016-08-07 09:14
@stonejing Hi, when it happens, could you send me your *.md file or a sample *.md file includes your current paragraph which may cause this bug (before your insert the second quote)? And tell the position you insert a second quote at? I will try many times to reproduce the exact bug.

**Comment by stonejing** [comment] 2016-08-08 15:18
OK, but this may take a few days, because this mistake can only happen when
there are some " symbol.


2016-08-07 17:14 GMT+08:00 AbnerLee <notifications@github.com>:

**Comment by stonejing** [comment] 2016-08-08 15:27
In the last paragraph, if i input the " with one space or more, then
typora will stop working, but if i input " with no space, it works well.

2016-08-08 23:18 GMT+08:00 Jing Stone <stonejing1817@gmail.com>:

**Comment by abnerlee** [comment] 2016-08-19 14:49
Fixed in new version

**Closed by abnerlee** 2016-08-19 14:49 UTC
Labels: bug
