### ISSUE TITLE
File Tree menu didn't work in Linux, hang on `loading ...`

### ISSUE THREAD

**Issue by maestrofx** [typora/typora-issues#1029] opened 2017-11-06 11:23 UTC
Hi there,
There's something unstable condition where switching to File Tree, it's hanging on `loading ...`. Sometimes, it works well, but in unpredictable condition, mostly it's `loading ...`-only status.

This affects on Linux machine only, it works well in Win-based machines.

Environment

> Typora: v0.9.38(beta)
> OS: Debian-based
> 

Thank you

**Comment by abnerlee** [comment] 2017-11-13 09:56
Does Typora have read access to the folder? Could you confirm it on v0.9.38?

**Comment by maestrofx** [comment] 2017-11-15 05:41
@abnerlee , still in v0.9.38!
Basically, the file tree works for, say, not so many files/folders, but for the directory contains a lot of files/folders, it didn't work.

**Comment by abnerlee** [comment] 2017-11-15 07:06
I see, could you send us <hi@typora.io> related log file?

You could find log file following http://support.typora.io/Report-Bugs/#linux

If possible, could you also attach the log from `View` -> `Toggle DevTools` after you enable debug mode in preference panel?

That could be helpful.

**Comment by maestrofx** [comment] 2017-11-16 08:25
emailed!

**Comment by maestrofx** [comment] 2017-12-04 05:38
@abnerlee, any update on this issue?

**Comment by abnerlee** [comment] 2017-12-04 09:52
We cannot reproduce this, but we can find the reason from your log file, that error happens when Typora try to "watch" your folder by node.js.

We will try to fix this in next version up

**Comment by abnerlee** [comment] 2017-12-15 03:27
fixed in new release

**Closed by abnerlee** 2017-12-15 03:27 UTC
