### ISSUE TITLE
Freezes on open any .md files when using unibody mode

### ISSUE THREAD

**Issue by Epitapher** [typora/typora-issues#3019] opened 2019-11-15 07:16 UTC
The windows freezes on open any .md files when using unibody mode, all buttons are not shown correctly. If start from start menu instead of opening files it works fine. Only unibody mode behaves this way, the normal mode always works.

OS: Win10  (in dark theme, if it's relevant)
version: 0.9.79 x64
screenshot:
NOTICE THAT ALL BUTTONS ARE NOT SHOWN CORRECTLY
![a](https://user-images.githubusercontent.com/27178583/68923976-a31b2c80-07ba-11ea-8169-2413665c87be.png)

**Comment by abnerlee** [comment] 2019-11-17 15:24
I cannot reproduce this one, possible to send us hi@typora.io the sample file and log file in C:\Users\{user}\AppData\Roaming\Typora\typora.log, and do you have any anti-virus app that may block Typora from loading local file?

**Comment by gotjek** [comment] 2019-11-17 17:52
When I got a freeze like in this bug (#2997), I sometimes view these strange buttons.
I deactivated unibody mode and I have had no freeze until now !

**Comment by Epitapher** [comment] 2019-11-18 05:21
> I cannot reproduce this one, possible to send us [hi@typora.io](mailto:hi@typora.io) the sample file and log file in C:\Users{user}\AppData\Roaming\Typora\typora.log, and do you have any anti-virus app that may block Typora from loading local file?

Already sent. It sometimes work sometimes doesn't.

**Comment by abnerlee** [comment] 2019-11-19 14:24
do you have any anti-virus app that may block Typora from loading local file?

**Comment by Epitapher** [comment] 2019-11-22 11:24
> do you have any anti-virus app that may block Typora from loading local file?

No, the only anti-virus app is windows defender and it's not blocking typora.

**Comment by gencer** [comment] 2019-11-30 14:16
I've the same problem. Not just MD files but empty typora (just laucnh) hangs. I see the caret/cursor and UI. That's all. Cannot open preferences or anything. It just freezes. Also using unibody.

**Comment by VaslD** [comment] 2019-12-04 05:12
I can confirm this issue is reproducible on my machine. Logs below:

[Launch Typora, try to type something, Typora hangs.](https://github.com/typora/typora-issues/files/3920103/typora.log) NOTE: It doesn't *stop responding*, meaning I can still close it by right clicking the Taskbar, right-click its window and **Close**. (I can't do anything in the Typora window itself, including using the close button. But I can arrange its window using Taskbar right-clicks.)

[Relaunch, no issue this time.](https://github.com/typora/typora-issues/files/3920110/typora.log)

If I relaunch Typora couple more times, the issue gets triggered occasionally. Logs don't show much. I already examined them myself and they were pretty much the same with or without hang, with or without using unibody style.

I also disabled auto updates just to confirm you're not downloading JSON on the main dispatcher, issue was still present.

Can't speak for others, I'm only running built-in Windows Defender (*Windows Security* with *Virus & threats protection*), and built-in Firewall.

**Comment by afkbrb** [comment] 2019-12-10 07:17
I met the same problem as @VaslD, too.  The problem only occurs recently (in about a month), maybe the recent updates for Typora lead to it.

**Comment by 0w0miki** [comment] 2019-12-23 05:51
I met the same problem as @VaslD in the last few weeks.
I can confirm this issue happens from 0.9.80 to 0.9.81.

However, version 0.9.77 works well on the same computer with nothing changes. I have tested this on both Win 10 1809 and 1903.
I also tried to clean all all files in `C:\Users{user}\AppData\Roaming\Typora\`, but it did not help.

**Comment by VaslD** [comment] 2019-12-23 15:02
I have more info on this issue, maybe irrelevant, just in case.

I see #3088 got merged and I realize I do have Chinese (China) and Japanese locale set up in Windows language settings, although neither was default. I need their IMEs occasionally for work. English (U.S.) is always the UI language I set for Windows and any application.

The hang happens after the Typora window is fully loaded visually. Sometimes I may be able to get a character in or highlight the menu button (top left) before the window starts to freeze.

I have Windows display scaling set to 200% (not 100%) to compensate this small screen and my sore eyes. Applications are seen to behave poorly when they don’t want to be blown up by Windows. I haven’t seen any element misplacement or graphic glitch in Typora though.

**Comment by gencer** [comment] 2019-12-23 16:56
Just to add this, My Windows UI also English but locale is Turkish, however, similar to @VaslD i have 4K screen with 125% DPI. Maybe this DPI is the key here.

**Comment by scannermobs** [comment] 2020-03-08 08:42
Just to say I'm having the same issue, but my scaling is set to 100%.

**Comment by fparol4** [comment] 2020-05-04 15:01
+1, i swiched to classic mode and it looks solve the problem.

**Comment by abnerlee** [comment] 2020-05-24 13:59
I updated Electron version, is this fixed?

**Comment by 0w0miki** [comment] 2020-05-24 14:33
> 
> 
> I updated Electron version, is this fixed?

Version 0.9.88 works for me.

**Comment by scannermobs** [comment] 2020-05-25 05:48
Hi, yes this appears to be fixed now. Many thanks!

—

Ben

**Closed** 2020-06-01 16:21 UTC
Labels: bug, windows
