### ISSUE TITLE
German text printing

### ISSUE THREAD

**Issue by cubeslicer** [typora/typora-issues#1441] opened 2018-04-24 05:36 UTC
Hi,
I came across a issue when printing - no matter if to paper or to pdf. There seems to be a issue with the umlaut "ü" (ue), when preceded with an "l", but not only. See the attachment.
Thx
Martin Wagner 
![german_printing_problem](https://user-images.githubusercontent.com/38680828/39167952-21db4d60-4792-11e8-8e24-ab3c80c4fe5a.jpg)

**Comment by cubeslicer** [comment] 2018-04-24 05:39
I forgot: I´m using  Typora on windows 10
![image](https://user-images.githubusercontent.com/38680828/39168031-9048f676-4792-11e8-9987-70f298f052e8.png)

**Comment by abnerlee** [comment] 2018-04-24 06:25
Could you attach the sample md file or send it to us (hi@typora.io)?

And system language in your PC is German right?

**Comment by cubeslicer** [comment] 2018-04-24 11:45
Hi,
thanks for the quick response. Here is the MD-File, I had to zip it because of github restrictions. . And yes, I use german system language .

[German_printing_Problem.zip](https://github.com/typora/typora-issues/files/1942552/German_printing_Problem.zip)

**Comment by abnerlee** [comment] 2018-04-24 15:38
Tried after set lang to de, but cannot reproduce this.

@cubeslicer could you also attached the output PDF?

If you export to HTML, then print in Chrome, will this bug happen?
If you export to PDF via `File` -> `Print` from menubar, will this happen?

**Comment by abnerlee** [comment] 2018-04-25 07:51
> and when using the file menu export to pdf it is also ok

Does it mean if you do `File` -> `Export` -> `PDF` from menu bar
Or do Print, then use default/microsoft PDF printer, the output PDF is fine?

**Comment by cubeslicer** [comment] 2018-04-25 13:31
The File >Y Print> "Microsoft Print PDF" driver produces good PDF files, 
also when I use File -> Export -> PDF from menu bar the result is ok.

**Comment by abnerlee** [comment] 2018-04-25 14:04
This is issue of PDF Architect 5.

Closing this therefore

**Closed by abnerlee** 2018-04-25 14:04 UTC
