### ISSUE TITLE
Sometimes the formula is not centered properly

### ISSUE THREAD

**Issue by wyf88** [typora/typora-issues#178] opened 2016-06-03 09:05 UTC
For example, the following two lines of formula:
$$\sigma^{-1} \sim \text{Gamma}(a_{0\sigma}, b_{0\sigma}),\quad \boldsymbol{\alpha} \sim N(\boldsymbol{\alpha}_{0}, \boldsymbol{\Sigma}_{0\alpha}),\\ \boldsymbol{\mu} \sim N(\boldsymbol{\mu}_{0}, \boldsymbol{\Sigma}_{0\mu}),\quad \boldsymbol{\Phi}^{-1} \sim \text{Wishart}(\mathbf{R}_{0}, \rho_{0}),$$
is not centered properly (Mac & Windows, every version). This is the only case that I encountered. I have tried to modified the latex code to find a pattern for the display error, but without luck. Any idea why? Thanks.

**Comment by wyf88** [comment] 2016-06-03 09:11
And I find another bug when I am reporting this bug... When I copy the whole comment above and paste to Typora (Windows), some of the sentences and the formula are pasted twice.

**Comment by smallx** [comment] 2016-06-03 09:19
@wyf88 

> And I find another bug when I am reporting this bug... When I copy the whole comment above and paste to Typora (Windows), some of the sentences and the formula are pasted twice.

For this problem, I have seem for some times. It usually happen when the content your pasted contains multi paragraph and these paragraph begin with “Tab” or ...

Sorry for my bad English. :smiley:

**Comment by wyf88** [comment] 2016-06-03 09:25
@smallx Thanks for your feedback!

**Comment by abnerlee** [comment] 2016-06-03 09:48
@wyf88 for the LaTeX part, currently display math should be wrapped with $$ and line break. For instance:

```
$$
\sigma^{-1} \sim \text{Gamma}(a_{0\sigma}, b_{0\sigma}),\quad \boldsymbol{\alpha} \sim N(\boldsymbol{\alpha}{0}, \boldsymbol{\Sigma}{0\alpha}),\\ \boldsymbol{\mu} \sim N(\boldsymbol{\mu}{0}, \boldsymbol{\Sigma}{0\mu}),\quad \boldsymbol{\Phi}^{-1} \sim \text{Wishart}(\mathbf{R}{0}, \rho{0}),
$$
```

Or else adding $ or deleting $ could cause block level change, and now I haven't good ideas to solve that scenario.

And meanwhile, $$some code$$ is treated as inline math, temporary. 

---

For the paste bug, yes, I can reproduce it. We will fix this in future updates.

**Comment by wyf88** [comment] 2016-06-03 14:06
@abnerlee I see, thanks for the explanation!

**Comment by abnerlee** [comment] 2018-01-25 03:09
Closing this since paste bug has been already fixed.

**Closed by abnerlee** 2018-01-25 03:09 UTC
Labels: bug
