### ISSUE TITLE
Malformed input, repository not added.

### ISSUE THREAD

**Issue by MiguelNiblock** [typora/typora-issues#2065] opened 2019-01-08 01:04 UTC
When I run:
```
sudo add-apt-repository 'deb https://typora.io/linux ./'
```
I get:
```
Malformed input, repository not added.
```
Running Linux Mint 19.1

**Comment by abnerlee** [comment] 2019-01-09 09:44
You could also try

```
sudo add-apt-repository 'deb https://typora.io linux/'
```

For alternative ways in https://support.typora.io/Typora-on-Linux/

**Comment by bjadamson** [comment] 2019-01-16 09:55
I'm also getting this on Linux Mint

**Comment by bjadamson** [comment] 2019-01-16 19:31
Oh whoah I just assumed this was still opened when I commented. Yeah please re-open!

**Comment by brbernardo90** [comment] 2019-01-16 20:44
I have de same issue, Mint 19.1

**Comment by moyersmike** [comment] 2019-01-18 11:59
Just tried that command on Linux Mint 19.1, receiving the same error as before @abnerlee .

**Comment by MiguelNiblock** [comment] 2019-01-18 23:00
> Does
> 
> ```
> sudo add-apt-repository 'deb https://typora.io linux/'
> ```
> 
> work? @brbernardo90 @bjadamson @sternj

Still doesn't work. Im currently using the portable binary version, which doesn't integrate with my desktop. That's the only way I've been able to use the latest build on Mint.

**Comment by rbbernardino** [comment] 2019-01-19 23:48
Me too on Mint 19.1, it seems to be specifically to this version...

**Comment by abnerlee** [comment] 2019-01-20 03:15
Closing this since it is an issue specific to  Mint 19.1

**Closed by abnerlee** 2019-01-20 03:15 UTC
Labels: linux

**Comment by rbbernardino** [comment] 2019-01-20 15:55
### Solution
@MiguelNiblock @bjadamson @brbernardo90 I have managed to get it working! Simply add it manually by editing the file `/etc/apt/sources.list` and adding the line `deb https://typora.io/linux ./`
You may do that also just by running:
```bash
echo -e "\ndeb https://typora.io/linux ./" | sudo tee -a /etc/apt/sources.list
```

### Explanation:
I have realized the `add-apt-repository` of Linux Mint is different from the Ubuntu original one. By instance, if you try `-m` option (debug), it will not work in Mint, which seems to be a much simpler (and maybe old) version of this program. In Ubuntu, it seems to be provided by `software-properties-common` package, while Mint replaced it with `mintsources`.

I have added several software sources in the past and indeed this format is not so common, generally there are two arguments after the url, like in the following examples (`non-free` and `main`):
```bash
deb [arch=amd64] https://repo.skype.com/deb stable **main**
deb http://repository.spotify.com stable **non-free**
deb https://deb.nodesource.com/node_11.x bionic **main**
```

So it seems the Mint `add-apt-repository` doesn't accept any input missing the last argument. However, if you manually add it to the `sources.list` and run `sudo apt update` everything will work **just fine** :smile:

**Comment by MiguelNiblock** [comment] 2019-01-21 08:07
OMG this finally worked! Im so childishly excited! hahaha

**Comment by luoshenzhi** [comment] 2019-05-09 05:40
relocation error: /usr/local/bin/Typora-linux-x64/resources/app/node_modules/spellchecker/node_modules/cld/build/Release/cld.node: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE14_M_replace_auxEmmmc, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

**Comment by invzbl3** [comment] 2019-08-17 20:50
I have reproduced this issue 
`Malformed input, repository not added.`

on Linux Mint 19.2 using the command:
`sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(. /etc/os-release; echo "$UBUNTU_CODENAME") stable"`

So I downgraded version of Linux Mint 19.2 to 19 and solved it. I think this problem is for newer versions after 19. Like 19.1, 19.2 and so on. As mentioned @rbbernardino you can add manually lines to repositories file in alternative way.

**Comment by PrimeTime416** [comment] 2019-08-18 17:52
Editing file /etc/apt/sources.list.d/additional-repositories.list and adding deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
 worked for me, thanks all.

**Comment by mau21mau** [comment] 2019-08-30 16:44
I fixed by just removing the `[arch=amd64]` from the source.

**Comment by Gong-fa** [comment] 2019-12-05 02:59
[69579:1205/105720.997916:FATAL:atom_main_delegate.cc(210)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
追踪与中断点陷阱

**Comment by LinuxOnTheDesktop** [comment] 2020-01-19 01:40
Please mention this issue - and the workaround - on [https://typora.io/#linux](https://typora.io/#linux).
