### ISSUE TITLE
image filename error

### ISSUE THREAD

**Issue by jtxiaocom** [typora/typora-issues#4688] opened 2021-09-28 09:57 UTC
1. Open [https://mp.weixin.qq.com/s/cbeySDrNOxyCrA46-squ_A](https://mp.weixin.qq.com/s/cbeySDrNOxyCrA46-squ_A)
2. Copy content include more than two pictures.
3. Paste in Typora.
4. You will found all pictures are same.

Typora should rename all image filename paste from web!

**Comment by abnerlee** [comment] 2021-11-07 06:56
should be fixed in 0.11.16

**Closed by abnerlee** 2021-11-07 06:56 UTC
Labels: bug, images / resouces

**Comment by qigtang** [comment] 2021-11-07 21:21
Tested latest Typora version 0.11.17.  Unfortunately the issue is not exactly fixed.

My setting is 
The preferences -> Image -> When inserting -> copy image to ./${filename}.assets.

Old behavior:
- if copying html, images will be copied to local folder, but some of them having the same names. 

New behavior:
- if copying html, images are not copied, still pointing to online url. So the rendered markup file is correct regarding to displayed image. But it is not exactly what we would prefer. Because when copying online html, for example, to keep a record, we are assuming the online website might be deleted in the future. By still keeping image as online url, there is chance the copied markdown files will miss the images.

I would appreciate if we still keep old behavior of copying image to local, but make sure its names are unique.   Like using sha1 hash of the image file, or just internally generate uuid. 

Thanks!

**Comment by abnerlee** [comment] 2021-11-11 11:37
Did you apply the "When inserting" rule to online images as well?
