### ISSUE TITLE
No Name being shown in Linux Update Manager

### ISSUE THREAD

**Issue by g0ukb** [typora/typora-issues#1375] opened 2018-04-03 07:26 UTC
Running latest Mint 18.3 Cinnamon with Typora ppa repository. Linux Update Manager alerted me to a new update but no application name (screenshot enclosed). Installing from command line `sudo apt-get update && sudo apt-get upgrade` confirms this as Typora.

The description in Update manager correctly says "markdown editor".

Additionally the changelog is blank. It would be good to see the changelog information being displayed.

![image](https://user-images.githubusercontent.com/2264432/38235179-1e07e28c-3718-11e8-8c50-97ca30b76c78.png)

**Comment by abnerlee** [comment] 2018-05-01 11:33
Works fine in "Software Updater" on Ubuntu.

Close this since we do not have Mint to reproduce this

**Closed by abnerlee** 2018-05-01 11:33 UTC
