### ISSUE TITLE
MathJax equation is incorrectly exported to word in if it contains the "\over" command

### ISSUE THREAD

**Issue by vertesy** [typora/typora-issues#997] opened 2017-10-26 09:17 UTC
#### 1. Equations with `\over`are incorrectly exported to `.docx`

I am trying to export a document with the following equation:

$${d( A^{X}) \over dt} = (k · B · C^{Y2} · D − e · F^{Y3} \label{j}$$

It does not render in word, whereas it does in PDF.

[I guess it is related to `\over` being a  "a TeX primitive":](https://github.com/jgm/pandoc/issues/1393)

#### 2. Equation references are broken:

`$ \eqref{j} $` is just exported as a string.

*This could be moved to a separate issue.*
- Probably related to [pandoc issue #1938](https://github.com/jgm/pandoc/issues/1938).
- And also to the fact that equations in the exported word document do not have numbering.

### Workaround for 1. is to use `\frac`

Nevertheless `\frac` is a lot less clean / more confusing when looking at the raw equation.

Instead of the `A-over-B`, it has to be written `frac-{A}-{B}`

$$ { \frac{d( A^{X})} {dt} } $$

handling `\over` would be great.

**Comment by abnerlee** [comment] 2017-12-15 03:47
Export to docx calls Pandoc, so it can be fixed if it is fixed in Pandoc.

Please reopen this issue, it is not caused by Pandoc but by Typora

**Closed by abnerlee** 2017-12-15 03:47 UTC
