### ISSUE TITLE
Touch Bar Paragraph Buttons Offset Improperly

### ISSUE THREAD

**Issue by thirdgen88** [typora/typora-issues#681] opened 2017-05-05 16:15 UTC
When using Typora in a body-text section, clicking the "Paragraph" button on the Touch Bar (15" 2016 rMBP) results in an offset button set.

Here is the initial place where I select the "Paragraph" button:
<img width="1085" alt="touch bar shot 2017-05-05 at 11 14 35 am" src="https://cloud.githubusercontent.com/assets/7111175/25754226/11bea9b0-3184-11e7-8cf3-e5b30ae24cd1.png">

Here is the offset buttons issue:
<img width="1085" alt="touch bar shot 2017-05-05 at 11 11 53 am" src="https://cloud.githubusercontent.com/assets/7111175/25754179/efd0489a-3183-11e7-9935-77cfe9b1d5a0.png">

**Comment by abnerlee** [comment] 2017-05-07 13:33
I got such report from some users who use an external display, so I still cannot reproduce it

**Comment by Hicola** [comment] 2017-05-31 02:33
I have it too. 
<img width="1085" alt="multi-touch bar 2017-05-31 10 29 34" src="https://cloud.githubusercontent.com/assets/13960874/26613278/9916012a-45ec-11e7-805d-5eb5e27bce9d.png">
<img width="1085" alt="multi-touch bar 2017-05-31 10 29 31" src="https://cloud.githubusercontent.com/assets/13960874/26613279/99178bc6-45ec-11e7-80fd-230861804772.png">

**Comment by thirdgen88** [comment] 2017-06-01 01:20
I've actually seen this behavior in the Bear app ([http://www.bear-writer.com](http://www.bear-writer.com)) as well--it seems that it isn't all that uncommon..  
<img width="1085" alt="touch bar shot 2017-05-31 at 8 19 28 pm" src="https://cloud.githubusercontent.com/assets/7111175/26660568/81e37ae4-463e-11e7-9a1c-0e81322fad84.png">

**Comment by abnerlee** [comment] 2017-08-11 08:29
I never met this, does this bug still happens on the newest version?

**Comment by thirdgen88** [comment] 2017-08-17 16:50
The behavior is still present as of 0.9.9.10.3

**Comment by abnerlee** [comment] 2018-01-25 03:00
should be fixed in v0.9.9.12

**Closed by abnerlee** 2018-01-25 03:00 UTC
Labels: bug
