### ISSUE TITLE
Connflicting distribution & closed immediately

### ISSUE THREAD

**Issue by bxk-sonavex** [typora/typora-issues#633] opened 2017-04-04 13:07 UTC
When installing it on Ubuntu 14.04, I got the following message
```
W: Conflicting distribution: https://typora.io ./linux/ InRelease (expected ./linux but got )
```

It looks typora installed successfully using `sudo apt-get install typora`.  However, the program closed immediately after the GUI displayed.  No any error message.

I really like typora, but not able to use it; so sad...

**Comment by abnerlee** [comment] 2017-04-04 15:06
@bxk-sonavex could you try launch typora from terminal by inputing "input" and press return?

Then check if there are error message in terminal.

And the crash may be caused by some issue with linked depended library, maybe install Chrome could fix this, since its dependencies are almost same with Chrome

**Comment by bxk-sonavex** [comment] 2017-04-04 15:16
I typed "typora" in the terminal and got
```
/usr/share/typora/Typora: relocation error: /usr/share/typora/resources/app/node_modules/spellchecker/build/Release/spellchecker.node: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

**Comment by abnerlee** [comment] 2017-04-04 15:27
@bxk-sonavex  No, no need to install yagi

**Comment by abnerlee** [comment] 2017-04-04 15:29
I will check based on the error info to see how to avoid this in future.

**Comment by bxk-sonavex** [comment] 2017-04-10 17:20
Is there a workaround so that I can use typora?  I installed Chrome but did not get it fixed.

**Comment by abnerlee** [comment] 2017-04-13 07:33
There's no easy "workaround", you could google `version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 ` for possible solution.

**Comment by abnerlee** [comment] 2017-12-13 14:16
I'm closing this since there's been long time with no further discussion.

And we put some solutions in Trouble Shooting section in http://support.typora.io/Typora-on-Linux/

**Closed by abnerlee** 2017-12-13 14:16 UTC
