### ISSUE TITLE
Issue with Multiple Monitors and Opening New Files

### ISSUE THREAD

**Issue by beaniemonk** [typora/typora-issues#938] opened 2017-09-29 14:59 UTC
I ran into an issue just now in Windows 10.

I have 2 monitors -- one is in landscape for coding/writing. I had a document maximized on the landscape monitor, then opened a second document from that same monitor.

The new document opened with the same dimensions as the existing one (landscape maximized), but it opened on my other (portrait) monitor instead. Thus the title bar was well above the top of the screen and I wasn't able to interact with it.

There are workarounds to resize it, but I just wanted to mention it as a minor usability issue. Thanks!

**Comment by nheeren** [comment] 2017-10-26 08:19
I have the same issue on macOS (10.12.6) and typora  0.9.9.10.8.

**Comment by samdx** [comment] 2017-11-24 16:04
I have a weird issue with multiple monitors.

I currently use Typora 0.9.37 on Windows 10 x64. 

I usually use 3 monitors at work, and when back home I use 1 only, it's the display of laptop. This is when the issue comes in.

When back home, I open Typora and the windows is sent to ... the (image) second monitor, so I can not interact with it. I have tried to use both flip 3D and virtual desktop to 'bring it back' but no luck.

As you can see, the `window-state.json` has `x` values too high, out of range of my screen. I have tried to edit the value manually but it has been reverted back whenever Typora has been launched.

![image](https://user-images.githubusercontent.com/18287802/33217489-2dbf8dfc-d173-11e7-812e-08cfbfb222b1.png)

**Comment by abnerlee** [comment] 2017-11-25 04:46
@samdx please try update to v0.9.38

**Comment by samdx** [comment] 2017-11-25 13:35
@abnerlee Hi,

I have downloaded and installed the latest ver from Website but the version is v0.9.37 only.

Where can I download the ver you've given?

Thanks!

**Comment by abnerlee** [comment] 2017-11-26 15:55
@samdx it may caused by cache of your ISP, could you try "check for updates" from typora menu then?

**Comment by ryanerwin** [comment] 2017-12-01 13:47
I'm using **Typora 9.3.38** on Windows 10 and having the same issue.

I use 2 monitors plus laptop screen when docked, only laptop screen when mobile, and the one Typora window is completely inaccessible... Still on one of my large monitors somewhere, even though I'm disconnected and that monitor is a few hundred miles away... 

Even more unfortunate, every time Typora opens a Window, the X/Y coordinates are somewhere off the mobile screen... presumably on one of my external monitors that aren't currently connected. So now I'm unable to OPEN any of my existing documents in Typora, because they all open on a desktop that I can't even see... With Win+Tab the window is visible, but no interaction from there is possible.

Also, the Save / Cancel warning box doesn't respond to the expected [enter] [esc] keystrokes...

Sticking windows to a consistent place on the screen is great, but seems like when you do that, you need to check if the screen space expected is still available.

**Comment by ryanerwin** [comment] 2017-12-01 13:50
If anyone else runs into this issue, close Typora and delete `window-state.json` in you `\AppData\Roaming\Typora` and Windows will open in the center of your primary, currently attached monitor.

**Comment by atoav** [comment] 2018-01-10 15:23
This seems to be a closed issue, but I still have it with the most current version 0.9.41
Typically when a program disappears offscreen I try to get it back by moving it via `[Win] + Left/Right`. With Typora this doesn't work for some reason.

**Comment by AlexPasternak** [comment] 2018-01-10 15:38
@atoav, when I get into this situation, I usually use the Alt-Space shortcut and trigger the move from there. E.g., https://winaero.com/blog/how-to-move-a-window-using-keyboard-only-in-windows-10-and-other-versions/

**Comment by abnerlee** [comment] 2018-02-09 07:15
Fixed in new version (v0.9.43)

**Closed by abnerlee** 2018-02-09 07:15 UTC
