### ISSUE TITLE
Feature: Quick outline which can be filtered etc.

### ISSUE THREAD

**Issue by Ciantic** [typora/typora-issues#1815] opened 2018-09-20 12:52 UTC
Liking Typora a lot.

One of the features I miss from VSCode is the quick outline, this allows to navigate longer documents much faster.

![image](https://user-images.githubusercontent.com/64731/45819334-b9c80f80-bcec-11e8-8286-4d3590c57cb5.png)

I hit a shortcut (in my case Ctrl+O) and then outline with list of headings appear as a popup. 

I can start typing right away to filter the headings, or navigating with keys downwards. Since I plan to use Typora as a note taker, I don't want to keep outline open as a sidebar, it takes too much space. Quick outline would be fantastic for other cases too.

Thanks for considering.

**Comment by AlexPasternak** [comment] 2018-09-20 13:50
Duplicate of #1591 and probably others.

https://github.com/typora/typora-issues/issues/1591

**Closed** 2018-09-20 13:54 UTC
