### ISSUE TITLE
Cursor stuck after selecting by up or down arrow

### ISSUE THREAD

**Issue by binyominzeev** [typora/typora-issues#3192] opened 2020-01-21 19:34 UTC
Using most recent Typora on Linux, when selecting text with the cursor, as long as I am using the left-right arrows, it works perfectly, but after using up-down arrows, the cursor is stuck and not possible to move anymore to select more text. I can select longer text by mouse only.

**Comment by jdalbey** [comment] 2020-01-22 19:24
I may be experiencing the same issue.  To be specific, most editors allow me to use Shift + cursor to select blocks of text.  In Typora 0.9.83 (beta) on Linux, if I press Shift + down arrow, an entire line is selected, but pressing the down arrow a SECOND time has no effect (when it should select the next line). In fact, it seems as though the cursor freezes and no longer responds to key presses. Clicking with the mouse restores the cursor to normal operation.

**Comment by fresheneesz** [comment] 2020-01-28 07:52
I also see this problem on windows. In fact, using the up or down arrows is not even necessary as long as as the cursor started on the end of the paragraph.

Repro:

1. Write some text
2. Put the cursor at the end of the line (must be end of the paragraph)
3. Hold shift and use the left-arrow once

Now when you try to use the right-arrow (while still holding shift) nothing happens.

**Comment by abnerlee** [comment] 2020-01-29 16:36
@fresheneesz also on Linux?

**Comment by binyominzeev** [comment] 2020-01-29 19:39
Yes, now I tried this on Linux, and same thing happens.

**Comment by binyominzeev** [comment] 2020-01-29 21:45
In a longer file I experience a different behavior: I select the text at the end of paragraph, press the right-arrow, and the whole text is unselected, while cursor is at the end (instead of just deselecting a single character).

**Comment by abnerlee** [comment] 2020-01-31 16:38
I'm not able to reproduce this under Ubuntu 18.04, possible to provide sample file and tell me on which position the cursor will be stuck after up or down key. A screencast is also welcomed.

**Comment by fresheneesz** [comment] 2020-01-31 19:21
[testCursorIssue.txt](https://github.com/typora/typora-issues/files/4141004/testCursorIssue.txt)

1. Change that file to a markdown file
2. place the cursor at the end of the line
3. Hold shift and press left arrow
4. While still holding shift, press right arrow

**Comment by binyominzeev** [comment] 2020-02-01 21:47
Here is the screencast (made on Ubuntu 18.04.3 LTS):

[screencast.mp4.zip](https://github.com/typora/typora-issues/files/4143274/screencast.mp4.zip)

**Comment by jdalbey** [comment] 2020-03-01 15:58
I am no longer experiencing this issue in 0.9.85 (beta).

**Comment by binyominzeev** [comment] 2020-03-01 20:07
Regarding the right-left cursor, the issue is indeed corrected. Regarding the up-down cursor, the bug still exists by me (also in 0.9.85 (beta), Linux).

**Comment by binyominzeev** [comment] 2020-03-01 20:09
(For that bug, it does not even have to be at the end of paragraph. Cursor is stuck at any place.)

**Comment by s3rv4nt** [comment] 2020-03-04 05:52
I'm also experiencing the same bug in Windows using Typora version 0.9.85 (beta). Specifically, if I press shift+up and then, while continuing to hold shift, I press up again, the cursor gets stuck and does not continue to highlight the next amount of characters -- same thing with shift+down and shift+ctrl+<up/down>. When I say that the cursor "gets stuck", what I really mean is that my arrow keys now move the window _scroll-bar_ instead of moving the cursor.

**Comment by abnerlee** [comment] 2020-05-23 14:27
should be fixed in latest version

**Closed by abnerlee** 2020-05-23 14:27 UTC
Labels: Need more info, cursor / selection, linux
