### ISSUE TITLE
Can not Open Image Location

### ISSUE THREAD

**Issue by adahbingee** [typora/typora-issues#3542] opened 2020-05-25 23:56 UTC
click menu text do nothing

windows 10

version 0.9.89(beta)

![image](https://user-images.githubusercontent.com/2985536/82848627-ff5bc780-9f26-11ea-92b3-9f3508a519bb.png)

**Comment by abnerlee** [comment] 2020-06-08 15:52
caused by https://github.com/electron/electron/issues/11617

**Comment by abnerlee** [comment] 2020-07-11 05:06
should be fixed in new release

**Closed by abnerlee** 2020-07-11 05:06 UTC
