### ISSUE TITLE
Sluggish responsiveness when typing on Windows 10

### ISSUE THREAD

**Issue by FSXAC** [typora/typora-issues#200] opened 2016-06-22 21:25 UTC
The characters do not appear instantly (or as smooth and as fast as other text editors). There are lag when typing any kind of stuff, this lag is even more noticeable when backspacing. 

I don't know if it's my Windows or my hardware, but it doesn't seem likely because Typora uses very minimum resources.

Windows 10 Education
Lenovo G50-80
Intel i7 5500U, 8GB

**Comment by abnerlee** [comment] 2016-06-23 03:55
Your hardware seems good. 

So, did it happens from the beginning, or only when you're editing large content of texts ?

**Comment by smallx** [comment] 2016-06-23 04:08
In my case, backspacing seems slowly too. Windows 8 64bit, Thinkpad E531, Intel i5 3320, 8GB.

> So, did it happens from the beginning, or only when you're editing large content of texts ?

Any time, any position, any file size.

**Comment by be5invis** [comment] 2016-07-08 21:41
@FSXAC Are you using the built in IME?
That one is broken, pick up some third-party.

**Comment by FSXAC** [comment] 2016-07-08 21:48
There is no issues writing in _Source Code Mode_. This makes sense because there is nothing "fancy" going on when writing in _Source Code Mode_ and I think it's something with Typora trying to update the style of the document since the lag becomes more severe the larger the document is.

**Comment by sahvot** [comment] 2016-07-25 03:20
Same for me. I like the app. Plz fix !

**Comment by abc612008** [comment] 2016-09-17 09:41
Same for me, no matter what IME I am using.
OS: Windows 10 v1607

**Comment by ahomu** [comment] 2016-09-18 02:38
I also often feel the lag, when typing.
Surface Book, Windows 10 Pro, Core i7, 16GB, MS IME (japanese)

**Comment by Windvast** [comment] 2017-03-02 16:39
Same problem. Especially when compare to Write!(official site: wri.tt), although I prefer Typora all the time.
Hardware: Windows10, 6600U, 16GB.

**Comment by Eaglezsx** [comment] 2017-09-09 10:12
when I am editing large content of texts ,for example 104KB,the software will become very slow.But I am very like typroa,so I put the large file into smaller files...I hope you can solve this problem,thank you!

**Comment by nascal3** [comment] 2017-09-30 00:55
Having the exact same issue, windows 10 on Lenovo G50-80, 8Gb RAM 1TB SSD Core i5. Mine seems to just lag at almost every activity from even moving windows around the desktop. It's a new clean installation. So it cant be caused by any third party software. Nothing is installed yet. please help.

**Comment by dwisp** [comment] 2017-10-08 16:58
I used to had it, but now the problem seems to disappear - I have updated my graphic drivers a lot lately, maybe that's the reason. Try updating your drivers.

**Comment by jesajash** [comment] 2018-02-06 09:51
I've just gotten it, it used to run really well, but the 0.9.42 update (I think) has made it extremely sluggish on my Surface Pro 4, with 8GB ram and i5. In *fancy* mode and *code* mode

**Comment by abnerlee** [comment] 2018-10-25 07:08
typing lag should be fixed in new release. For other performance issue, may refer #68

**Closed by abnerlee** 2018-10-25 07:08 UTC
Labels: bug
