### ISSUE TITLE
How to open local markdown files from file links?

### ISSUE THREAD

**Issue by ryerh** [typora/typora-issues#309] opened 2016-09-28 09:02 UTC
After a recent update, clicking a local file link from typora will redirect to Chrome.
Usually, it will open a new typora window to open this file, is this a Bug?
``` markdown
[another_file.md](./another_file.md)
```

**Comment by Brightcells** [comment] 2016-09-28 10:07
We can use old version such as [v0.9.9.5.1](https://www.typora.io/download/archive/typora_0.9.9.5.1.zip) before this bug fixed.

All usable old versions see [dev_release](https://www.typora.io/dev_release.html)

**Comment by pjeby** [comment] 2016-10-16 18:23
Here's a quick fix that worked for me with Typora 0.9.20 on Windows.  You will need to find the `Typora/resources/app/app/window/frame.js` file and change its permissions so that it's editable.  Then search for:
```js
a="http://"+a}
```
and replace it with:
```js
reqnode("electron").remote.shell.openItem(a); return}
```
Haven't tried this on OS X yet, but the same principle should apply there since `shell.openItem()` is a cross-platform Electron API.

**Comment by abnerlee** [comment] 2016-10-18 02:27
fixed in new version

**Closed by abnerlee** 2016-10-18 02:27 UTC
Labels: bug

**Comment by ryerh** [comment] 2016-10-21 10:04
@pjeby It has been fixed since the last update, life is still fine now~

**Comment by wookayin** [comment] 2016-11-24 09:16
@abnerlee Hi, I am using v0.9.9.8.4 and this bug looks happening to me, i.e. `./local-file.md` is opened in the browser, not in the Typora app. Is this a regression?

**Comment by ickerwx** [comment] 2018-01-04 20:00
This is happening for me as well. I am using `0.9.41 (beta)` and links to files on the local file system open in an external text editor.

**Comment by abnerlee** [comment] 2018-01-05 03:27
> links to files on the local file system open in an external text editor.

Are they also markdown files (with extensions of txt or md or markdown, etc) ?

**Comment by ickerwx** [comment] 2018-01-06 19:21
They are all links to markdown files.

I noticed earlier that I have a default handler for `text/plain` files. I haven't checked the source code, so I'm speculating here, but apparently typora let's the OS decide how to open links.

This is of course the reasonable thing to do, but maybe you could think about implementing an option to set that makes typora try to open links internally. Anyway, looks like my comment in this issue was a little hasty, sorry for the noise.

**Comment by abnerlee** [comment] 2018-01-07 04:00
Should be a bug, markdown files should be opened in typora when click links from typora, by default.

**Comment by ickerwx** [comment] 2018-01-07 18:30
Alright, what info can I collect for you to track this down?

**Comment by abnerlee** [comment] 2018-01-08 04:53
No extra info needed, I can reproduce it. We will fix this in next evrsion up

**Comment by EganSolo** [comment] 2020-05-15 05:38
There's still a bug in intra-files links. 
I've created a simple example that reproduces the bug and I've attached the two files below.
Basically, if I have a section in file f1.md called 'Header' and I reference that section from f2.md by writing [link](./f1.md#header), then ctrl-clicking on the link in f2 will open file f1.md but will not scroll to the section Header. 
Please see the attached files.
[intra_file_ref_bug.zip](https://github.com/typora/typora-issues/files/4632446/intra_file_ref_bug.zip)

**Comment by abnerlee** [comment] 2020-07-23 14:37
> then ctrl-clicking on the link in f2 will open file f1.md but will not scroll to the section Header.

This is another existing issue which you can find in our "issues" tab
