### ISSUE TITLE
local relative image source path different on Mac and Win Version

### ISSUE THREAD

**Issue by KypMon** [typora/typora-issues#2670] opened 2019-07-29 01:44 UTC
I am using the typora on both Mac and Win Os. I found a problem:
For example, on the Mac OS, I have a local image source like ```![eb-7](\image\db-4.png)``` which load correctly. But when I open the same file on Win Machine, I have to add a period `.` in front of the path like ```![eb-7](.\image\db-4.png)``` to make it work, could u guys please make it possible for Win OS version to read the local file without the period? Thanks

**Comment by abnerlee** [comment] 2019-07-29 13:35
I cannot reproduce this. `\image\db-4.png` is absolute path instead of relative path, so it should not be shown on both macOS and Windows.

So, what's your Typora version? possible to send us <hi@typora.io> the sample md file?

**Comment by KypMon** [comment] 2019-07-31 16:11
@abnerlee  Just send the sample file. I realized that I am using the '\' instead of '/' in the image path, it shows on Mac, but not Windows. My version is Version 0.9.9.25.3 (2897).
<img width="920" alt="Screen Shot 2019-07-31 at 11 59 34 AM" src="https://user-images.githubusercontent.com/20315868/62228070-0491c980-b38b-11e9-90a5-65715decfd53.png">

**Comment by truefalsename** [comment] 2019-08-01 05:07
Yes, that's expected:  MacOS and Windows use different slashes to indicate paths, one uses dir/dir2/dir3 and the other dir\dir2\dir3 . The same thing will happen also for hyperlinks and whatever else has a hard path coded.

**Comment by abnerlee** [comment] 2019-08-01 15:47
`\image\db-4.png` should not be shown as relative path on macOS

**Comment by abnerlee** [comment] 2019-08-03 15:02
should be fixed

**Closed by abnerlee** 2019-08-03 15:02 UTC
Labels: bug
