### ISSUE TITLE
Exported HTML does not include base.user.css

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#224] opened 2016-07-14 03:14 UTC
I made some CSS customizations using `base.user.css`. These were not included in the HTML export. The result is that the exported version does not look like the version displayed within Typora. 

I haven't tested it, but I presume `{current-theme}.user.css` is not included as well.

**Comment by abnerlee** [comment] 2016-07-24 17:07
Fixed in new verion

**Closed by abnerlee** 2016-07-24 17:07 UTC
Labels: bug

**Comment by vassudanagunta** [comment] 2016-07-24 17:33
Confirmed. Thanks!

**Comment by joeri-juramento** [comment] 2020-09-30 15:38
I would like report I am experiencing this problem again. 

Inspired by this issue, I manually pasted my base.user.css content in my typora-html-with-styles exported document to workaround it.

However, you may want to take another look at it.

The CSS I pasted created [auto-numbered headings](https://support.typora.io/Auto-Numbering/) in TOC and body (and typora overview window).

**Comment by abnerlee** [comment] 2020-10-14 16:21
@joeri-juramento what's your Typora/OS version?

**Comment by joeri-juramento** [comment] 2020-10-15 13:02
@abnerlee thanks for getting back to me and I should have mentioned the versions 15 days ago, sorry.

I am unable to reproduce the issue. Due to your question I re-tested again, but in the last 15 days I might have let choco and brew do their thing. I did stumpble upon Choco claiming I was on ~96 whereas the Typora GUI reported ~95, so I manually GUI-upgraded today.

So at the moment I am working with Typora-0.9.96/Windows and 0.9.9.35.2/Mac and the exports _do_ contain the extra CSS resulting in numbered headings.

My apologies, I really had to manually paste the css into the export 15 days ago, but for whatever state my typora app was in causing that, it seems to be in the past.

So the problem no longer exist.
