### ISSUE TITLE
It doesn't work on Windows

### ISSUE THREAD

**Issue by Amerone** [typora/typora-issues#1644] opened 2018-07-28 08:03 UTC
I've tried it many times, reboot it or reinstall it.The problem is still unresolved.I need your help!

**Comment by qhzxc0015** [comment] 2018-07-28 12:32
me too. My typora is open, but the editor is invisible, very strange. In window10.

**Comment by abnerlee** [comment] 2018-07-28 17:05
What's your Typora version? Did you use multiple screen?

Would remove C:\Users\{username}\AppData\Roaming\Typora\window-state work?

**Comment by Amerone** [comment] 2018-07-30 06:40
I installed 64 bits before, but now I can open it in 32 bits.

**Comment by imbadark** [comment] 2018-08-08 08:37
@abnerlee  Jesus , I met the same situation .... And trrrrrry a string of ways to solve it but no one did work..(include what u say)
My OS version is Win7 SP3( stable enough ).
Typora version is : 0.9.53 (latest?)
This situation is pretty strange , however I believe it can be re reproduced..
Because I found another same Editor-Apps , named [notion](https://www.notion.so/desktop) .
When typora stops work (reopen) , it stops too.  (Maybe notion and typora have some same lib?)
This has a conflict with what caused the last software to be unbootable.? 

And before u closed the typora process , it could still edit or create a new window. (Such as notion) , after close it,  WAHTEVER U DID, U CANNOT OPEN IT.....(just like the issue described)
And @abnerlee  thx a lot..... 32 bits did work..... I can finally open the typora on it....

Other potentially useful information is:
When I reinstalled typoa-win-x64-bit,It reminded me that the permissions are not enough.
ERROR message : CreateProcess error=740 ,  that's all..

**Closed** 2018-10-25 03:36 UTC
