### ISSUE TITLE
[BUG] Searching for Chinese characters doesn't work properly on macOS.

### ISSUE THREAD

**Issue by searene** [typora/typora-issues#2657] opened 2019-07-21 09:23 UTC
# Description
Searching for Chinese characters doesn't work properly on macOS, see the following reproduction steps for details.

# Steps to reproduce
1. Create a new file, and input `测试` as its contents.
2. Hit `Cmd + F` to start searching, then input `测试` in the search input box.
3. `测试` in the contents area should be highlighted as the search result now. But actually it's not. Nothing happens.
4. Only when I close the search input box and hit `Cmd + F` again can I see `测试` being highlighted.

# Version and OS
* Version: Version 0.9.9.25.3 (2897), `Check for Updates` in Typora tells me that I'm up-to-date.
* OS: macOS High Sierra

# Addition
This bug doesn't affect English characters.

**Comment by abnerlee** [comment] 2019-07-29 15:40
Cannot reproduce this. What's your IME? have try the default system IME?

**Comment by searene** [comment] 2019-07-29 16:26
> Cannot reproduce this. What's your IME? have try the default system IME?

That's odd, I'm always using the default system IME, that's not the reason.

**Comment by abnerlee** [comment] 2019-10-14 13:18
Close this since I cannot reproduce this. feel free to reopen it if it still exists in latest verison

**Closed by abnerlee** 2019-10-14 13:18 UTC
Labels: Need more info

**Comment by relaxbao** [comment] 2021-05-20 03:04
I  can't search the Chinese characters  in the folder  , but it can be searched  in the document
