### ISSUE TITLE
Typora's management/rendering of paragraphs isn't implemented correctly

### ISSUE THREAD

**Issue by KirkMunro** [typora/typora-issues#1210] opened 2018-01-31 19:50 UTC
Typora's handling of paragraphs that span multiple lines without wrapped text doesn't
seem right. When viewing the rendered view, paragraphs that span multiple lines
do not render as a contiguous paragraph -- instead they render as many individual lines;
yet, the rest of the document renders how it should, so this feels wrong.

You can see that by entering this markdown into a document in Typora:

```markdown
This is a paragraph that
spans multiple lines in raw
markdown but that should
render as a single paragraph
in the rendered view.
```

There are a few things I feel might make this a better experience for everyone:

1. When you render paragraphs that span multiple lines, render them properly (make
them appear as a single paragraph).
1. When you edit paragraphs in the rendered view in Typora, make the editor work like
it does for any other markdown editing, showing the paragraph the way it is laid out in
the markdown file, while still showing rendered items like bold/italics unless you are editing
those specific items).

This would ensure that people can get proper paragraph rendering, while being able
to write their markdown the way they want to, all from within the rendered view.

**Comment by vassudanagunta** [comment] 2018-01-31 20:43
Dupe of #364

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2018-02-01 02:42 UTC
