### ISSUE TITLE
Document with accents appearing twice

### ISSUE THREAD

**Issue by cisoun** [typora/typora-issues#3222] opened 2020-02-03 10:21 UTC
Hello,

As a french speaker, I happened to create a document with accents in the file name, like "Général.md".
I've noticed that when I save it the first time after Typora has been launched, it appears twice in the left panel. This situation exists from a long time but I didn't take a moment to report it until now.

Specs are: 
 - Mac OS Mojave 10.14.5
 - Typora 0.9.9.31.6 (4047)

Steps to reproduce the bug:
 - Create a new doc with accents in the name (use my example if needed).
 - The new document should appear twice in the left panel.

Thanks for your work !

**Comment by jgclark** [comment] 2020-02-06 18:13
Can't reproduce on macOS 10.15.3 on same version of Typora, using exactly your filename. Does it happen in other directories, and with different accented characters?

**Comment by cisoun** [comment] 2020-02-07 09:19
@jgclark Hello, yes. Anywhere, with any accent.

Some strange behaviours I've found:
 - If you create a folder with accents, you cannot fold it in the files panel. Unless you restart Typora.
 - Whenever I create a file with accents, it is shown twice in the panel, unless I restart Typora too. Saving it after doesn't make it appear twice but if I rename it, yes.
 - Activating the debug mode (I guess it is for the webkit view) doesn't seem to do anything and is not saved.

Also, I forgot to point out that it only occures in File Tree mode. Articles mode is okay.  
I don't have any particular message in the console either. 

Thanks for your help !

**Comment by abnerlee** [comment] 2020-03-28 15:46
Could you try latest version, and if still happens, could you share the "filename with accents" ?

may relates #3199

**Comment by abnerlee** [comment] 2020-03-28 16:02
Could you try latest version, and if still happens, could you share the "filename with accents" ?

**Comment by cisoun** [comment] 2020-03-31 11:00
Hello ! Version 0.9.9.32.1 I guess ? Still got this issue.
Here's a clip: https://drowned.ch/typora.mov

**Comment by abnerlee** [comment] 2020-05-24 14:00
should be fixed

**Closed by abnerlee** 2020-05-24 14:00 UTC
Labels: File Management, bug
