### ISSUE TITLE
Add a preference option to ignore single line-break

### ISSUE THREAD

**Issue by aleung** [typora/typora-issues#233] opened 2016-07-24 11:32 UTC
I'm switching from other markdown editor to typora. A major different between typora and others is that in typora a line-break is really a line-break, while in standard markdown spec single line-break is ignored.

Could you add a preference option to ignore single line-break to make it compatible with standard markdown spec?

In my opinion there are two reasons to do that:
1. Make it seamless for users to switch from other markdown editors. My existing markdown files contain a lot of single line-breaks.
2. I manage my markdown files in git. I usually write one sentence one line. It makes me easy to diff  and merge the changes -- a minor change in only one sentence can be isolated. While the single line-break is ignore it doesn't effect the render output.

**Comment by TSFoster** [comment] 2016-08-01 12:06
I came on here to create an issue regarding single line breaks and "Copy as Markdown", but I think this is the same issue, really.

I agree that single line breaks in Markdown should not be treated as line breaks, but I don't agree that it should even be a preference. Markdown already has a method for creating single line breaks, having two trailing spaces at the end of the previous line.

I think it would be great to switch to the "standard" Markdown approach for single line breaks. I appreciate it may cause breaking changes to some people's files, but that's what betas are all about!

P.S. Typora is exactly the Markdown editor I've always dreamed of having! Keep up the good work 👍

**Comment by bunnyhero** [comment] 2017-01-25 20:19
Agreed: in my mind, the existing behaviour is a **bug**.

**Comment by mruessler** [comment] 2017-06-06 21:08
I would also like to see this resolved. Issue #364 seems to be a duplicate of this one.

**Comment by vassudanagunta** [comment] 2017-06-08 09:11
Another reason we should resolve issue #369.

**Comment by vassudanagunta** [comment] 2018-02-20 20:41
@TSFoster: 

> I agree that single line breaks in Markdown should not be treated as line breaks, but I don't agree that it should even be a preference.

Supporting an option is entirely consistent with *both* the CommonMark and GFM specs, which say:

> A conforming parser may render a soft line break in HTML either as a line break or as a space.
>
> A renderer may also provide an option to render soft line breaks as hard line breaks.

I'm fine with the option. But *whatever* the setting, the text rendering within Typora should be exactly the same as how the HTML will be rendered. This is important because Typora is a WYSIWYG editor, and because it is popular precisely because it is a WYSIWYG editor, avoiding the need for separate edit and preview views that other editors employ.

The two options consistent with being a WYSIWYG editor are:

1. Only render the single line-breaks in source code mode
2. Only render the single line-breaks when the paragraph has focus (similar to how you do so for other things like bold/italics and links) and in source code mode.

Option 2 makes the most sense to me.

**Comment by vassudanagunta** [comment] 2018-03-09 00:51
@abner? See my comment above about labelling this issue.

**Comment by abnerlee** [comment] 2018-03-09 03:08
I would not consider this as `bug` or `markdown parse`, but adding a new option for users.

Typora understand this is a ignorable line-break after parsing the content, but we cannot know whether user want to see this (better for editing) or not (better for reading if they follow GFM).

And some markdown engines will even keep the line break, like this comment textarea I'm writing.

**Comment by vr8hub** [comment] 2018-03-30 18:53
It's a bug.

>… we cannot know whether user want to see this (better for editing) or not (better for reading if they follow GFM).

It doesn't matter what the user wants _in WYSIWYG mode_. (Source code mode is a different matter.) The Markdown spec is very clear — single line breaks are ignored. If a user wants something different, then they shouldn't be using Markdown. As everyone here has already said, by doing something different than the standard, you're breaking interoperability with other editors, *and* you're doing your users a disservice, because the end result (when copied to HTML, Pandoc, etc.) is not going to look like they see it on the screen.

(I empathize — the line break issue drove me crazy when I started using Markdown. But *I* had to adapt to the spec, not the other way around. That is the point of this issue — Typora should be adhering to the spec that it says it follows.)

**Comment by vassudanagunta** [comment] 2018-03-31 08:15
@vr8hub 

> The Markdown spec is very clear — single line breaks are ignored. If a user wants something different, then they shouldn't be using Markdown.

Not quite. See [above](https://github.com/typora/typora-issues/issues/233#issuecomment-367112244).

So we have two separate but related issues:

1. Should Typora "provide an option to render soft line breaks as hard line breaks"?  *My answer: Why not?*

2. Should Typora be WYSIWYG, rendering soft line breaks (aka single line breaks) identically on screen to it's HTML/PDF/RTF/Latex output, whatever choice for `#1` the user made? *My answer: YES! YES! YES! #1317*

**Comment by abnerlee** [comment] 2018-04-03 04:12
Option added from menu bar or from preferences panel in latest version

**Closed by abnerlee** 2018-04-03 04:12 UTC
Labels: enhancement, hybrid editing

**Comment by l0k18** [comment] 2022-04-27 03:42
It shouldn't default to WSIWYG view to break the single lines either. I use this to edit documents that display on Github, and I have a 1440p screen and the line breaks waste my screen space.
