### ISSUE TITLE
[Feature Requrest] allow resize images

### ISSUE THREAD

**Issue by wchoujaa** [typora/typora-issues#2714] opened 2019-08-09 02:47 UTC
Allowing the images to be resized along their diagonal by draging them. Its pretty handy when you dispose title and organize the general layout you want it to be fast.

**Comment by HighestQuality** [comment] 2019-08-09 05:29
Duplicate of #2189. Found in #2242.

**Comment by abnerlee** [comment] 2019-08-09 11:35
#2242

**Closed** 2019-08-09 11:35 UTC
