### ISSUE TITLE
Pasting rich text while inside backticks inserts newline

### ISSUE THREAD

**Issue by cmeeren** [typora/typora-issues#1551] opened 2018-06-10 18:29 UTC
Repro:

1. Write ` `` `
2. Place the cursor inside the backticks
3. Copy any text from a "rich text" source that is not Typora itself (I've tested with Firefox, Chrome, and Word). Make sure the text does not contain a line break (preferably also no formatting, just to keep things simple)
4. Paste into the backticks
5. Observe that a newline gets added

This does not happen when pasting text from Typora itself or from Notepad.

**Comment by abnerlee** [comment] 2018-07-06 05:52
There should be empty line between each paragraph (`<p>`). For line break, like `\n` or `<br/>` no empty line will be inserted.

**Closed by abnerlee** 2018-07-06 05:52 UTC

**Comment by cmeeren** [comment] 2018-07-06 09:02
It does not contain a newline (as per step 3), so this is a Typora issue. As long as you copy from a rich text source, even if you only copy a single character, a newline gets added in Typora, at least if you paste inside backticks. Try to follow the repro exactly as described and you'll see what I mean.

**Comment by abnerlee** [comment] 2018-07-18 15:50
@cmeeren 

Sorry, but I still cannot reproduce this. 
Could you provide an sample URL that I should paste from to reproduce this bug?
And what's your Typora/OS version?

**Comment by cmeeren** [comment] 2018-07-18 18:18
I am unable to reproduce now, so it seems this has been fixed since I reported it. :)
