### ISSUE TITLE
css float: now longer left-wraps/right-wraps text

### ISSUE THREAD

**Issue by baardev** [typora/typora-issues#5437] opened 2022-09-20 20:54 UTC
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized CSS.
    confirmed with all built-in themes

- [x] Searched http://support.typora.io/

----
An image that is in a <IMG> tag with the style "float:right", is right-justified, but if that image is on the first line of a paragraph, it appears ABOVE the text as opposed to left-wrapping around the image.  This is new with the latest version (1.4.4).  This bug does not appear when exporting to PDF.

To reproduce, create MD file:
`<img src='someimg.png' style='float:right;width:30%'/>test text test text test text test text test text test text test text test text test text test text test text test text test text test text test text test text test text test text test text test text test text test text test text test text `

Running on: Kernel: 5.19.9-1-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 12.2.0
    Desktop: KDE Plasma v: 5.25.5 Distro: Manjaro Linux base: Arch Linux

![Screenshot_20220918_192429](https://user-images.githubusercontent.com/1649016/190930475-28c2ac3d-ec41-40a7-a36b-baf2e30f3d15.png)

The same is true for right-wrapping text on left-floated images.
![float-left-bug](https://user-images.githubusercontent.com/1649016/191113512-5dc3774a-55b9-408b-a880-f02a93e6d8ad.png)

**Comment by baardev** [comment] 2022-09-25 05:24
There is an additional bug in the CSS formatting. Regardless of the width set in the style, the image is getting reduced to about 5%.

The image attached if from the following code:
`The quantitative values are the same in both equations, but the qualitative values are radically different.

<img src='../Images/tcurve.png' style='float:right;width:20%'/>In applying formula ***b)*** we begin with ***4&div;family-size*** for the first tholon, so we have ***4&div;1***, or simply ***4***.  The next value, with a *family-size* of 3, would then be ***4&div;3***, or ***1.333***, the next *family-size* of ***5*** is then `
![Screenshot_20220925_021921](https://user-images.githubusercontent.com/1649016/192129593-bff661ec-2958-4f97-be06-36aabf360bb4.png)

**Comment by abnerlee** [comment] 2022-09-25 14:58
> the image is getting reduced to about 5%.

There are now transparent border before and after images for editing purpose.

**Comment by tholonia** [comment] 2022-10-01 22:27
Can you elaborate on this a bit, please? It is unclear what transparent borders have to do with broken floats or image shrinkage. I also don't see any additional borders in images added with tags or with MD. How big are these borders? Can they be disabled in CSS? Is that what is breaking the float functionality? Does this mean that any docs with images that were made before this change will now be affected by this change? Are you saying that the float issue is not a bug?

**Comment by abnerlee** [comment] 2022-11-24 08:37
> It is unclear what transparent borders have to do with broken floats or image shrinkage.

It should not broken floats, we will fix the float issue. It is a very small border which would cause setting width of image not 100% accurate.

**Comment by abnerlee** [comment] 2023-02-14 04:48
fixed in v1.5.x

**Closed by abnerlee** 2023-02-14 04:48 UTC
Labels: images / resouces, fixed in dev
