### ISSUE TITLE
Menu invisible on Linux

### ISSUE THREAD

**Issue by fanxilsa** [typora/typora-issues#1923] opened 2018-10-31 08:17 UTC
OS: Ubuntu 18.10
Typora version: 0.9.60

Screenshot is attached below. EDIT: Actually, there is a faint outline of the words, but I'm not sure if this was intended.

![screenshot from 2018-10-30 18-12-55](https://user-images.githubusercontent.com/44587278/47701945-9db27900-dc6f-11e8-9c6c-df5ad640fd46.png)

_Originally posted by @fanxilsa in https://github.com/typora/typora-issues/issues/1915#issuecomment-434194502_

**Comment by abnerlee** [comment] 2018-10-31 13:45
caused by https://github.com/electron/electron/issues/15194

**Comment by Wangwj98** [comment] 2018-11-03 11:13
Totally same problem on Manjaro 18.01.
There is another bug; after you typed some words in a new opened typora window, the window cannot be closed and cannot be found in system monitor unless you save the file.

**Comment by wxk6b1203** [comment] 2018-12-04 03:42
I think you should update from upstream dependency. Thank you!
![default](https://user-images.githubusercontent.com/8924149/49417647-8ceaab00-f7b9-11e8-839c-d759221c1a8b.png)

**Comment by cabreraalex** [comment] 2018-12-07 02:58
I'm having the same issue on newest install of Typora

**Comment by vdegove** [comment] 2018-12-30 11:07
I confirm this in Ubuntu 18.04. I'm using the Ubuntu community-theme for my desktop.

**Comment by Wangwj98** [comment] 2018-12-31 06:42
Well, this issue has been open about 2 months.
The bug has actually been fixed by `electron group`, but not yet added to any stable release yet, at least not in the current newest release `electron  3.0.10-1`. 
see #15878.

**Comment by joshcangit** [comment] 2018-12-31 08:59
I wouldn't consider this a bug, more of a visual glitch. So this issue will be solved once the fix is available right?

**Comment by abnerlee** [comment] 2019-01-10 03:36
Should be fixed in new release

**Closed by abnerlee** 2019-01-10 03:36 UTC

**Comment by joshcangit** [comment] 2019-01-11 09:56
Yes, I can confirm that this is fixed.
![new typora](https://user-images.githubusercontent.com/33022160/51026742-278f9400-1587-11e9-91d0-e35a666737c3.png)
