### ISSUE TITLE
Can't Open Multiple instances via Typora.desktop and /bin/typora (Ubuntu 16.04.3 Xenial)

### ISSUE THREAD

**Issue by RiseAgainst9192** [typora/typora-issues#830] opened 2017-08-13 11:23 UTC
v0.9.32 (beta) Aug 13
**Issue:**
Unable to open **2nd instance** via 1) **GUI** (file browser) or 2)**CLI** (/bin/typora) to open a blank or an existing file.

**Not an issue:** 
I'm able to open 2nd instance through Typora's **file > new file** or **file > open recent**. **No problems** there, thankfully.

**My System:**
I've used Lubuntu and Xubuntu 16.04.3 Xenial. Both of them have the same issue

**BONUS**
THANK YOU FOR MAKING TYPORA :+1:  (Sorry, I figure this is a thankless job lol.). I love using this for school notes! Keep up the good work!!!

**Comment by shoesforindustry** [comment] 2017-08-14 08:46
Seems to be the same problem on OSX, open a file OK, double click on another file on the desktop to open it and beachball, requires force quit. 
OSX 10.12.16
Typora Version 0.9.9.10.2 (0.9.9.10.2)

**Comment by abnerlee** [comment] 2017-08-14 09:00
@shoesforindustry will open that file on the desktop via open file menu crash Typora?

**Comment by shoesforindustry** [comment] 2017-08-14 09:07
Sorry abnerlee, a red herring, a bad md file on my desktop, which of course I was opening as part of the double click. Apologies.

**Comment by abnerlee** [comment] 2017-08-14 14:47
Caused by https://github.com/electron/electron/issues/9880 https://github.com/electron/electron/issues/9576

**Comment by abnerlee** [comment] 2017-08-26 10:09
We downgrade Electron version for Linux.  
It is fixed in new version

**Closed by abnerlee** 2017-08-26 10:09 UTC
