### ISSUE TITLE
Auto pair even when unchecked in preferences

### ISSUE THREAD

**Issue by jordgoff** [typora/typora-issues#3752] opened 2020-07-31 18:19 UTC
I've unchecked "Auto pair brackets and quotes" in the preferences, but they keep auto pairing. I've tried setting the preference, quitting and restarting, but nothing seems to work.

**Comment by abnerlee** [comment] 2020-08-06 15:32
We cannot reproduce this.

What's your Typora version and what is your operation system?

And did you use any IME?

**Comment by jordgoff** [comment] 2020-08-06 18:12
I'm on Mac OS 10.15.6, using Typora Version 0.9.9.34.2 (4509). No IME. 

It happens in source mode, so this line is what I get when I type an unpaired single bracket or quote: ()""{}[]''

Thanks!

**Comment by abnerlee** [comment] 2020-08-30 03:50
should be fixed in new release

**Closed by abnerlee** 2020-08-30 03:50 UTC
Labels: hybrid editing, source code mode
