### ISSUE TITLE
Dark themes: document window flashes white when first opening

### ISSUE THREAD

**Issue by adesurirey** [typora/typora-issues#3776] opened 2020-08-11 11:49 UTC
`Typora Version 0.9.9.34.2`

On macOS, when opening Typora with a dark theme, the whole window flashes white for half a second.

<details>
 <summary>GIFs</summary>

Notes Dark
![notes-dark-startup](https://user-images.githubusercontent.com/22000544/90001291-8cdec600-dc91-11ea-8139-8fe32a9fc645.gif)

Ursine Umbra
![ursine-startup](https://user-images.githubusercontent.com/22000544/90001308-90724d00-dc91-11ea-89d8-b9d070cff2e0.gif)

</details>

This affects the following themes:
- Onedark
- Ursine Umbra
- Quartz Smoky
- Vue Dark
- Notes Dark

Only 2 themes I tested don't flash:
- Night
- Xydark

I tried to identify the problem without success so I thought I would reach out to you.

Any idea?

This issue was initially opened on the Notes Dark theme repository: https://github.com/adesurirey/typora-notes-dark-theme/issues/5

**Comment by xypnox** [comment] 2020-08-16 14:01
As I mentioned in the [issue on my theme](https://github.com/xypnox/xydark-typora/issues/2#issuecomment-674529729), the problem might not be specific to themes and may be in the Typora internals. 

I have tested my theme for white flashes, and sometimes they are there and sometimes they are not. I couldn't as of yet find any pattern in their occurrence.

**Comment by snooprat** [comment] 2020-11-06 13:41
I tried everything, finally I found the cause is file name. If I changed file name from "notes-dark.css" to "notesdark.css", then problem was solved.

**Comment by adesurirey** [comment] 2020-11-12 08:26
Is there any plan to fix this soon or should we change our theme names ?

**Comment by aCluelessDanny** [comment] 2020-11-12 17:04
Been messing around with it, and yeah, it's the filename in a peculiar way. If "dark" is present at any point in the filename _and there are no hyphens_, it doesn't make the white flash.
So for example:
- `ursine-umbra.css` - White flash
- `ursine-dark.css` - White flash
- `ursinedark.css` - **No flash**
- `darkursine.css` - **No flash**
- `urdarksine.css` - **No flash**
- `urdarksin-e.css` - White flash

Kinda funny how that works, haha. I think if there was a way to use a variable or two to set the theme name (not depending on the filename) and/or whether to flash white or not

**Comment by abnerlee** [comment] 2020-12-14 03:51
should be fixed

**Closed by abnerlee** 2020-12-14 03:51 UTC
Labels: UI / UX, bug, macOS

**Comment by adesurirey** [comment] 2020-12-14 09:30
It is, thank you @abnerlee

**Comment by neposedy-design** [comment] 2021-12-02 12:32
This is happening for me for all the default themes, and newly installed Notes Dark (notes-dark) theme. I tried to remove hyphen to no avail. Default themes are flashing too. V 1.0.2, macOS 12.0.1 (21A559). 
@abnerlee 

https://user-images.githubusercontent.com/70030433/144422543-efa688f7-6fd3-4e42-855a-eee75721f0d8.mov

**Comment by chriscubellis** [comment] 2021-12-13 20:43
This is happening for me in 1.0.4, on macOS 12.0.1
