### ISSUE TITLE
Html  Typesetting is abnormal

### ISSUE THREAD

**Issue by leov1** [typora/typora-issues#1529] opened 2018-05-30 03:42 UTC
I have tried to write the API  document by markdown. After I export to HTML or PDF files,  The HTML and PDF File it doesn't like the Typora display. 
There is about fifteen catalogue, the top five is normal, the below is looks weird.
![image](https://user-images.githubusercontent.com/7077687/40697793-8781042e-63fe-11e8-86e3-84612eae59a2.png)

**Comment by abnerlee** [comment] 2018-05-30 04:03
Which theme did you use? What's your Typora/OS version?

Could you send us (hi@typora) or attach the sample *.md file and exported *.html file?

**Comment by leov1** [comment] 2018-05-30 13:04
@abnerlee  Hi, I'm using the default theme & Typora version  is 0.9.9.16 (0.9.9.16) & My Os Version is 
10.11.6 (15G20015), The sample file, I'll send to hi@typora.

**Comment by abnerlee** [comment] 2018-05-30 13:49
It is caused by syntax like `<span id="detail_tobacco_order'>XXXXXXXXX</span>`

which should be `<span id="detail_tobacco_order">XXXXXXXXX</span>`

**Comment by leov1** [comment] 2018-06-01 07:28
@abnerlee  got it, thx.

**Comment by abnerlee** [comment] 2018-08-19 01:40
Fixed in new release

**Closed by abnerlee** 2018-08-19 01:40 UTC
Labels: bug
