### ISSUE TITLE
Character encoding issues with font-variant-ligatures

### ISSUE THREAD

**Issue by GiovanH** [typora/typora-issues#1871] opened 2018-10-15 23:23 UTC
System: Windows 10
Printer: HP LaserJet 1100 Series
Typora version 0.9.58

When I print certain combinations of characters from Typora to my printer, they are encoded incorrectly.
For instance, "ly" is printed as a y with a dialectic dot underneath, and "ff" is printed as a u with several scattered dialectic dots.

When there is an encoding error during printing, it is usually due to a misconfigured printer, so here are steps I took to troubleshoot the problem:
- Instead of printing to the printer, I printed to file
	- The PDF displayed the characters correctly
- I then printed the exported PDF
	- The PDF printed correctly.
- Instead of printing to file, I tried using the typora builtin "export" command
	- The PDF displayed and printed correctly.

I fear this might just be a technical issue on my end, but because the same document printed correctly outside of Typora, I'm thinking there's a problem with typora's printing, and I'm seeking help here.

**Comment by abnerlee** [comment] 2018-10-16 04:43
Would follow https://support.typora.io/Add-Custom-CSS/ and add following custom CSS help?

```css
p {
  font-variant-ligatures: none !important;
}
```

**Comment by GiovanH** [comment] 2018-10-16 04:48
> Would follow [support.typora.io/Add-Custom-CSS](https://support.typora.io/Add-Custom-CSS/) and add following custom CSS help?
> 
> ```css
> p {
>   font-variant-ligatures: none !important;
> }
> ```

This immediately solved the problem. Thank you!
That being said, while this is good for me, it does seem to indicate a bug in Typora. Obviously, this is unexpected behavior, but it's also inconsistent, as the exported file and the printed file should be the same. (i.e. if a user *wanted* font ligatures, they should get them in the exported file too.)

**Comment by GiovanH** [comment] 2018-10-16 04:51
What's especially strange about this is that I've used Typora religiously for years, but today is the first time I've ever seen this happen, and I can't think of any changes I've made to my system, nor did I notice Typora update.

**Comment by abnerlee** [comment] 2018-10-17 16:17
@GiovanH We'd like to prevent this in Typora. Could you share your System/Printer Locale? 

`font-variant-ligatures: none !important;` seems to stronger, how about

```
body {
font-variant-ligatures: no-historical-ligatures;
}
```

could this also solve your problem?

**Comment by GiovanH** [comment] 2018-10-17 17:39
```body {
font-variant-ligatures: no-historical-ligatures;
}```
does *not* work, but
```body {
	font-variant-ligatures: no-common-ligatures;
}```
does.

I'm not sure if there's a specific technical system locale you're interested in, but everything should be set to US English.

**Comment by abnerlee** [comment] 2018-10-25 03:12
Fixed in new release

**Closed by abnerlee** 2018-10-25 03:12 UTC

**Comment by GiovanH** [comment] 2018-10-25 17:00
Great! That being said, I'm curious: what was the issue?
Typora (tragically) isn't open-source, so I can't actually check.

**Comment by abnerlee** [comment] 2018-10-26 09:20
We didn't found the cause...

We added `font-variant-ligatures: no-common-ligatures;` when print. 
but ligatures is still enabled in Typora and PDF export.

**Comment by AhmedThahir** [comment] 2021-07-03 08:25
Is there a way to enable ligatures only for the code fences?

**Comment by AhmedThahir** [comment] 2021-07-04 07:46
update:
The behavior is very odd. In the code block, some work and some don't

![Screen Shot 2021-07-04 at 11 45 28 AM](https://user-images.githubusercontent.com/26618217/124377516-58b33000-dcbd-11eb-971e-b03525a60d26.png)
