### ISSUE TITLE
Clicking end of doc in typewriter mode scrolls to top

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#576] opened 2017-03-05 02:14 UTC
Since you still can't scroll past end of document, I tried using typewriter mode as an alternative, but one thing that drove me crazy was how clicking somewhere past the end of a document would place you back at the top. Repro GIF attached.

The longer my file became, the more annoying this was. Since you can't tell where the doc ends, if you have some blank lines at the end still, and want to click those, going back to the top is not what you're expecting. I hope this is not by design, but if so, there should be a setting to turn it off.

![2017-03-04 21 11 26](https://cloud.githubusercontent.com/assets/1819485/23583904/3e417c5a-011f-11e7-99da-0c6ba3139bde.gif)

**Comment by AlexPasternak** [comment] 2017-06-20 14:28
Any update on this one, @abnerlee? It really drives me crazy. You're typically adding content near the end of the doc, and having it jump you to the top accidentally is very disruptive. Hopefully you've been able to reproduce it?

**Comment by abnerlee** [comment] 2017-06-21 16:55
@AlexPasternak 
Hi, I can reproduce this if I click-hold-release my mouse. But for normal click operation (click quickly), seems I cannot reproduce it. But anyway, we will fix the previous case in next version up.

**Comment by AlexPasternak** [comment] 2017-06-21 18:06
I can reproduce this easily with regular click, let me try listing repro steps one more time.

1) Use Typora latest, Version 0.9.9.9.4.2 (0.9.9.9.4.2)
2) Start new doc
3) Generate large blob of text, e.g., 5 paragraphs with http://hipsum.co
4) Paste text into doc
5) Click into middle of one of paragraphs and turn on Typewriter mode
6) Scroll to the bottom of doc, and click on empty space past the end of last line ("I bet you’re still using Bootstrap too…" if from Hipsum)
7) You're jumped back to the top of the doc

HTH.

**Comment by abnerlee** [comment] 2017-06-22 01:47
@AlexPasternak Have you ever modified the theme css or add custom css ?

**Comment by AlexPasternak** [comment] 2017-06-22 02:23
@abnerlee, nope, never. Have never seen the need. I do typically use the dark theme, as per screenshot above.

**Comment by abnerlee** [comment] 2017-08-12 03:44
This should be fixed in the latest version

**Comment by AlexPasternak** [comment] 2017-08-12 19:52
Well it seems better at any rate. Double-clicking past the end still jumps to the top, but then jumps back (see report where I double-click on empty space past end of doc). At least you end up in the right place usually. In some cases, the first word in the doc ends up highlighted and selected, but most of the time it's improved.

![2017-08-12 15 49 52](https://user-images.githubusercontent.com/1819485/29243800-24506952-7f76-11e7-8a8b-ca8719292513.gif)

**Comment by abnerlee** [comment] 2018-08-19 03:59
Tested in new release. Seems OK now

**Closed by abnerlee** 2018-08-19 03:59 UTC
Labels: bug
