### ISSUE TITLE
Comment markers do not work when typed, only when added via Format menu

### ISSUE THREAD

**Issue by taylorbf** [typora/typora-issues#413] opened 2016-11-12 15:41 UTC
Loving Typora, thank you for this work!

I notice that if I type a comment, it is not translated into markdown:

&lt;!-- this is my comment  --&gt;

But I can add comments via the Format menu, which do translate into markdown.

This may be intentional. Is there a reason?

To be consistent with the idea of markdown and being able to format text using inline code, I would like to see this changed so that I can type a comment marker and have it register as a markdown comment.

**Comment by abnerlee** [comment] 2017-02-24 14:47
should be caused by "--" being replace with em-dash by macOS's "smart dash" feature.

We will consider some improvement to avoid such issue in future updates.

**Comment by abnerlee** [comment] 2017-07-03 16:23
can be fixed by https://github.com/typora/typora-issues/issues/291 related

**Closed by abnerlee** 2017-07-03 16:23 UTC
Labels: enhancement
