### ISSUE TITLE
When opening a file with BOM, Typora does not recognize YAML header

### ISSUE THREAD

**Issue by getreu** [typora/typora-issues#3348] opened 2020-03-10 16:38 UTC
When opening a file with BOM (byte order mark), Typora does not recognize YAML header any more. Please add BOM support.

**Comment by abnerlee** [comment] 2020-03-27 16:19
Which OS?

**Comment by abnerlee** [comment] 2020-03-27 16:19
#1337

**Comment by getreu** [comment] 2020-03-27 17:11
Sorry, #1337 has nothing to do with it:

Some Unicode editors write a BOM by default: The byte order mark (BOM) is a particular usage of the special Unicode character, U+FEFF BYTE ORDER MARK, as a magic number at the start of a text stream.  The fact that the text stream's encoding is Unicode, to a high level of confidence;

Even if Typora does not write a BOM, its presence should not lead to reading errors: When a 
text comes with a BOM, typora does not recognize the front matter any more!

**Comment by abnerlee** [comment] 2020-03-28 07:12
#1337 is about encoding:

- UTF8 (with BOM)
- UTF8 (without BOM)
- ...

**Comment by getreu** [comment] 2020-03-28 16:23
Last try to make myself understood:

1) Typora saves and reads UTF-8 encoded Unicode text files.
2) It is common practice that Unicode text-files start with a BOM.
3) Typora's files do not, which is not a problem (although it would be better).
4) Typora does not correctly open text-files with BOM: When there is a BOM, the YAML front matter is parsed any more.

My point is no. 4): in order to be compatible with other Unicode editors, Typora should interpret
the byte order mark (BOM) correctly.

I hope you got my point (even if you don't care about compatibility).

**Comment by abnerlee** [comment] 2020-03-29 08:12
What's your OS? I tried a file using UTF8 with BOM, but I cannot reproduce this. 

Possible to attach or send us <hi@typora.io> the sample file ?

**Comment by getreu** [comment] 2020-03-29 16:38
Linux. Steps to reproduce: 

1. Create a MD text file, e.g.:

   ```
   ---                                                                              
   title: test                                                                      
   --- 

   body
   ```

   which is in hex:

   ```
   2D 2D 2D 0A │ 74 69 74 6C │ 65 3A 20 74 │ 65 73 74 0A │ 2D 2D 2D 0A │ 0A 62 6F 64 │ 79 0A
   ```

2. Add a byte order mark (for example in vi with `:set bomb`)

    ```
   EF BB BF 2D │ 2D 2D 0A 74 │ 69 74 6C 65 │ 3A 20 74 65 │ 73 74 0A 2D │ 2D 2D 0A 0A │ 62 6F 64 79 │ 0A
   ```

3. Open the file again in Typora

   You can see that the first `---` from the YAML header are misinterpreted as horizontal line.

**Comment by getreu** [comment] 2020-03-29 16:44
I just sent you the file by Email with*
When opening a file with BOM, Typora does not recognize YAML header
#3348* as subject.

BTW: my compliments for this very nice editor with excellent ergonomics!

**Comment by abnerlee** [comment] 2020-05-23 16:05
should be fixed

**Closed by abnerlee** 2020-05-23 16:05 UTC
Labels: bug, linux, windows

**Comment by getreu** [comment] 2020-05-27 19:57
I tested 0.9.89 and I can confirm the bugfix works. Thank you.
