### ISSUE TITLE
#Bug copy as html code not works when the content has mathjax formulation.

### ISSUE THREAD

**Issue by FindHao** [typora/typora-issues#524] opened 2017-02-04 08:30 UTC
When I write the formulations with mathjax, I can't get the html code from edit-->copy as html code.

**Comment by abnerlee** [comment] 2017-07-03 15:18
Cannot reproduce this, seems fixed now

**Comment by FindHao** [comment] 2017-07-27 05:47
for example:
$f = a + b $ 
When I export it to a html file, it's ok and there are a lot of css styles and it's a svg.
But when I use edit->copy as html code , I got just 
```html
<p>$f=a+b$</p>
```

**Comment by FindHao** [comment] 2017-07-28 07:20
> I see, since copy as HTML is to copy HTML code without css styles. I need to decide whether is should be copied as <p>$f=a+b$</p> or put the complicated svg code..

I think the css style is used to change the font, color and format, but not for the formulation. So it's to put the svg code. And when generate the html code, maybe you can do some judgement of the tag whether it is formulations?
:thinking:

**Comment by abnerlee** [comment] 2019-10-13 17:41
added option about whether svg or latex will be copied in new version.

Closing this now

**Closed by abnerlee** 2019-10-13 17:41 UTC
Labels: bug
