### ISSUE TITLE
Windows start menu shortcut installed under weird folder

### ISSUE THREAD

**Issue by rotu** [typora/typora-issues#3730] opened 2020-07-23 16:34 UTC
When installing Typora on Windows, it creates a start menu item in a folder called "(Default)". It should either not be in a folder or its folder should have a descriptive name.

![image](https://user-images.githubusercontent.com/119948/88313197-c8145780-ccd8-11ea-8bc3-5d51dcb5c78d.png)

**Comment by abnerlee** [comment] 2020-08-01 09:46
My behavior is same with #3536, so I'm not able to reproduce this.

Is it Windows 10? and did you use 64bit or 32bit installer? and is the installer loaded from typora homepage, or did you see this after upgrade from an older Typora version?

**Comment by rotu** [comment] 2020-08-01 17:40
I'm using Windows 10, on one of the insider preview builds.
I installed via Chocolatey pretty recently, and Typora has updated itself since.

**Comment by rotu** [comment] 2020-08-01 19:03
I just confirmed after uninstalling and reinstalling via Chocolatey, the (Default) start menu folder gets recreated.
The version installed via chocolatey is somewhat older 'https://typora.io/windows/typora-update-x64-0525.exe'.
When Typora self-updates, it does *not* move or re-create a new Start menu shortcut.

The 32-bit and 64-bit 9.93 installers, do indeed create a start menu shortcut in a Typora folder.

**Comment by abnerlee** [comment] 2021-12-11 09:11
We now keeps the setup.exe from v1.0, this should be fixed

**Closed** 2021-12-16 15:55 UTC
Labels: Need more info
