### ISSUE TITLE
Gothic theme cost a lot of system resources

### ISSUE THREAD

**Issue by livc** [typora/typora-issues#1131] opened 2017-12-29 12:58 UTC
Gothic theme macos Version 0.9.9.11.2 (0.9.9.11.2)
<img width="519" alt="screen shot" src="https://user-images.githubusercontent.com/11692045/34437641-fe8b12ee-ecda-11e7-90be-75e974a96713.png">
<img width="602" alt="screen shot 1" src="https://user-images.githubusercontent.com/11692045/34437642-fec48074-ecda-11e7-860c-f11b19133550.png">

**Comment by abnerlee** [comment] 2017-12-30 03:29
Caused by css calculation/rendering, (maybe a webkit bug?)

Fot hot fix, create a gothic.user.css and write:

```css
.mac-seamless-mode #typora-sidebar {
	height: auto;
}
```

**Comment by abnerlee** [comment] 2018-01-26 08:15
fixed in new release

**Closed by abnerlee** 2018-01-26 08:15 UTC
Labels: bug
