### ISSUE TITLE
Jumplist doesn't list documents on Windows any more  :(

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#2588] opened 2019-06-21 20:08 UTC
Recently (0.9.70 and up), Typora's jumplist on Windows changed to only list folders, not files.  Can we have files back?

(The reason the folders in the jumplist aren't very useful to me is that the "takes several minutes to save a file if you ever use the file view" bug is still in effect.  Also, the folder jump list doesn't get updated by opening files from the command line, so it doesn't even include everything to start with.)

**Comment by abnerlee** [comment] 2019-06-22 02:14
Do you have recent files from "File" -> "Open Recent" menu?

**Comment by pjeby** [comment] 2019-06-22 03:32
The jump list had only 5 folders in it; removing one had no effect.  I used to have 16 files before, no folders, and I had pinned items as well.  Dragging a file to the icon offers to "Pin to Typora", but has no effect.  The File->Open Recent menu currently lists 11 files and 8 folders.

**Comment by abnerlee** [comment] 2019-06-30 15:44
What's the setting in 
![image](https://user-images.githubusercontent.com/1621242/60398982-fafd2200-9b90-11e9-9134-2a4975e5c4f7.png)

And how about right click on Typora from "Start" menu?

**Comment by pjeby** [comment] 2019-06-30 16:18
I'm on Windows 7, not 10, but "Store and display recently opened items in the Start menu and the taskbar" is definitely checked.

**Comment by pjeby** [comment] 2019-06-30 16:19
(Oh, and right clicking Typora in the start menu just brings up a normal explorer right-click menu.)

**Comment by abnerlee** [comment] 2019-07-01 03:58
There are similar also settings on Windows 7, maybe follow https://www.groovypost.com/howto/geek-stuff/disable-clear-windows-7-jump-list-recent-history/

**Comment by pjeby** [comment] 2019-07-01 04:32
As I said above, the relevant box is indeed checked.  I have not changed any Windows settings between when this was working and when this was not; the only thing that changed is upgrading Typora (by doing a fresh install of a newer version).  Other applications such as Word have retained their jump and pin lists, but it is now impossible to pin any documents to the Typora icon.

**Comment by pjeby** [comment] 2019-08-15 02:55
FYI, this started working again at some point, just as mysteriously as it stopped.

**Comment by abnerlee** [comment] 2019-08-17 04:00
I'm also not able to reproduce it on Windows 7. Close this for now

**Closed by abnerlee** 2019-08-17 04:00 UTC
