### ISSUE TITLE
Image - Reveal in Finder opens Recent Folder but not Folder with image

### ISSUE THREAD

**Issue by Acidham** [typora/typora-issues#2334] opened 2019-03-26 14:59 UTC
Typora 0.9.9.23.4 
macOS: 10.14.4

Right click on an image stored in assets folder, choose reveal in finder opens Recent Folder in Finder but not the assets folder.

**Comment by abnerlee** [comment] 2019-04-16 15:33
Could you provide a sample of your image path?

Currently we cannot reproduce this.

**Comment by Acidham** [comment] 2019-04-16 15:40
`![download](Tableau%20Headcount%20Dashboard%20Change%20Requests.assets/download.png)`

**Comment by abnerlee** [comment] 2019-04-19 13:48
should be fixed in new release, please reopen if it still happen

**Closed by abnerlee** 2019-04-19 13:48 UTC
Labels: bug
