### ISSUE TITLE
Deleting an empty paragraph deletes first char of next line as well

### ISSUE THREAD

**Issue by benutzerfreund** [typora/typora-issues#834] opened 2017-08-14 15:42 UTC
When the cursor is in an empty paragraph, hitting delete (not backspace) deletes the return, but also the first character of the next line.
To make things worse, when I choose undo, only the return reappears, but not the deleted char of the next line.
I think this is an issue introduced in 0.9.9.10.2.

**Comment by abnerlee** [comment] 2017-08-26 10:06
Should be fixed in newest version

**Comment by benutzerfreund** [comment] 2017-08-28 16:11
Hm. Sorry to say: on Mac OS 10.12.6 and Typora 0.9.9.10.6 the bug still appears as before.

**Comment by abnerlee** [comment] 2017-08-29 02:29
Did you trigger Delete key by `fn`+`Backspace`? I still unable to reproduce this

**Comment by benutzerfreund** [comment] 2017-08-29 06:03
I just use regular Delete key on a standard extended keyboard. Pressing it once when the cursor is in an empty paragraph deletes the paragraph *and* the 1st char of the next line. See it in action here:

http://www.benutzerfreun.de/staging/Typora.mp4

Hope this helps!

**Comment by abnerlee** [comment] 2017-10-30 06:52
should be fixed in new release

**Closed by abnerlee** 2017-10-30 06:52 UTC
Labels: bug
