### ISSUE TITLE
Link opens in typora window

### ISSUE THREAD

**Issue by rahvee** [typora/typora-issues#675] opened 2017-05-02 20:16 UTC
I keep typora open with a few windows open, and documents loaded. Some of those documents include hyperlinks to webpages, and sometimes (seemingly random) when I Command-Click the URL to open in a browser, the URL opens in the typora window, as if typora were a web browser.

I have not been able to reproduce this issue, nor have I been able to capture a debug, because it seems to happen rarely and seemingly randomly. It probably happens to me once every few days (during which time, I probably click a hundred links, 99 of which work and 1 fails).

Typora 0.9.9.9.4.2 on Mac OSX 10.12.4

**Comment by rahvee** [comment] 2017-05-04 17:06
I was able to capture this in Debugging one time. Where is the log file, so I can upload it? 

I have a feature request: Whenever someone toggles on/off Debugging, tell them where the log file is.

**Comment by abnerlee** [comment] 2017-05-08 14:31
The log message is on Console.app, but may not be detailed enough to debug this issue.

If that happens again, could you enable debug mode, then click "Inspect Element" in context menu, and copy/paste/send the log in the console panel to us (<hi@typora>)? Thanks

**Comment by abnerlee** [comment] 2017-08-11 16:03
I will close this issue since I cannot reproduce it.

Please reopen it if you met this bug again

**Closed by abnerlee** 2017-08-11 16:03 UTC
Labels: bug
