### ISSUE TITLE
Cursor disappears after save; reverts to top after task switch

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#865] opened 2017-08-29 23:34 UTC
In 0.9.36 on Windows, do the following:

* Open a document for editing, go to some point in the middle.
* Type some text, leaving the cursor on that line
* Save the file

After a short delay, the cursor disappears.  You have to click to get focus back to where you were.  Alternately, if you switch away to another window (e.g. because the save is to a slow network drive), then switch back, the cursor will be at the top of the document instead of where you left it.

(Also, if it's a slow save and you switch during the save, Typora brings itself back to the front even if you were typing in some other app...  but without the cursor focused anywhere.)

**Comment by abnerlee** [comment] 2017-09-03 04:09
@pjeby I tested on Windows 10, but I cannot reproduce this bug when I try to save this file on my local disk. I can only reproduce this bug if the file is on a network drive.

So, could you confirm if this bug only occurs when the file is located in your network drive, or it occurs anywhere?

**Comment by pjeby** [comment] 2017-09-03 06:36
Now that I'm *trying*, I can't get it to happen at all, possibly because my network is fast at this hour.  So I can't really *confirm* that it's network-drive specific, but it seems plausible to me.

**Comment by pjeby** [comment] 2017-09-20 04:55
Ok, I've got some more information about what's going on...  it does indeed have to do with network drives.

Here's the thing: apparently sometimes on a network drive, Typora interprets *its own save of the file* as meaning another program changed the file on disk.  I don't know how Typora is monitoring or detecting that, but it's getting false positives for a change sometimes.

When it does, there are two possibilities: either I've typed something since the save or I haven't.  If I *have* typed something, then I get popups -- **three** of them, one after another -- asking if I want to reload, which is really annoying because I'm *in the middle of typing* and chances are I've already typed a space or am about to...  which promptly reloads the file, erases what I was typing, and resets my scroll position to the top of the file.

This was happening enough times lately for me to realize that it *also* happens when I *haven't* typed anything since the save.  It's just that there's no popup, it just automatically reloads, causing the loss of cursor position and the Typora window returning to the foreground.

So there are multiple problems here: 

First, the dialog box is kind of broken.  A spacebar or really anything you might be typing (especially typeahead) should not trigger the dialog box to go ahead with something you might not want.  ;)

Second, the "other program changed it" detection is getting false positives.  My *guess* is that it might be related to the fact that some Windows libraries may have problems with timestamp resolution when interacting with remote files, OR it could be the required retry on overlapping opens of a file.  Or it might be in one of the other hairy things that can go wrong with Windows networking.  :)

For the sake of testing, I've changed some Samba settings related to timestamps on the share I'm mostly using, so that I can get an idea of whether it affects the frequency of the issue occurring.  If the issue doesn't come back, then it's probably the two-second resolution problem, where a Windows app uses an API that rounds the timestamp to the nearest 2 seconds, in such a way that half the time the file will look changed even if it wasn't.

Third, the handling of automatic reload is unpleasant.  Even if you have to reload, it doesn't seem like the cursor should jump to the top.  Maybe it could just compare the file contents and apply the changes as if you were editing?  Or just use the comparison to figure out roughly where the cursor should be post-reload? Maybe just by comparing the file versions, character for character, placing the cursor at the first-detected change (unless it's past the current cursor position), and scrolling so the cursor is visible if that position's off-screen?

(Just some ideas, though obviously this is a harder thing to fix than either of the other two issues, and is a lot less important if the change detection is fixed.)

For that matter, it might be helpful to *always* have the reload request dialog appear, *even when nothing has changed*.  That way, the cursor would not inexplicably jump!

Oh, speaking of inexplicability, one other thing that happens as a result of the automatic reload is that focus switches to Typora even though it was in the background when the false "change" was detected.  This is incredibly annoying in and of itself, because it often results in me making changes to the file because I was typing in another window at the time focus changed!  Typora should definitely not grab focus just because it's detected a change.

So, to summarize:

* Typora should detect file changes correctly, or at least with fewer false positives on network drives
* When Typora detects a change, it should *always* ask before reloading the file, never doing it without consent (unless you've enabled some option, perhaps?  I could see some people maybe finding it desirable, e.g. to use Typora as a previewer for some other editor, or to do collaborative editing with someone else)
* Typora should *never* grab focus from another window, not even to ask about a reload, and definitely not for an automatic reload, *even if there's an option to automatically reload and it's enabled* -- if you want to watch a file change as it's being changed elsewhere, then you can just drag the window somewhere visible and watch it update without it having to be the focus window.
* When Typora displays a dialog asking to do something data-altering (like reloading a file), it should ideally not grab the focus then, either.  Instead, it should show a status bar or something else that requires an explicit use action to change the focus, allowing them to be notified but not randomly redirecting their keystrokes to take unintended actions.  If this approach isn't feasible, then the dialog should at least be designed so that random typing (esp. space and enter) does not cause the data-altering action to be taken, just because you're a fast typist.  :)
* Finally, it would be nice if file reloads kept the cursor and scroll position in as close to the same place as possible.  But if the preceding issues are addressed, this is a relatively minor issue.

Thank you again for a wonderful program, I use it every day for nearly everything I write!

**Comment by abnerlee** [comment] 2017-09-20 06:52
Hi thanks for the detailed feedback.

> Typora should detect file changes correctly, or at least with fewer false positives on network drives

Yes, this is our bug, we will fix this.

> When Typora detects a change, it should always ask before reloading the file, never doing it without consent

Currently, when you have unsaved changes, the dialog will show, or else the content will be reloaded automatically. The reason it bothers you is because a.) there's a bug about file change detection. b.) the cursor/scroll position will lost after reload. So we will do those fix, then consider whether the dialog is always needed or not.

**Comment by pjeby** [comment] 2017-09-20 13:33
Thanks.  Hopefully you can also do something about the focus-grabbbing, which honestly is the worst part of the entire issue.  An editor shouldn't be grabbing the focus from other apps, and it definitely shouldn't grab the focus from *itself*, i.e., when you're typing.  :)

Honestly, if *none* of the other problems were fixed, but Typora just stopped switching itself to the front or displaying dialogs asynchronously, that would make me quite happy.  It's far less of a bother to come back to a badly-reloaded window than it is to end up typing in the wrong document.

I've been using Typora quite extensively recently as a programming editor, writing code embedded in markdown documents and then using [a tool I wrote to make them executable](https://github.com/bashup/mdsh).  I also use it to write tests using [cram](https://bitheap.org/cram/), for which it also works fairly well.

The only major frustration I've run into with Typora besides the change detection is it adding or changing invisible characters, like forcibly joining two code blocks that are space-indented, or inserting zero-width-space characters in front of triple backquotes when they're inside a code block delimited in another way.  I've just about given up on using Typora to edit cram test files because of the constant changing of my invisible characters.

For most of my projects it probably wouldn't be a big deal, but since I'm currently writing tests and documentation that describe *markdown documents*, Typora inserts a lot of zero-width-spaces that break my tests and force me to hunt them down regularly to remove them.  The only reason I haven't already written an automatic tool to remove them is that I fear it would get into a "save war" with Typora, as Typora automatically puts the characters *back*...  and then auto-saves the file, causing the tool to take them out and save, causing Typora to reload again...

I bring all this up because it's another case explaining why I feel  "unconfirmed automatic reload shouldn't happen", and it's also another example of Typora doing things "behind my back".  So if there's going to be automatic reload, please tell me it won't create an endless war of saving with my other tools.  :)

**Comment by pjeby** [comment] 2017-09-20 16:55
More information: the problem is not fixed by changing samba's `dos filetime resolution` setting: whether it's `yes` or `no`, the problem occurs.

This suggests that the problem is that Typora is listening for filesystem change events *without* checking the file mtime and comparing it to a cached value.  With the network latency, it's likely that the change event is received late enough that Typora thinks it is another application.  This could probably be resolved by:

* disabling change notifications during the saving process
* capturing the `mtime` of the file immediately after saving AND when canceling the reload (this would help fix the multiple-popups problem), and
* ignoring change notifications where the `mtime` is the same as the value captured by loading, saving or canceling a reload

(This is all speculation of course since I don't have the source code.)

**Comment by pjeby** [comment] 2017-09-20 16:59
Oh, forgot to mention: the reason I'm now assuming that it's a filesystem event notification issue is that if I *restart samba while a file is open* in Typora, the problem ceases to happen: all subsequent saves of the file do not cause a reload attempt.  (That is, until I start Typora again with that file.  Then the problem immediately returns.)

This suggests that restarting samba is canceling an active event subscription.  (Again, you would know better than I would how it's actually implemented.)

**Comment by pjeby** [comment] 2017-09-20 17:55
Further confirmation: the problem happens if the client machine has a clock setting that is about two seconds behind the server.  If the client clock matches or is ahead of the server, the problem doesn't occur, indicating that the issue is Typora using the client clock as a basis for comparison instead of using the actual mtime off the disk.  Typora should capture the file's mtime for comparisons, rather than whatever value is on the system clock.

Ironically, the algorithm Typora is currently using will miss also changes that set the mtime of a file backwards, as when another program on another machine explicitly sets an mtime based on *its* system clock.  Changing it to use the actual mtime will fix that problem as well, and the 2 second window can probably be eliminated, since the actual value of the mtime should not change between checks, even if it is a low-resolution value.

**Comment by abnerlee** [comment] 2017-09-25 04:49
jumping around when save in a net drive should be fixed in the new release

**Comment by pjeby** [comment] 2017-09-27 05:56
Huge improvements: excessive reloading is fixed.  Scrolling to a different position is fixed.

Still a (minor) problem: cursor position still resets to the top.

New problem: changing the file multiple times in another program makes Typora flicker as if reloading, *but the text is not actually updated to match the current file contents*.

It looks like Typora is *still* using the local system clock in some way, because it will not recognize changes made outside of Typora until the file date is in the past from the local clock perspective.

Steps to reproduce:

* Edit a file in Typora on a network drive of a system that is slightly out of clock sync from the current machine (e.g. server has a time that is 10 or 15 seconds *later* than the local machine)
* Save the file in Typora
* Open in another editor on the server, make a change, save -- Typora will refresh and update to match file contents
* Make another change on the server and save -- Typora flickers but does not actually update
* Optionally repeat multiple times -- Typora still does not update
* Wait until local clock catches up to the modification time of the file, then save again on the server -- Typora now updates to match file contents

I'm not sure what the new logic is for determining the refresh, but it seems like it is still using the local machine's clock as part of the algorithm somewhere.  There's probably some place where you're either saving a `Date` object or comparing an mtime to one, when it needs to be stat mtimes *everywhere*.

**Comment by abnerlee** [comment] 2017-09-27 07:01
We do not use mtime, but compare detected changed time to last save/refresh time. We are using node.js but we didn't find a proper to way detect changes performed by other app.

We will try to reproduce this anyway, and then find the solution

**Comment by pjeby** [comment] 2017-09-27 14:53
That's my point: if you're using "time" in general rather than looking at file modification times exclusively, you will definitely have problems like this one, because the system clock can be raced in one fashion or another.

If you're not using mtime, then the clock skew between machines isn't the problem.  I will try resyncing the clocks and see if it's really just a fixed window aka "saves within N seconds of each other" problem.

**Comment by pjeby** [comment] 2017-09-27 16:08
Ok, confirmed it's not clock skew.  It's ignoring changes if the file is changed within 15 seconds of the last time it was changed.  The screen still flickers, but the content doesn't update.  Each time you change the file externally, the 15 second window resets, keeping it from loading any changes.

But, this only happens on a network drive, and only if the file was changed *on the other machine*.  That is, if you open another program on the same machine accessing the network drive, it's fine.  But if you run the other program on the other machine and change the file, the change is detected but the old file is loaded.

What's really weird is that under some circumstances, the content changes on the screen *up to the length that was previously loaded*.  That is, if you add text to the end of the file, then go back and edit something Typora had previously displayed, then it will update that but not the text added at the end.  It's almost like 

Anyway, so far I can only reproduce this by editing the file on a non-Windows machine sharing with a Windows machine.  Both machines so far I've tested this on were Linux samba shares, but different devices with different configuration.  (One was a NAS, the other was a server I set up.)  I haven't tried this on a Mac yet.

More detailed investigation reveals that the issue appears to be that Windows doesn't immediately update the directory information for the file (modification time and size) when it's working with these Samba shares.  So sometimes Typora detects a change and loads a shorter version of the file because Windows thinks the file is shorter than it is, or else loads the file and sees old content because Windows isn't updating its cached content.

At this point, I think we can safely say this is no longer Typora's problem.  I found this [StackOverflow discussion about it](https://serverfault.com/a/625035/158840), and changing the Samba share to use `server max protocol = SMB2_02` fixed the problem for me.  Changing the QNAP NAS to use SMB 2.0 (which internally sets the same setting) fixed it on that share as well.

The only way left to mess it up that I can think of is that losing my VPN connection to the samba share stops Typora from observing any further changes.  That happens a couple times a day for me, but I'm generally aware of it and can reload the file to resume change observation.  So you can probably go ahead and close this now.

On a not-entirely unrelated note, when will it be possible to *pay* you for this thing?  Even just "donations".  Because at this point I feel totally guilty about this being free.  :)

**Comment by abnerlee** [comment] 2017-12-15 03:03
Since this is a network driver issue, we will merge this info https://github.com/typora/typora-issues/issues/1058

**Closed by abnerlee** 2017-12-15 03:03 UTC
Labels: bug
