### ISSUE TITLE
Using '-' + space to start a new line item, user exists edit mode

### ISSUE THREAD

**Issue by Nataland** [typora/typora-issues#1975] opened 2018-11-20 02:19 UTC
By exiting edit mode I mean users need to click the screen in order to be able to type again.

MacOS high sierra v10.13.4

**Comment by khaggerty-adev** [comment] 2018-11-27 21:10
I have this same issue now. When I hit return and then attempt to make a bulleted list, the cursor moves to the beginning of the document.

**Comment by abnerlee** [comment] 2019-01-09 17:35
Cannot reproduce this now, should be fixed in new release, please reopen it if the exists in new version

**Closed by abnerlee** 2019-01-09 17:35 UTC
