### ISSUE TITLE
level up or down all the title's level by one step.

### ISSUE THREAD

**Issue by dulm** [typora/typora-issues#2466] opened 2019-05-03 07:19 UTC
When copy content from web, all the title's level is one level small then the correct value.  User have to level up title one by one, hope to add a feature to level up or down all the title in selected range.

**Comment by vassudanagunta** [comment] 2019-05-04 00:52
Dupe of #2376

**Comment by abnerlee** [comment] 2019-05-14 15:01
#2375

**Closed** 2019-05-14 15:01 UTC

**Comment by dulm** [comment] 2019-06-28 02:38
temp python code:

```python
def lvl_up_title():
    str = pyperclip.paste()
    regx = re.compile(r"^##", flags=re.MULTILINE)
    for m in regx.finditer(str):
        print(m.groupdict())
    def sub_func(m):
        dic = m.groupdict()
        return f"#"
    result_str = regx.sub(sub_func, str)
    #print(result_str)
    pyperclip.copy(result_str)
```
