### ISSUE TITLE
PDF export is showing incorrect non-monospaced dash characters in inline code

### ISSUE THREAD

**Issue by CherryDT** [typora/typora-issues#5406] opened 2022-09-06 20:25 UTC
- [X] Searched existing issues to avoid creating duplicates.

- [X] Confirmed that it can be reproduced in built-in themes without customized css.

- [X] Searched http://support.typora.io/

----

**Describe the bug**
When dashes are written in inline code, they will become non-monospaced after exporting to PDF.

Markdown:
![image](https://user-images.githubusercontent.com/6010463/188731056-57582403-08d3-4399-843d-de11a82ae19b.png)
PDF:
![image](https://user-images.githubusercontent.com/6010463/188731088-a8f283a4-90d6-48aa-9ff7-33b3069f2831.png)

**To Reproduce**
1. Create a file that contains these contents:  
```markdown
`test --xyz`
```
2. Export as PDF
3. View PDF and notice the incorrect character widths.

**Expected behavior**
The characters should be monospaced.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit

**Typora Version**
1.4.4

**Comment by abnerlee** [comment] 2022-11-23 09:26
caused by the fix of #678

**Comment by abnerlee** [comment] 2023-02-14 04:48
fixed in v1.5.x

**Closed by abnerlee** 2023-02-14 04:48 UTC
Labels: import / export, fixed in dev
