### ISSUE TITLE
Exporting markdown to PDF with PDF images embedded results in low quality png conversions.

### ISSUE THREAD

**Issue by vertesy** [typora/typora-issues#970] opened 2017-10-16 09:53 UTC
- The importance of vector graphics is to be discussed elsewhere (TLDR: png is often not an option in science), but its current use suffers from low quality png conversions upon PDF export of a markdown document with PDF images embedded.

- I believe it is problem with OS X's pdf printer (tried in MOU, same results). 

#### Tries without success
Any html based conversions seem to skip embedded .pdf files:

- [grip](https://superuser.com/questions/689056/how-can-i-convert-github-flavored-markdown-to-a-pdf)
     `pip install grip `
     `grip your_markdown.md`

-  Node.js based markdown-pdf
      `npm install -g markdown-pdf`
      `markdown-pdf /path/to/markdown`

#### Workaround

A current workaround is using pandoc conversion `pandoc X.md -o X.pdf`, but native high quality export / conversion would be a great step forward.

#### Limitations
- Pandoc uses a different CSS by default, that yields a classic LateX document feel over the github flavoured markdown look.

- Code-block style disappears (incl syntax highlight).

- Table of contents generated by Typora is lost. You can add `--toc` to pandoc, but it puts it before anything else, yielding a document that does not start with its title.

Any better solutions / suggestions are welcome.

**Comment by abnerlee** [comment] 2017-10-17 06:38
@vertesy  How about export as HTML, then print in Safari, will the quality be better?

**Comment by vertesy** [comment] 2017-10-17 09:03
Thanks for the suggestion! Exported .html in Firefox does not display .pdf files. Now I checked and it is correctly displayed in Safari.

Nevertheless upon .pdf export (save as / print as pdf) the .pdf image quality is bad (because it uses OS X's engine, I guess).

**Comment by abnerlee** [comment] 2017-10-21 03:38
> Nevertheless upon .pdf export (save as / print as pdf) the .pdf image quality is bad (because it uses OS X's engine, I guess).

We also use OS X's engine for PDF exporting, so I'm closing this because it is caused by the system PDF print engine

**Closed by abnerlee** 2017-10-21 03:38 UTC
