### ISSUE TITLE
Home/End buttons not working correctly in Source Code Mode

### ISSUE THREAD

**Issue by fresheneesz** [typora/typora-issues#3173] opened 2020-01-14 06:40 UTC
Home/End buttons were fixed so they correctly went to the beginning/end of the line (and not the beginning of the paragraph) in issue #2693. However, this is still a bug in Source Code Mode.

**Comment by jgclark** [comment] 2020-01-20 16:50
From looking at your linked issue, I guess this is a Windows-specific request?

On macOS 10.14.6 I get the other behaviour to you: Home/End does BOL/EOL in Source Code Mode, but _not_ in whatever the opposite mode is called.

**Comment by fresheneesz** [comment] 2020-01-22 05:12
Oh hm. Yes I'm using it on windows 10.

**Comment by christophcemper** [comment] 2020-01-26 21:15
Yes, I confirm, same problem here in Source Code mode

**Comment by abnerlee** [comment] 2020-01-31 16:26
Will fix this, but it will still remain a little bug caused by https://github.com/codemirror/CodeMirror/issues/4841

**Comment by abnerlee** [comment] 2022-12-02 09:24
should be fixed already

**Closed by abnerlee** 2022-12-02 09:24 UTC
Labels: windows, source code mode, cursor / selection
