### ISSUE TITLE
error while loading shared libraries: libffmpeg.so

### ISSUE THREAD

**Issue by Chris-Bee** [typora/typora-issues#2686] opened 2019-08-03 12:11 UTC
Hello everybody,
I'm using Ubuntu 16.04, just updated Typora to 0.9.73-1 and I'm getting this error message:

`typora: error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory`

Thanks in advance,
Chris

**Comment by Chris-Bee** [comment] 2019-08-03 12:14
I downgraded for the time being:
`apt-get install typora=0.9.72-1`

**Comment by cornelusleroux** [comment] 2019-08-03 12:42
This also happens on Debian 10 with Typora 0.9.73-1.

Looking at the directory, `libffmpeg.so` is present:
```bash
$ ls -l /usr/share/typora/ | grep lib
-rwxr-xr-x 1 root root    253344 Aug  3 11:46 libEGL.so
-rwxr-xr-x 1 root root   3134880 Aug  3 11:46 libffmpeg.so
-rwxr-xr-x 1 root root   5830320 Aug  3 11:46 libGLESv2.so
```

It seems the linker path is weird:
```bash
$ ldd /usr/share/typora/Typora
  linux-vdso.so.1 (0x00007fff177fd000)
  libffmpeg.so => /usr/share/typora/./libffmpeg.so (0x00007f6852853000)
  libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f685282d000)
  ...
```

**Comment by luizbills** [comment] 2019-08-03 15:57
Same issue on Ubuntu 19.04

**Comment by abnerlee** [comment] 2019-08-03 15:59
Can confirm this. Seems issue caused by permissions on deb package.

Already fixed by re-package the deb installer, you could try update Typora again or: 

```
sudo apt-get update
sudo apt-get install --install typora
```

**Closed by abnerlee** 2019-08-03 15:59 UTC

**Comment by cornelusleroux** [comment] 2019-08-03 16:11
Can confirm it is fixed now. I still had to run `sudo chmod 4755 /usr/share/typora/chrome-sandbox` to get rid of

```
[16401:0803/180809.680730:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/share/typora/chrome-sandbox is owned by root and has mode 4755.
```

after updating, but that is a different issue.

**Comment by tanjuntao** [comment] 2020-03-09 12:48
> Can confirm this. Seems issue caused by permissions on deb package.
> 
> Already fixed by re-package the deb installer, you could try update Typora again or:
> 
> ```
> sudo apt-get update
> sudo apt-get install --install typora
> ```

I've tried this but I got the following problem:
```
E: Command line option --install is not understood in combination with the other options
```
What should I do?
