### ISSUE TITLE
Typewriter mode always "enabled" after restart

### ISSUE THREAD

**Issue by cmeeren** [typora/typora-issues#1509] opened 2018-05-22 11:16 UTC
Using Typora for Windows 0.9.51. After each restart, Typewriter behavior is enabled, though the checkbox in the preferences is disabled. I have to enable and disable Typewriter mode to fix it (after every restart).

**Comment by abnerlee** [comment] 2018-05-22 16:27
We don't have Typewriter mode in preferences panel. It can only be enabled/disabled under `View` menu. And the setting you made from Menu will be saved.

I cannot reproduce this bug, by enable and disable Typewriter mode from menu, and then restart Typora, it seems typewrite mode won't be enabled incorrectly.

Could you tell me how you could reproduce this bug?

**Comment by abnerlee** [comment] 2018-05-23 03:00
”always keep caret in the middle of the screen when in typewriter mode“ means we will put caret in middle when you press up/down key.

When Typewriter mode is enabled, the caret will be in middle after start. To close it, you will need to disable Typewriter mode in menu bar

**Comment by cmeeren** [comment] 2018-05-23 06:41
No, what I meant was that the "always keep caret in the middle of the screen when in typewriter mode" setting does not seem to be saved properly. As long as typewriter mode is enabled, the behavior toggled by the "always keep caret in the middle of the screen when in typewriter mode" setting is enabled even if the actual checkbox in Preferences is off.

Let me try a bit more detailed repro:


1. Enable Typewriter mode and the "Always keep caret ..." setting.
2. Current behavior (correct): Caret is always in the middle when up/down is pressed.
3. Disable "Always keep caret ..." setting
4. Current behavior (correct): Caret can move up/down on page and is not always centered.
5. Exit Typora
6. Start typora
7. Current behavior (incorrect): Caret is always in the middle when up/down is pressed. This indicates that the "always keep caret ..." setting is turned on, but we just turned it off before restarting Typora. In Preferences, the "always keep caret ..." setting is off, even though its behavior is turned on.
8. Enable the "always keep caret ..." setting.
9. Current behavior is now identical to point 7, which is correct since we have now enabled the setting.
10. Disable the "always keep caret ..." setting
11. Current behavior (correct): Caret can move up/down on page and is not always centered.

Further information: typewriter mode does not need to be enabled for this bug to occur, only for it to be observed. If you disable typewriter mode and the "always keep caret ..." setting, and restart, and then enable typewriter mode again, the "always keep caret ..." behavior is now turned on even though the setting is disabled.

Was this understandable?

**Comment by abnerlee** [comment] 2018-05-23 09:20
Yes, I can confirm it this is bug. Thanks for your patience and report.

**Comment by abnerlee** [comment] 2018-05-28 02:32
Fixed in new release

**Closed by abnerlee** 2018-05-28 02:32 UTC
Labels: bug

**Comment by yerumaku** [comment] 2020-07-30 14:00
Can I not disable `checkbox` when printing in HTML? 
I use them in the my css theme to collapse lists.

```css
ul > li.task-list-not-done:first-child ~ li {
  display: block;
}
ul > li.task-list-done:first-child ~ li {
  display: block;
}
```
```html
<li class="md-task-list-item task-list-item task-list-done">
  <input type="checkbox" disabled="disabled" checked="">
  <p><span>collapsed</span></p>
</li>
```
