### ISSUE TITLE
Ctrl+backspace hides text cursor [linux] - now borderline unusable

### ISSUE THREAD

**Issue by Beanie127** [typora/typora-issues#4336] opened 2021-04-27 08:30 UTC
Running ElementaryOS 5.1.7 (built on Ubuntu 18.04.4 LTS).

I just updated to 0.10.3 on Linux and the text input cursor/caret frequently disappears midway through editing a document, meaning subsequent presses of the space bar cause the document to scroll down. 

Haven't been able to identify all triggers, but control+backspace is the most consistent one, it reliably deletes the previous word and then hides the cursor. It also disappears apparently at random, making the software borderline unusable for any length of time.

**Comment by goodyg** [comment] 2021-04-27 20:46
This is happening in Windows as well after I upgraded to the latest version this morning to 0.10.2. I agree that it makes it very hard to use because I use Ctrl-Backspace all the time to delete words. One other possible clue is the bullets in my document flash each time I use Ctrl-Backspace. It also makes it difficult to type because because pressing space or backspace after trigger the issue then scrolls the document up/down and I have to scroll back to where my cursor was.

**Comment by Cobertos** [comment] 2021-04-28 00:49
Was not able to reproduce on this on 0.10.4 (beta) on Linux Mint 20.1 x86_64

I tried copying another document and deleting it with Ctrl+Backspace; also tried with Inline Math turned on and Using Ctrl+Backspace through paragraphs with some inline math and math blocks and was not able to get the cursor/caret to disappear.

Perhaps 0.10.4 cursor fix fixed this? 

```
0.10.4

1. Fix cursor in inline math.
```
https://typora.io/dev_release.html

**Comment by Beanie127** [comment] 2021-04-28 08:11
I've just updated to 0.10.6 and the issue persists. I've tried turning of inline math to see if that has an impact, and it made no difference.

**Comment by abnerlee** [comment] 2021-04-28 09:17
@Beanie127 could you send us <hi@typora.io> a screencast? We didn't reproduce either

**Comment by Beanie127** [comment] 2021-04-28 10:12
Sent. I've noticed that the problem only seems to happen in some existing files, not in a new document.

**Comment by goodyg** [comment] 2021-04-28 23:07
I've recreated the issue (windows). It appears to be related to the size of the document. A doc with 6000 words (asdf) doesn't have the issue but the document below with 15000 words (asdf) does. Using Ctrl-backspace to delete a word causes the cursor to disappear and then pressing space then scrolls down the document.

[WordIssue.md](https://1drv.ms/u/s!AhZNblyBDLdp0zCgTLhYUNR4Djb0?e=4HU7mG)

**Comment by TheHolyDenier** [comment] 2021-04-30 17:32
I've experienced this issue too with control + backspace. Windows, version 0.10.6 (noticed first at 0.9.98, I think) and in a big file (about 250k characters, 40k words).  😊

**Comment by abnerlee** [comment] 2021-05-01 03:37
@goodyg Still ok in my test, so "ctrl+backspace" on which location? After the first paragraph, or end of first paragraph, or on first word?

**Comment by dovinmu** [comment] 2021-05-05 18:32
Can confirm this is happening on 10.7 (beta) with Windows 10 Pro 19042.928 after Typora auto-updated. This bug suddenly made Typora very hard to use for me. 

What happens:
Ctrl + Backspace
Cursor disappears
Nothing I type is entered into the file, hitting space scrolls down the file

This doesn't happen if I start a new file, nor does it happen if I copy the contents of the file having issues into a new file.

**Comment by abnerlee** [comment] 2021-05-09 10:42
should be fixed in latest version

**Closed by abnerlee** 2021-05-09 10:42 UTC
Labels: bug, cursor / selection, hybrid editing

**Comment by dovinmu** [comment] 2021-05-11 16:28
That fixed it for me, thank you!
