### ISSUE TITLE
Page scroll after saving in Source Mode

### ISSUE THREAD

**Issue by jtr109** [typora/typora-issues#585] opened 2017-03-10 11:55 UTC
My Typora version:
  - Version 0.9.9.9.3 (0.9.9.9.3)
  - beta version for preview

My OS:
  - OS X EI Capitan
  - Version: 10.11.6 (15G1217)

This issue happens in the _Source Mode_ in new version.

When I type `Meta + s` for saving after edited a file and an `(Edited)` shown on the title. The page will scroll immediately and the line where cursor stays will show on the bottom of the window.

For example:

I opened a file with 100 lines and switch into _Source Mode_. Then I edited the line 50 in the middle of the window and left the cursor on this line. After typing `Meta + s` for saving, the whole page would move and the line 50 showed on the bottom of the window.

**Comment by mdeboer** [comment] 2017-04-20 07:48
Same here with version 0.9.9.9.4.2 unfortunately.

**Comment by abnerlee** [comment] 2017-08-11 16:05
should be fixed in the newest version, since I cannot reproduce it for now

**Closed by abnerlee** 2017-08-11 16:05 UTC
Labels: bug

**Comment by jtr109** [comment] 2017-08-12 00:29
Thanks a lot and I will have a try. 😄
