### ISSUE TITLE
Inconsistent copy behaviour of multi-paragraph text from live preview mode 

### ISSUE THREAD

**Issue by gasedwards** [typora/typora-issues#4343] opened 2021-04-28 10:15 UTC
Typora 0.10.6 (5297) [macOS]

*Issue:*
Copying multi-paragraph text using `CMD + C` from the seamless live preview truncates text at the end of the first paragraph in formatting aware programs (tested in TextEdit, Mail, MS Word).

*Expected:*
Text is pasted with basic formatting (bold, italics etc)

*Workaround:*
Use `CMD + SHIFT + C` for MD-formatted text or Copy Plain Text

**Comment by abnerlee** [comment] 2021-05-08 16:04
I cannot reproduce this (typora -> TextEditor), possible to attach a screencast?

**Comment by gasedwards** [comment] 2021-05-09 20:45
Issue is reproducible for me when the first paragraph being copied has any formatting in it (e.g. **bold** or *italic*)

https://user-images.githubusercontent.com/39886718/117586400-d3256080-b10f-11eb-9ae1-982b6f23e38a.mp4

**Comment by abnerlee** [comment] 2021-05-28 16:07
relates #1236

**Comment by abnerlee** [comment] 2021-07-20 13:58
should be fixed

**Closed by abnerlee** 2021-07-20 13:58 UTC
Labels: hybrid editing
