### ISSUE TITLE
I can not use MathJax mhchem '\pu{}' command in typora

### ISSUE THREAD

**Issue by chem1024** [typora/typora-issues#2079] opened 2019-01-12 05:22 UTC
$\pu{123 kJ*mol-1}$
it works in my blog, but it does not work in typora.

**Comment by abnerlee** [comment] 2019-01-20 14:17
caused by #1045

**Comment by abnerlee** [comment] 2019-01-25 13:49
Fixed in new release

**Closed by abnerlee** 2019-01-25 13:49 UTC
Labels: 3rd party lib
