### ISSUE TITLE
Chinese quotes and brackets will become English quotes and brackets

### ISSUE THREAD

**Issue by xiaochunjimmy** [typora/typora-issues#2494] opened 2019-05-13 05:15 UTC
I choose Chinese to create this issue because this is a problem related to Chinese.
</br>
当勾选了”使用成对的符号 → 匹配括号和引号“的时候，中文输入法下输入的引号和括号会被转化为英文标点。但这并不是我们想要的。

**Comment by abnerlee** [comment] 2019-05-13 07:03
try update?

**Comment by xiaochunjimmy** [comment] 2019-05-13 08:57
When I was trying to update Typora, I got the message "Typora 0.9.9.24.6 is currently the newest version available".
</br>
The problem's not solved, I'm sorry. @abnerlee 
</br>
My system language is English and my Typora language is Chinese.
When I typed the Chinese quotation mark, it printed the English quotation mark when I checked the "Auto pair brackets and quotes". It should be Chinese quotes and auto-paired.
It seems that the "auto pair" function forced transfer Chinese quotes to English quotes.
</br>
This is English quotes and brackets:  `""` , `()`
This is Chinese quotes and brackets: `“”` , `（）`

**Comment by abnerlee** [comment] 2019-05-14 01:26
What's your IME?

Does this happen when you input on empty paragraph, or happens when you select some text and input quotes?

**Comment by xiaochunjimmy** [comment] 2019-05-14 02:36
I used the Sogou input method. Sogou-input is the most popular input method in China.
</br>
It just happens when I input quotes or brackets in a sentence.
Many Chinese users face the same bug, I contacted the customer service of Sogou-input, they said they debugged and this is the problem of Typora.
This problem only happens when I checked the function of "Auto pair brackets and quotes".

**Comment by abnerlee** [comment] 2019-05-14 14:44
I see, we will check it. What's your macOS version?

**Comment by xiaochunjimmy** [comment] 2019-05-14 14:50
Mojave 10.14.4

**Comment by abnerlee** [comment] 2019-06-21 16:11
should be fixed in latest version

**Closed by abnerlee** 2019-06-21 16:11 UTC
Labels: macOS

**Comment by xiaochunjimmy** [comment] 2019-06-22 14:21
Thank you for your efforts

**Comment by xu-kai-xu** [comment] 2020-01-13 01:27
Is this problem solved? I meet the same problem and can not figure it out.

**Comment by chchen-stanford** [comment] 2021-02-12 22:40
I have encountered a similar problem with the Chinese quotation marks. After some testing, I think this is the issue: In Typora, somehow the quotation marks are always parsed as an English character, even if the input method is Chinese. As an example, I use macOS "Pingyin - Simplified" for Chinese input. The quotation marks are only "correct" when the English font is something like Georgina or Overpass, for which the English quotations marks happen to looks similar to the Chines counterparts.

@abnerlee, could you please change the parsing so Chinese quotations marks (entered using Chinese input method) are always rendered as Chinese, regardless of the English font adopted?

**Comment by chchen-stanford** [comment] 2021-02-13 12:04
I have encountered a similar problem with the Chinese quotation marks. After some testing, I think this is the issue: In Typora, somehow the quotation marks are always parsed as English characters, even if the input method is Chinese. As an example, I use macOS "Pingyin - Simplified" for Chinese input. The Chinese quotation marks only appear "correct" when the English font is something like Georgina or Overpass, for which the English quotation marks happen to look similar to their Chinese counterparts.

@abnerlee, could you please change the algorithm so Chinese quotation marks (entered using Chinese input methods) are always rendered as Chinese, regardless of the English font adopted?

**Comment by abnerlee** [comment] 2021-02-14 15:20
> could you please change the algorithm so Chinese quotation marks (entered using Chinese input methods) are always rendered as Chinese, regardless of the English font adopted?

Have you try set a Chinese font following https://support.typora.io/Custom-Font/ ?

**Comment by chchen-stanford** [comment] 2021-02-14 17:44
Yes, I actually specify most of my Chinese fonts explicitly. Here are some examples:

whitey.user.css
body {
font-family: "Palatino", "Noto Serif SC", serif;
}

body {
   font-family: "PT Serif", "Noto Serif SC", serif;
}

See the attached screenshots. Although the Chinese font choice is identical, only the PT Serif font gives a Chinese looking quotation mark.

[cid:BE88B8FE-5D5C-40A6-A590-1D772476F103]
[cid:1033239B-6953-44DD-9851-AE4FF308261C]
Chuan-Hua Chen

On Feb 14, 2021, at 10:20 AM, AbnerLee <notifications@github.com<mailto:notifications@github.com>> wrote:



could you please change the algorithm so Chinese quotation marks (entered using Chinese input methods) are always rendered as Chinese, regardless of the English font adopted?

Have you try set a Chinese font following https://support.typora.io/Custom-Font/ ?

**Comment by chchen-stanford** [comment] 2021-02-14 17:49
Yes, I actually specify most of my Chinese fonts explicitly. Here are some examples in whitey.user.css:

body {
	font-family: "Palatino", "Noto Serif SC", serif;
}

body {
   font-family: "PT Serif", "Noto Serif SC", serif;
}

Although the Chinese font choice is identical, only the PT Serif font gives a Chinese looking quotation mark.

**Comment by chchen-stanford** [comment] 2021-02-26 20:09
@abnerlee Do you think this issue with Chinese quotation marks can be addressed? For those of us who write both Chinese and English, the quotation mark issue is quite limiting. For example, instead of using my favorite font Avenir, I would need to settle on a less appealing alternative like Nunito Sans, just so that I can get the appropriate Chinese quotation marks.

**Comment by abnerlee** [comment] 2021-03-03 07:59
We don't have any special algorithm for this, the rendering is handled by the system.

Does Chinese quote in other apps, like Safari or TextEdit.app also looks like English quotes? If not, what fonts are you using? Could you specify the same font in Typora?

**Comment by xu-kai-xu** [comment] 2021-03-03 09:12
@abnerlee, hi, I don't know how Chinese quotation looks like in Safari or other apps. I think the problem is that for English punctuation, the symbols are all half-width characters, but for Chinese punctuations, the symbols are all full-width characters. .And the result is not related to the font I use. I show an example in MS word:
![image](https://user-images.githubusercontent.com/44153643/109778597-f92a1280-7c3f-11eb-8b06-d0c173bfaf9f.png)

In the above figure, I highlight the width of the quotations and the periods.

In typora, the English period and Chinese period take occupy different widths. But the English quotation and Chinese quotation seem the same.
![image](https://user-images.githubusercontent.com/44153643/109779730-30e58a00-7c41-11eb-82e5-809869c52ca2.png)

And the utf-8 code for a Chinese quotation is `&#x201C;` for left quotation and `&#x201D;` for right code.
I got this from [here](https://www.sojson.com/utf8.html).

**Comment by chchen-stanford** [comment] 2021-03-03 11:51
@abnerlee I did some further testing with TextEdit. If I use plain text, then TextEdit has the same problem as Typora. I only get the appropriate Chinese quotation marks with certain fonts that have curly quotation marks. However, if I use rich text format, then TextEdit always yields the correct quotation mark. On the toolbar, I can visibly see the font changes from Avenir (my default font) to PingFang SC the moment the input method is switched from "US" to "Pinyin Simplified". 

The following behavior of TextEdit is revealing. The moment I convert a rich text to plain text (by choosing TextEdit/Format/Make Plain Text), a Chinese quotation mark is automatically converted to its English counter part, even though other Chinese texts are preserved. 

My tests with TextEdit suggest that the quotation mark issue is inherent in macOS. Since markdown file is in plain text, there is not much Typora can do unless macOS appropriately preserves Chinese quotation marks.

**Comment by abnerlee** [comment] 2021-03-04 14:46
Yes, this is a macOS bug / spec.

try use this font as a workaround -> https://www.zhihu.com/question/35110457/answer/61344040 ?

**Comment by chchen-stanford** [comment] 2021-03-04 15:19
For those Typora users who write in both English and Chinese, I am posting here what I have learned about quotation marks:

(1) There is a macOS bug that automatically converts Chinese quotation marks into English ones in a plain text file. This bug is affecting Typora.

(2) The built-in English letters associated with a Chinese font are meant for occasional use in a primarily Chinese text. For truly mixed English and Chinese writing, it is best to specify a good English font first, and then a Chinese font.

(3) The best workaround I found is to have a pair of themes. In one theme, use your favorite English font (that often does not have curly quotation marks). In another family, use a comparable English font that has curly quotation marks. You can then choose a theme depending on your mode of writing. 

An example serif pair:
--font-family: "Palatino", "Noto Serif SC", serif;
--font-family: "Iowan Old Style", "Noto Serif SC", serif;

An example sans-serif pair:
--font-family: 'Avenir Roman', 'PingFang SC', sans-serif;
--font-family: 'Nunito Sans', 'PingFang SC', sans-serif;
