### ISSUE TITLE
[FEATURE REQUEST] Themes Issues

### ISSUE THREAD

**Issue by jinchoung** [typora/typora-issues#2562] opened 2019-06-15 04:25 UTC
- currently, typora does not remember the theme you are using until you close out of the program. if the process is killed (when computer shuts down), typora does not remember the theme you changed to. would be better if it just remembers the theme state as soon as it is changed.
- is it possible to link the theme repository more directly to typora? would be cool if i could just download and browse the themes within typora.

thanks!

**Comment by abnerlee** [comment] 2019-06-21 16:46
> currently, typora does not remember the theme you are using until you close out of the program. i

Which Typora / OS version? I cannot reproduce this one.

**Comment by jinchoung** [comment] 2019-06-21 18:59
i'm using win 10 version and i saw this with the version before this latest one.

i have my home pc scheduled to turn off at 4am in the morning. i noticed that when i switched the theme in the evening, when i booted up the next day and started typora, the theme didn't "take".

so i did an experiment where i changed the theme then closed typora manually. when i opened up typora again, the theme remained changed.

so it seemed to me that the anomaly occurs when the pc shuts down typora when it's shutting down itself - which i assumed was the same as killing the process.

i'm currently on the newest version of typora and i've tried killing the process instead of closing and if i had changed themes, the changed theme remains when i re-open typora. so either it is fixed or there's something different that's happening to close typora when a pc is shutting down.

thanks!

**Comment by abnerlee** [comment] 2020-12-14 03:58
the theme unchanged should be fixed.

Others may relates to #4035

**Closed by abnerlee** 2020-12-14 03:58 UTC
Labels: Need more info
