### ISSUE TITLE
Outline view scrolls to top while editing

### ISSUE THREAD

**Issue by uayebforever** [typora/typora-issues#3456] opened 2020-04-28 16:56 UTC
With an outline that is longer than the space available in the sidebar, the view regularly scrolls to the top while editing.

It looks like this happens when I move through a heading in the editor (no change to heading required). I suspect this causes an update to the outline, which makes it repaint without remembering the scroll position.

Kind of annoying if you have a long document/outline.

Using latest and greatest version. (Typora is truly beautiful, by the way!)

**Comment by abnerlee** [comment] 2020-05-14 13:54
Possible to attach a screencast for this? I cannot reproduce this one.

**Comment by uayebforever** [comment] 2020-05-14 22:35
I can. 
[TyporaBugSmall.mp4.zip](https://github.com/typora/typora-issues/files/4631278/TyporaBugSmall.mp4.zip)

**Comment by abnerlee** [comment] 2020-06-13 14:01
should be fixed

**Closed by abnerlee** 2020-06-13 14:01 UTC
Labels: cursor / selection
