### ISSUE TITLE
[Suggestion] Per Document Image Drag and Drop autocopy

### ISSUE THREAD

**Issue by fluffymadness** [typora/typora-issues#1135] opened 2018-01-01 18:43 UTC
First, thanks for this awesome software!
I basically use typora as a word replacement. I often write documents where I need to copy / drag and drop a lot of images from webpages into them.
Would it be possible to make an option (when ticked) that makes typora autocreate a folder with the same name as the current document, and that gets used for the document ressouces everytime I create a new document and save it somewhere.

For example I make a new document MyDocument with Typora and save it on my Harddisk.
As soon as I paste an image into the open Document a .MyDocument folder is created in the same path, and the image is copied to this directory and referenced with a relative path in the Markdown file.
This way I would have a seperate resource folder for every document making it more convenient especially when something needs to be deleted

e.g 

D:/Documents

> MyDocument.md
> .MyDocument/
> - Image1.jpg
> - Image2.jpg
> - Image3.jpg
> 
> MyDocument2.md
> .MyDocument2/
> - Image1.jpg
> - Image2.jpg

Hopefully something like this could be implemented.

**Comment by liquidblasted** [comment] 2018-02-26 09:35
+

**Comment by liquidblasted** [comment] 2018-02-26 09:35
+1

**Comment by vassudanagunta** [comment] 2018-02-26 11:24
Dupe of #1073

**Comment by abnerlee** [comment] 2018-03-13 07:19
Supported in new release. 

Should be configured first in preference panel

**Closed by abnerlee** 2018-03-13 07:19 UTC

**Comment by asins** [comment] 2018-03-19 07:42
What version started to support the automatic reproduction of images and the relative location of documents?

**Comment by abnerlee** [comment] 2018-03-19 09:07
0.9.47/0.9.9.13.6
