### ISSUE TITLE
Question about privacy

### ISSUE THREAD

**Issue by marflow** [typora/typora-issues#2969] opened 2019-10-29 19:38 UTC
Hi, I just started Typora on a Mac running Catalina and the attached window pops up. Why would Typora want to receive keystrokes from any application. Thanks.
<img width="469" alt="Bildschirmfoto 2019-10-29 um 20 31 37" src="https://user-images.githubusercontent.com/6233748/67802709-ff2c4400-fa8b-11e9-9f1a-d546aa234840.png">

**Comment by abnerlee** [comment] 2019-11-05 10:03
It is not needed, please deny it.

In my investigation, it occurs when you open the save file dialog, when saving files, exports, etc.

The cause would be that we set "NSUseRemoteSavePanel" as "False" when launching app to fix a issue that sometimes save file dialog cannot be shown (#2895) and also speed up the save file dialog. I don't know why apple consider this as input monitoring. Also, the save file dialog cannot be shown exists in a few users, but can be fixed by cleaning Typora caches / configs, but set the defaults seams easier than telling users to clean old data. I didn't notice about the privilege popup after this change.

We will make thisway as fallback when save file dialog cannot be shown in next version, you could run 

defaults delete abnerworks.Typora NSUseRemoteSavePanel 

in terminal to delete that config from next version. Or just net Typora being denied about this privileges

**Comment by marflow** [comment] 2019-11-07 09:46
Thanks abnerlee. I removed Typora from System settings > Input Monitoring and ran "defaults delete abnerworks.Typora NSUseRemoteSavePanel" in the terminal but the Typora asks again and the app is added to Input Monitoring again (but not checked). 
Hope this can be worked out and Typora is/was not really tracking keyboard input on older OS versions. The combination of this issue and Typora not having any company / people and contact info behind it is troubling.

**Comment by LeBaux** [comment] 2019-11-08 13:58
> The combination of this issue and Typora not having any company / people and contact info behind it is troubling.

I find it curious, it is the case with a lot of devs from eastern countries (China/Japan). There is some info about the author here https://abnerlee.github.io/about/ and he also linked to his flicker, so I do not think he is hiding per se. It is just how they roll.

**Comment by abnerlee** [comment] 2019-11-30 05:22
New version is available, so new logic is
1. try to get a Save Panel
2. if failed, set NSUseRemoteSavePanel as true (this is not runtime config, but stored on disk)
3. try to get a Save Panel

When NSUseRemoteSavePanel is true, this dialog will show.

So, after upgrade, please clear all settings using 3rd tools like App Cleaner (#2895), then restart Typora,
If the dialog still show, repeat the process (until Typora can get Save Panel in step 1 without setting NSUseRemoteSavePanel as true, which means #2895 did not happen)

---
Or simple deny the request since we will not listen keystrokes from other apps.

**Closed by abnerlee** 2019-11-30 05:22 UTC

**Comment by cmcramer** [comment] 2020-02-28 03:38
I got this request, when saving a new file, after updating to Version 0.9.9.32.1 (4191). IIRC steps were:

1. ⌘-n to open new file
2. Add some lines of text
3. ⌘-s to save
4. Dialog pops up asking user to go to System Preferences and allow Typora to monitor keystrokes from other applications.
