### ISSUE TITLE
Zero width spaces (randomly) inserted by Typora

### ISSUE THREAD

**Issue by mschroen** [typora/typora-issues#403] opened 2016-11-04 18:53 UTC
Sometimes it happens that Typora inserts Unicode `U+200B`, mostly before the end of inline math (i.e. before `$` or `\)`) without the users knowledge. In these cases, `pdflatex` has a hard time to compile the Typora files that were converted from `.md` to `.tex` using `pandoc`.

```
! Package inputenc Error: Unicode char ​ (U+200B)
(inputenc)                not set up for use with LaTeX.
See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...
l.219 ...data point $\theta_{P,L}​
                                 $ according to its depth...
```

**Comment by yougotwill** [comment] 2017-04-04 07:48
I'm also having this issue but it is when I work with unordered lists in the latest version

**Comment by gambrell** [comment] 2018-01-09 16:53
I am seeing this with code fences

**Comment by abnerlee** [comment] 2018-11-03 14:01
should be fixed

**Closed by abnerlee** 2018-11-03 14:01 UTC
Labels: bug

**Comment by arorar** [comment] 2019-01-30 17:43
Typora still sporadically inserts a Unicode char â€‹ (U+200B) (zero width space) in inline latex expressions. I cannot systematically replicate the problem. I am using 0.9.64 beta on Windows.

**Comment by bobbygryzynger** [comment] 2019-02-14 23:51
I'm also seeing the issue with `U+200B` characters in latex blocks.

**Comment by zhou13** [comment] 2019-04-03 00:37
I can confirm this.  Please reopen this issue.

**Comment by okatsn** [comment] 2019-04-09 02:47
In my case, not only â€‹ is occasionally inserted, en dash (–) sometimes automatically **be replaced** by â€“. For example, "Q–Q plot" becomes "Qâ€“Q plot" after reopen the same document. I think this is a serious problem since Typora will change the content of document without user conscent.

**Comment by abnerlee** [comment] 2019-04-17 08:36
Math related is on #2403

**Comment by pariterre** [comment] 2019-05-19 03:45
Since my issue has been referenced here, I will answer the question on which version I use here. 
I run Typora on Ubuntu, version 0.9.70(beta) installed from command line. I may not have updated for a while now though (and I am not sure what is the latest version)

**Comment by abnerlee** [comment] 2019-05-19 14:01
@pariterre It is the latest version. Possible to provide the detailed steps to reproduce this ?

**Comment by pariterre** [comment] 2019-05-19 20:49
Here is a copy paste of issue 2506:

Hi there,

I was using Typora for writting paper using markdown, it looks very good and is very pleasant to use!
I have a weird bug (maybe a feature?). If I bounce between source code and render while writing inline equations, Typora sometimes (seems random..) adds a character prior to the $ of the equation that I copy-paste here: "​" (please note that there is the actual character between the " " but is not an ASCII character so it doesn't print; in Typora it is shown as a red dot).

To reproduce the bug, I've created a new file, put Typora in source code mode and typed "$f$ " (please note the space after the second $). Then I clicked on the letter f while still being in source code mode, then swap to rendered mode, then I clicked after the space, and switch back to source code mode. Please note this is not the only way to make this character appears, but seems to be the most consistent.

I hope my description was clear enough!

Thanks :)

**Comment by abnerlee** [comment] 2019-05-20 13:32
> Then I clicked on the letter f while still being in source code mode
This means click after letter f or select letter f?

**Comment by pariterre** [comment] 2019-05-20 16:51
Click after, but as stated, I can happen in other context as well. And sometimes it doesn't happen. Then I just switch the mode, click elsewhere and switch mode again. Eventually, this happens

**Comment by NotAPenguin0** [comment] 2019-08-06 07:55
I'm  having an issue with this as well, latest version. Typora is insterting U+200B when exporting to HTML in my C++ code blocks, making them not compile. An example of such a code block where the happens is:
```cpp
#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}
```

**Comment by NotAPenguin0** [comment] 2019-08-06 09:11
Update: the reason that this happens is because CodeMirror (the plugin used for rendering the code) uses zero width spaces to represent empty lines.

**Comment by raymondlaw** [comment] 2020-01-11 04:03
Thanks for the update, I was able to work around this problem by removing blank lines for now
