### ISSUE TITLE
[Bug] Cursor moving to the head of the file unexpectedly when pasting

### ISSUE THREAD

**Issue by trisct** [typora/typora-issues#4073] opened 2020-12-23 03:25 UTC
Hi, I am using typora 0.9.98 (beta) on ubuntu 20.04. I discovered the bug when trying to paste texts into a task list (not sure yet whether pasting in other cases produces the same bug).

The problem is that after I copy something from another window and click at the end of a list to paste some text, the cursor moves to the start of the file and the text gets pasted there. It is really bugging me because it severely affects my "pasting rhythm".

Steps to reproduce:

1. Write a `.md` file with the contents
```
# example
- [ ] list item
```
2. Click on another window.
3. Click at the end of the `item`, so that the cursor is right after the letter "m", and immediately after clicking press `Enter` to create a new item.

You would now find that the new item has been created but the cursor is at the start of the file. Note that step 3 must be completed REALLY quickly to reproduce the bug.

Edit: There is also a chance that the cursor returns to the end of the last line.

**Comment by abnerlee** [comment] 2020-12-31 13:01
> Click on another window.

Click to another Typora window, or any window?

**Comment by trisct** [comment] 2021-01-01 10:05
Any window.

**Comment by abnerlee** [comment] 2021-05-01 07:56
I cannot reproduce this now. Should be fixed already

**Closed by abnerlee** 2021-05-01 07:56 UTC
Labels: Need more info, cursor / selection, linux
