### ISSUE TITLE
Wrong keyboard selection behavior spanning multiple lines

### ISSUE THREAD

**Issue by mocsa** [typora/typora-issues#3228] opened 2020-02-06 08:31 UTC
How to reproduce on Windows:
* Enter a paragraph of text which spans at least two full lines.
* Put your cursor in the middle of the first line.
* Press SHIFT+DOWN.
* Text is selected from the middle of the first line to the middle of the second line.
* PROBLEM: My cursor is lost!
  * I cannot move my cursor with the cursor keys.
  * SHIFT+Cursor keys do nothing, therefore I cannot change my selection.
  * I cannot type anything. Like if my Typora window became inactive.
  * When I press UP or DOWN keys, my whole document is scrolled up and down.
* WORKAROUND: Put my cursor back into the document with the mouse. Then I can continue working.

The problem does not happen when I keep SHIFT+RIGHT pressed and my selection reaches the end of the line and continues into the second line. However, as soon as I press SHIFT+UP, that is, my selection crosses a line, my cursor is lost.

The same thing happens if you start in the second line and press SHIFT+UP.

I experience this in version 0.9.83.

**Comment by jgclark** [comment] 2020-02-06 18:09
Can't reproduce on Typora 0.9.9.31.6 on macOS 10.15.3.

**Comment by mocsa** [comment] 2020-02-06 19:50
I couldn't reproduce it, either, but I found a different way to reproduce:
* Go to www.lipsum.com
* On the left of the "Generate Lorem Ipsum" button, enter 80000 into the input box and set the radiobutton to "bytes".
* Click on "Generate Lorem Ipsum"
* Copy the whole text to a new Typora file and save it.
* Close Typora
* Open Typora and open your previously saved file.

This way I was able to reproduce the problem. It seems that it only happens with "bigger" files. Although 80kB is not that big.

**Comment by jgclark** [comment] 2020-02-07 13:46
I tried that method on same device as before, and couldn't reproduce.
However, I did notice the following UI glitch when attempting to reproduce:

<img width="747" alt="Screenshot 2020-02-07 at 13 36 28" src="https://user-images.githubusercontent.com/1671754/74034419-25794e00-49b0-11ea-8617-6a442400bcf8.png">

This only happens when using keyboard (shift-up and shift-down etc.), not when simply click-dragging with the mouse.

**Comment by mocsa** [comment] 2020-02-07 14:40
I can reproduce it consistently with the method in my second comment.

Also note that if I simply copy 80kB of text into a new Typora file I cannot reproduce the problem. Only if I save it into a file, close Typora and then open the file.

**Comment by surf3s** [comment] 2020-03-11 15:42
I have an R markdown document with exactly this problem (Windows 10, Typora 0.9.86).  If I start selectively removing parts of the document (in Rstudio and then pasting into Typora), I can create versions that don't have this problem (I used the test protocol above - paste text into a new document, save it, close it, open it, and check).  But after more than an hour of trying, I can't find a pattern or logic in what I have to delete to make it work.  By the way, it is exactly like jgclark says - it is only when using the keyboard.

**Comment by enly1** [comment] 2020-03-16 13:02
I'm going mad with the whole editing / keyboard operations in typora.

I have the same problem with table editing (wrapped cell) - shift-up to select, then cursor lost.  up/down simply scroll my document.  Overtyping the selection has no effect etc.

Seems to be intermittent but - re-opening the same doc seems to work for a while, then back to problems.

This combined with the crazy cursor management in word wrapped table items is going to be a deal breaker for me soon.  I've just checked the size of my document and interestingly its 36k now and i've just started to experience the problem.

Currently, many standard conventions for cursor management seem to be broken / intentionally different to all other editors.

Linux mint - Typora 0.9.86

**Comment by abnerlee** [comment] 2020-05-23 14:26
should be fixed in latest version

**Closed by abnerlee** 2020-05-23 14:26 UTC
Labels: cursor / selection
