### ISSUE TITLE
Focus Mode notification is showing even when I tick "Do not show again"

### ISSUE THREAD

**Issue by kekePower** [typora/typora-issues#2299] opened 2019-03-19 08:25 UTC
Hi.

Thanks for an awesome product. I love it.

The issue I have with version 0.9.9.67 (linux) is that the notification for Focus Mode keeps showing even if I tick "Do not show again" and click dismiss.
I use Ctrl-N to open a new window. The same happens from File->New.

Cheers,
kekePower

**Comment by abnerlee** [comment] 2019-03-21 02:39
fixed in new release

**Closed by abnerlee** 2019-03-21 02:39 UTC

**Comment by denniskb** [comment] 2020-10-14 05:54
Present again in 0.9.96

**Comment by abnerlee** [comment] 2020-10-14 15:28
I'm not able to reproduce this. Possible to give a screencast?

**Comment by denniskb** [comment] 2020-10-14 15:48
I would tick the box and 'dismiss' the message. The moment I entered the mode again, the message popped up again with the box unticked. Solved by:

1. Enter type writer mode
2. Tick the box, 'dismiss' the popup
3. Exit type writer mode
4. Enter focus mode
5. Tick the box, 'dismiss' the popup
6. Exit focus mode
7. **Restart** Typora

Only then the ticks took permanent effect.

**Comment by abnerlee** [comment] 2020-10-14 16:16
@denniskb Is it possible that you enabled both focus mode and typewriter mode that in the first time focu/s mode alert is shown, then on new window, typewriter mode alert is shown?
