### ISSUE TITLE
Wrong keyboard selection behavior at start/end of paragraph

### ISSUE THREAD

**Issue by lowlight-ua** [typora/typora-issues#3220] opened 2020-02-02 17:21 UTC
Version 0.9.83
Related (but not identical to) #2964 , #1164 

### Steps to reproduce:

(Windows key combinations are mentioned; use equivalent standard combinations on other OSs).

* Create new document.
* Type or paste "Lorem ipsum dolor sit amet".
    * The cursor is after "amet".
* By using Shift+Left, select "sit amet".
* By using Shift+Right, try to unselect "sit".
    * Expected: the left boundary of the selection moves until "sit" is unselected.
    * Actual: one of the two outcomes – either selection is removed completely, or the selection is unchanged.

### Note:

* The bug is also reproducible when selection and unselection operations are word-by-word (e.g. Shift+Ctrl+Left/Right).
* A similar bug is reproducible when the cursor is at the beginning of the paragraph instead of the end; for reproduction, just mirror the steps.
* Really impacts performance due to muscle memory and the frequency of using this combination in other editors when typing.

**Comment by jgclark** [comment] 2020-02-06 18:00
Which OS are you on -- Windows 10.x?
I'm on macOS 10.15.3 / Typora 0.9.9.31.6 and can't reproduce this.

**Comment by lowlight-ua** [comment] 2020-02-06 18:04
I am on Windows 10, yes. Don't have a Mac, so can't verify there.

**Comment by enly1** [comment] 2020-03-16 13:08
FYI - I can't reproduce this issue on 0.9.83 on linux.

**Comment by abnerlee** [comment] 2020-05-23 14:25
Should be fixed in later versions

**Closed by abnerlee** 2020-05-23 14:25 UTC
Labels: cursor / selection
