### ISSUE TITLE
mermaid node not show full text.

### ISSUE THREAD

**Issue by dulm** [typora/typora-issues#4499] opened 2021-07-04 01:29 UTC
- [ ] Searched existing issues to avoid creating duplicates.

- [ ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [ ] Searched http://support.typora.io/

----

**Describe the bug**
mermaid node not show full text.

```mermaid
graph LR
	ca("compileOnlyApi")
	a("api")
	ae("apiElements")
```
show  not correct: `compileOnlyA` `ap` `apiElement`

<img width="1164" alt="WeChat7ae415161041de2c656a3104fce97bea" src="https://user-images.githubusercontent.com/1228446/124410287-b9ee0880-dd7c-11eb-91e1-4e3356071d27.png">
works fine in https://mermaid-js.github.io/mermaid-live-editor/edit/

content in `/Applications/Typora.app/Contents/Resources/TypeMark/lib/diagram/css/mermaid.css`:

```
:root {
  --mermaid-theme: default;
  --mermaid-sequence-numbers: off;
  --mermaid-flowchart-curve: linear;
  --mermaid--gantt-left-padding: 75;
  --sequence-theme: simple;
}
```

how to fix it?

**To Reproduce**

**Expected behavior**

**Screenshots / Screencasts**
If applicable, add screenshots / screencasts to help explain your problem.

**Sample Markdown File**
Please attach or send us <hi@typora.io> the sample md file that may reproduce this.

**Desktop (please complete the following information):**
 - OS:  osx  11.3.1 (20E241)

**Typora Version**
0.10.11 (5372)

**Additional context**

**Comment by abnerlee** [comment] 2021-07-05 08:28
relates #1661

**Comment by abnerlee** [comment] 2021-07-05 14:10
Which theme did you use?
And what is the screen dpi?

**Comment by taminhtienhai** [comment] 2021-07-19 09:30
I also got this problem in HTML exported file

**OS**: Archlinux
**Laptop**: Asus Zenbook 430UA
**Version**: 0.10.11 (beta)

![image](https://user-images.githubusercontent.com/22344452/126137795-a8323395-557d-48e3-81ec-0f3fe80d4cf0.png)

**Comment by hqgu** [comment] 2021-08-07 08:12
I got the same problems. Any solution to this issue?

**Comment by ChunJiu2008** [comment] 2021-08-13 04:11
I also encountered the same problem, it seemed to be worse, the font was enlarged too much, and it couldn't be adjusted.
<img width="741" alt="2021-08-13 11_02_30-基于 Python 的公网 IP 自动上报程序 md - Typora" src="https://user-images.githubusercontent.com/33535956/129303845-3008212f-7f41-4ab1-a556-1c35d766d378.png">

**Comment by hqgu** [comment] 2021-08-18 14:45
It is related to CSS.  This problem is automatically fixed when switched to  some themes.

**Comment by abnerlee** [comment] 2021-08-28 15:44
should be fixed in 0.11.7

**Closed by abnerlee** 2021-08-28 15:44 UTC
Labels: Need more info, 3rd party lib

**Comment by jsionr** [comment] 2021-08-30 09:19
I solved the problem with this CSS code in my theme files:
```css
:root {
    --mermaid-font-zoom: 1em !important;
}
```

**Comment by dulm** [comment] 2021-10-11 08:11
0.11.11  still not fix

**Comment by etiology** [comment] 2021-10-19 20:42
Version 0.11.5 (5648) --> still not fixed

**Comment by MarqueIV** [comment] 2023-10-10 03:58
All, seems this is possibly caused by you having a non-default window zoom.  So either go to the 'View' menu and choose 'Actual Size', or press <kbd>Command</kbd>-<kbd>Shift</kbd>-<kbd>0</kbd>.  If you're already at the default (actual) size, zoom in once, then zoom back out to the default.  This seems to 'reset' Typora's rendering engine.  My app has been clipping the text FOR-EV-AR!!! and I just found that trick, and ever since, it's been perfect again.

Side-Note: Typora creators... you definitely have something going on in your rendering because the issue survived restarts/reboots/etc.  But once you perform the above, again, it seems to 'reset' something so you may want to look into that aspect of things.
