### ISSUE TITLE
Buttons in the Update window aren't doing anything.

### ISSUE THREAD

**Issue by lleuppi** [typora/typora-issues#4559] opened 2021-07-27 10:41 UTC
**Describe the bug**
When starting Typora the "Updates" window pops up. When i try to click on **any** of the buttons nothing happens.

**To Reproduce**
I can't reproduce any steps.

**Expected behavior**
Normally you are able to click any of the buttons:

- Skip this version
- Remind me later
- Download update

But since the last update nothing happens when clicking the buttons

**Sample Markdown File**
I tested it out, it doesn't matter which file i am opening.

**Desktop (please complete the following information):**
OS: Windows 10 64bit

**Typora Version**
0.11.0 (beta)

**Comment by mmpp406** [comment] 2021-07-27 11:14
Me too!

**Comment by Taswen** [comment] 2021-07-28 03:15
🙋‍♂️

**Comment by armando-herastang** [comment] 2021-08-02 11:47
Same thing over here!

**Comment by Geeyun-JY3** [comment] 2021-08-02 15:23
Now that you guys know the buttons is not clickable, why don't you download the latest version 0.11.2 directly from https://typora.io ?

duplicate of #4541
https://github.com/typora/typora-issues/issues/4541#issuecomment-885732720
> should be fixed in 0.11.2, but 0.11.2 requires manually download from https://typora.io

also https://github.com/typora/typora-issues/issues/4541#issuecomment-886326030

**Comment by armando-herastang** [comment] 2021-08-02 15:31
> 
> 
> Now that you guys know the buttons is not clickable, why don't you download the latest version 0.11.2 directly from https://typora.io ?
> 
> duplicate of #4541
> [#4541 (comment)](https://github.com/typora/typora-issues/issues/4541#issuecomment-885732720)
> 
> > should be fixed in 0.11.2, but 0.11.2 requires manually download from https://typora.io
> 
> also [#4541 (comment)](https://github.com/typora/typora-issues/issues/4541#issuecomment-886326030)

I did, thanks so much for the insightful comment 👍 😄 
Just pointing out the `links` weren't working either

**Comment by abnerlee** [comment] 2021-08-03 13:55
#4541

It's bug for 0.11.0 and 0.11.1 please download latest version from https://typora.io manually

**Closed by abnerlee** 2021-08-03 13:55 UTC

**Comment by TomasHubelbauer** [comment] 2021-08-04 08:52
I was hesitant to update by downloading the new version since I wasn't sure if it was going to preserve my settings, but I just did and am happy to report that it did indeed preserve them. Thank you for the fix.
