### ISSUE TITLE
Opening file from "recent files" menu item opens blank file

### ISSUE THREAD

**Issue by mlbrgl** [typora/typora-issues#2467] opened 2019-05-03 11:53 UTC
- OS version: Mac OS 10.14.4
- Typora version: 0.9.9.24.6
- Steps to reproduce the bug:
  - create new file, add some content, save it, close it
  - open through "recent files" menu item
  - bug: the file is empty (0 characters)
- Relevant log entries: 
`par défaut	13:42:22.888033 +0200	Typora	Failed to resolve bookmark 7f8497e08c00 with error: Error Domain=NSCocoaErrorDomain Code=4 "Le fichier n’existe pas."`
[...]
`par défaut	13:42:25.572054 +0200	Typora	readFromPath: /Users/matthieu/Documents/correct/path/to/file.md
`
- Additional info: the file is saved on the main drive

**Comment by borisrorsvort** [comment] 2019-05-06 16:32
Actually this also happens when typora open with the last opened folder. The first file you click on renders a blank page.

Osx version 10.14.4
typora Version 0.9.9.24.6 (2400)

**Comment by abnerlee** [comment] 2019-05-12 13:45
I cannot reproduce it followed your steps, could you provide more details to reproduce it. Also, what is the path of saved file? Does it contains any special characters?

**Comment by borisrorsvort** [comment] 2019-05-12 13:55
Quit Typora while editing a file within a folder. Open again. It opens a blank page. Then click on a file. Still a blank page but title is correct. Then click on another file. It opens that other file correctly.
So it’s always the first file you click on right after Typora opened that doesn't work.
No special character in name except dashes or spaces.

**Comment by borisrorsvort** [comment] 2019-05-12 13:58
I have the setting restore folders after open.
I tried to change to restore files and folders after open and it has similar behaviour:
Opens the last edited file, but the next file you click on renders a blank page (with the correct title though). Then click again on another file and that works.

**Comment by mlbrgl** [comment] 2019-05-12 19:54
> So it’s always the first file you click on right after Typora opened that doesn't work.

Indeed, I hadn't noticed but the second file opened through Typora's menu (either "Open Quickly..." or "Open Recent") does open correctly.

So to open fileA.md using Typora's menu exclusively, the following steps are required:
- open fileB.md
- open fileA.md

I might add that double-clicking on md files from the Finder opens files correctly from the first attempt, even if Typora is closed.

Same here regarding the path to the file or the filename: no special characters (tested with a file named "test.md" on the Desktop).

I also tested by switching the OS back to English, same behaviour.

**Comment by abnerlee** [comment] 2019-05-14 01:23
@borisrorsvort Sorry, I still failed to reproduce it following your instructions, possible to send us (<hi@typora.io>) a screencast ?

**Comment by mlbrgl** [comment] 2019-06-03 11:57
@abnerlee did you get a screencast from @borisrorsvort?

**Comment by borisrorsvort** [comment] 2019-06-03 12:00
Here you go @abnerlee 
http://take.ms/LMV1V

**Comment by mlbrgl** [comment] 2019-06-03 12:04
Thanks @borisrorsvort !

**Comment by rolanday** [comment] 2019-06-15 15:17
Same issue here (MacOS, Typora Version 0.9.9.24.6 (2400)). It's a fairly regression.

**Comment by abnerlee** [comment] 2019-06-21 16:03
should be fixed in latest version

**Closed by abnerlee** 2019-06-21 16:03 UTC
Labels: File Management, Need more info

**Comment by mlbrgl** [comment] 2019-06-26 06:02
Confirmed, thanks @abnerlee!
