### ISSUE TITLE
Line-break in tables

### ISSUE THREAD

**Issue by zttt** [typora/typora-issues#33] opened 2016-01-06 23:24 UTC
Currently there is no way to line-break in a table since Typora is ignoring `<br/>`.
Is it possible to support this feature in future release?

**Comment by goto100** [comment] 2016-07-06 09:42
+1

**Comment by harper357** [comment] 2016-07-21 19:46
This would be a great enhancement/feature. Atom seems to do this just fine (for example).

**Comment by vassudanagunta** [comment] 2016-07-22 01:53
Clearly GitHub handles it:

| Fruit  | Vegetable | Grain |
| ------ | --------- | ----- |
| apple  | eggplant  | rice  |
| tomato <br> (not a vegatable!) | spinach   | wheat |
| banana | squash    | oat   |

I confirmed that the above table works in Atom as well.

**Comment by vassudanagunta** [comment] 2016-07-22 01:56
To be consistent with how Typora supports line-breaks in regular paragraphs, `SHIFT` `RETURN` rather than having to manually enter `<br>` should be supported.

**Comment by goto100** [comment] 2016-07-22 02:16
It seems typora ignores **all** html in markdown, not only `<br />` in table.

**Comment by vassudanagunta** [comment] 2016-07-22 02:50
Supporting HTML should be a separate feature request. Typora added line-breaks for regular paragraphs recently (by pressing `SHIFT` `RETURN`, not entering HTML), it simply needs to do the same within tables.

**Comment by leafiy** [comment] 2016-08-18 08:21
+1

**Comment by alphaqiu** [comment] 2016-11-15 04:48
![image](https://cloud.githubusercontent.com/assets/1404566/20293445/8e763bb4-ab31-11e6-80ed-0855aace2195.png)
when i pressing SHIFT RETURN, it generate and go to next row. pressing SHIFT RETURN break line not work for me.

**Comment by Jasonx0716** [comment] 2017-03-10 06:43
+1 better add this feature

**Comment by CarloGiuliano** [comment] 2017-03-26 17:16
+1 It would be of great help to make the table contents more readable

**Comment by bixb0012** [comment] 2017-04-08 14:57
+1 If I could add only a single enhancement request for Typora, this might just be it.  Sure, inserting `<br/>` works when printed or exported, but not having actual line breaks within table cells makes for a mess with larger content.

**Comment by ecamy** [comment] 2017-04-10 07:37
I press shift+return, then add new row, why?

**Comment by abnerlee** [comment] 2017-04-10 14:22
Table in markdown does not support line break. An acceptable solution os to support and render `<br/>` tag.

**Comment by AlexPasternak** [comment] 2017-04-10 17:21
In this case it seems like what folks are asking for is a keyboard combination that would insert the br tag. This is something I do very often in tables, and having to manually type it out, or come up with a custom solution for each user, doesn't seem as nice.

**Comment by ecamy** [comment] 2017-04-11 13:33
I think it's really important for a table. hope add the function in the future. I used typora to write the note from the day before yesterday, it is wonderful for all of us.

**Comment by westfish** [comment] 2017-05-13 03:08
from Jan 2016 to May 2017, the problem still exists,<br>or shift+enter(windows) is  not worked to break lines in a table

**Comment by nickcorona** [comment] 2017-07-25 19:39
Problem is still not fixed on Linux. I still have no idea how to start a new line in a table cell.

**Comment by swen624** [comment] 2017-09-11 07:03
+1

**Comment by Rocking80** [comment] 2017-09-21 05:18
I also need this feature very much! Since so many users needs this support, why no one take this into action in almost 2 years?!

**Comment by jiangfengming850811** [comment] 2017-10-26 00:55
+1

**Comment by abnerlee** [comment] 2017-10-30 07:58
Please use `<br/>` (https://github.com/typora/typora-issues/issues/439)

Or hit shift+return. This is supported now in the last update.

**Closed by abnerlee** 2017-10-30 07:58 UTC
Labels: enhancement

**Comment by cee1** [comment] 2018-01-30 14:56
os x 0.9.9.12

<br /> not renders to a line-break while exporting to PDF or HTML

**Comment by abnerlee** [comment] 2018-01-31 03:25
@cee1 will be fixed in https://github.com/typora/typora-issues/issues/1180 soon

**Comment by fulldecent** [comment] 2018-04-17 03:28
This is in the current released version:

![screen shot 2018-04-17 at 11 27 42 am](https://user-images.githubusercontent.com/382183/38847101-7efcf5da-4232-11e8-9b66-5dc83b6e4cce.png)

![screen shot 2018-04-17 at 11 28 24 am](https://user-images.githubusercontent.com/382183/38847104-81083286-4232-11e8-9821-27e49fd35469.png)

**Comment by mifas** [comment] 2020-11-10 05:46
How to hide the `<br />` tag from Markdown?

**Comment by Kiiiwiii** [comment] 2020-12-09 07:37
> How to hide the `<br />` tag from Markdown?

Typora > Preference > Markdown > Visible \<br /> (uncheck)
