### ISSUE TITLE
Footnote id is removed when editing 

### ISSUE THREAD

**Issue by ixeft** [typora/typora-issues#1339] opened 2018-03-20 11:24 UTC
With this type of footnote : 

```markdown
Lorem ipsum dolor sit amet  [^footnote-id], consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua . Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

[^footnote-id]: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
```
When cliquing on the footnote content, the id `footnote-id` disapear sometime inside `[^footnote-id]:`

System info : Archlinux, typora 0.9.47

**Comment by abnerlee** [comment] 2018-03-20 13:56
Anyways to reproduce?

**Comment by ixeft** [comment] 2018-03-20 17:25
Copy paste  the text in my example inside typora (removing the code tags)
Juste go at the end of the last line and type «Enter»
look again at `[^footnote-id]:`, it is transformed into `[^]:`

**Comment by abnerlee** [comment] 2018-03-21 07:44
After press  «Enter», I got:

```
Lorem ipsum dolor sit amet  [^footnote-id], consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua . Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

[^footnote-id]: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

[^]: 
```

`footnote-id` seems still be there

**Comment by ixeft** [comment] 2018-03-23 13:05
The bug seems to have been introduced between 0.9.41 and 0.9.47
It is even worth when you try to edit the text of 2 footnote one after the other : 

```
Lorem ipsum dolor sit amet  [^footnote-id], consectetur adipiscing elit [^footnote2], sed do eiusmod tempor incididunt ut labore et dolore magna aliqua . Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

[^footnote-id]: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

[^footnote2]: voluptate velit esse cillum
```
after trying to edit both footnote and go from one to a other, you finish with : 
```
Lorem ipsum dolor sit amet  [^footnote-id], consectetur adipiscing elit [^footnote2], sed do eiusmod tempor incididunt ut labore et dolore magna aliqua . Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

[^]: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

[^]: voluptate velit esse cillum
```
And undo does not works to get back those id.

**Comment by abnerlee** [comment] 2018-04-03 03:19
I tested in Ubuntu, but I cannot reproduce this issue.

Do you have any ideas on reproducing this bug?

**Comment by ixeft** [comment] 2018-04-11 15:24
For more information I get the software from this : https://aur.archlinux.org/packages/typora/

I think that the quickest way to reproduce the bug is to clic on one of the footnote content, and switch to code mode, then the id is lost.

**Comment by abnerlee** [comment] 2018-05-02 02:48
should be fixed in new release

**Closed by abnerlee** 2018-05-02 02:48 UTC
Labels: Need more info
