### ISSUE TITLE
File List/"Articles" view does not handle external renames (Windows, 0.9.31)

### ISSUE THREAD

**Issue by pjeby** [typora/typora-issues#814] opened 2017-08-11 07:10 UTC
If you rename a file from outside Typora, the list/"articles" view does not update with the file's new name (though the folder-based view does).  The old name and text still appear, but it is impossible to navigate to the file: clicking on it does nothing.  Deleting the file externally does not remove it from the list, either, and changing the sort order has no effect.

**Comment by AlexPasternak** [comment] 2017-08-11 23:06
And these types of issues is probably exactly why they avoided adding this view in the first place. You wanted to make a Markdown editor, but now you have yourself a file manager instead, or creeping your way towards one. I love files sidebar (use it in VS Code all the time), but it's not necessary in every single text/code editor. Oh well, we're down the slippery slope.

**Comment by pjeby** [comment] 2017-08-12 00:08
Um, @AlexPasternak, I'm not seeing how your comment is in any way helpful to either me or the author.  The file sidebar is actually quite well implemented: it responds instantly to external addition or deletion; the failure to pickup renames is a relatively small glitch within its overall functionality.

**Comment by abnerlee** [comment] 2017-08-12 04:18
In my testing both view will apply the rename, could you provide detailed steps to reproduce this?

**Comment by pjeby** [comment] 2017-08-12 06:28
Well, the steps I am using are:

1. Using the [Notebooks](http://www.notebooksapp.com/) app, open a markdown file in Typora (using Control-O or right-click and "Open")
2. Display the list view in Typora, sorted by modification date
3. Create a new markdown file in Notebooks, typing a title line
4. The new file now appears in Typora's list view
5. In Notebooks, change the text of the title line and wait a moment -- Notebooks automatically renames the file and saves it with the new contents
6. In Typora, the file still shows with the old name and contents, and cannot be opened or edited.

Given that I'm not able to reproduce the problem using only Explorer, I think there is perhaps a moment where Typora tries to read the file while Notebooks is writing it, or perhaps while renaming it, and getting an error that is silenced.  Maybe some additional error handling is needed, to force-refresh the whole view if there's an error while tracking a rename or rewrite of a file?  Or perhaps the issue is that the rename and write events happen too close together?

**Comment by abnerlee** [comment] 2017-08-12 07:37
I see, I will try Notebooks to see what happened.

For force refresh, you could find "Refresh Folder" item on the menu of the footer of the sidebar

**Comment by pjeby** [comment] 2017-08-12 18:47
Ah, I missed the "Refresh Folder" function.  It does in fact work around this problem.  Thanks.

One reason I enjoy the new file panels so much is that they give me more of the functionality of Notebooks directly from Typora.  My typical workflow is creating new documents in Notebooks in an Inbox folder and then doing any more detailed editing in Typora.  But now, it's a lot easier to just work on those new documents in Typora, immediately after typing the title in Notebooks.  I can literally just alt-tab back to Typora, click on the new document, and continue typing.

(Actually, if Typora emulated the title-filename sync feature of Notebooks, and also allowed you to create new documents without specifying a filename first, I could do all my new note creation directly in Typora, using Notebooks only for search and filing.  But that'd be a feature request.  (Specifically, what Notebooks does is look at the first nonblank line of the file, removing markdown header syntax, and converting invalid filename characters.  If the result matches the current filename, then editing the title renames the file.  You can still manually rename the file, but if it doesn't match the title anymore then it's not synced thereafter.))

**Comment by abnerlee** [comment] 2017-08-14 05:53
should be fixed in the newest version

**Comment by pjeby** [comment] 2017-08-14 07:15
It's definitely improved.  Now, when creating a file named, say, "New Note", then renaming to "New Note 2", it will have two files listed in the pane, one for each name.  Any subsequent renames of New Note 2 are detected, but there is still a ghost of "New Note" until the pane is refreshed.  Which is still a lot better than before, because now the file is immediately accessible in Typora even without refreshing.

**Comment by abnerlee** [comment] 2017-08-14 07:32
What's your OS version? In my testing, the ghost one will be removed

**Comment by pjeby** [comment] 2017-08-14 16:08
Windows 7 Professional x64.

I noticed this morning, however, that it's a rather timing-dependent race condition.  That is, I can get it to either work or not work depending on the timing of how I type.  If I perform the following steps in Notebooks, without pausing for more than a fraction of a second between steps:

1. Create a document, or change the title of an existing one, by typing on the first line
2. Enter some new text into the document that didn't exist before
3. Change the title

...then a ghost of either the first or second filename is left behind.  From previous experience, I know it's possible for me to do this accidentally, i.e., without intending to reproduce the bug.  But I also now know how to *prevent* it, i.e., by waiting for Typora to fully refresh the file list between each step.

(My guess would be that perhaps file monitoring is effectively paused while the display is refreshed?  Maybe the refresh is done from a callback, instead of having the callback write to a queue that's periodically flushed?)

Anyway, while playing around with this I noticed another issue: if there is a single-quote character in the filename, Typora treats it as non-existent file.  So typing a title like "Let's Try This" into Notebooks causes the file to not show up in Typora at all.  Should I create a separate issue for that?

**Comment by pjeby** [comment] 2017-09-26 17:22
FYI, As of 0.9.37, the single-quote problem is fixed, but it's still possible to get ghost files in the article view.

In practice, though, I don't much care anymore because it 1) happens infrequently, 2) can be fixed with a refresh, and 3) doesn't actually hurt anything while it's there.  So feel free to close this if you don't think it's worth fixing.

**Comment by abnerlee** [comment] 2017-10-22 07:20
Closing this since it is a minor bug and hard to reproduce

**Closed by abnerlee** 2017-10-22 07:20 UTC
