### ISSUE TITLE
Auto save overwites wrong file when switch files

### ISSUE THREAD

**Issue by twborup** [typora/typora-issues#3894] opened 2020-10-05 08:24 UTC
I'm using Typora 0.9.96 on a Windows and have noticed an issue when Typora is auto-saving. At first, I thought I did something wrong, but after several tries, I found a way to replicate the issue.

1. 1. You need at least 2 articles.
2. Make some changes to article#1 and do not save.
3. Choose article#2 in the list on left.
4. Typora will ask if you want to save the changes.
5. Choose Yes and select article#2 just after selecting Yes. 

This can have several outcomes:

1. Article#1 is saved and all is good.
2. Article#2 is saved with acticle#1's content. There are no way of undoing this, and you have to rewrite the article or recreate it from a backup.
3. The content of article#2 is replaced by the content of article#1. It is not saved yet, so I you notice this, you can undo it. If I select a different article than article#2 and return to article#2 then the content is correctly the content from article#2 (the content from article#1 is no longer shown, even though I didn't do anything).

It is really frustrating when an article is overwritten and you must rewrite it again, so please fix this issue.

**Comment by abnerlee** [comment] 2020-10-12 15:23
I tried with your steps, but still failed to reproduce.

Possible to send us a screencast <hi@typora.io> in case we missed anything?

**Comment by abnerlee** [comment] 2021-04-29 15:52
should be fixed

should be same with #3520

**Closed by abnerlee** 2021-04-29 15:52 UTC
Labels: File Management, Need more info

**Comment by ffaallkk** [comment] 2024-09-30 08:30
Just experienced this for the second time with Typora for Windows 1.9.5 on Windows 11, working with Markdown files on a network drive. "Auto save when switching files" was enabled. At some point I noticed that the contents of file A had been overwritten with the contents of file B. This has happened before, back then I was convinced that I must have made a mistake myself because I could not fathom a text editor to have a bug like this. When it happened now I found this thread. At least I found the option to restore past versions, still not sure if there was a data loss. I switched to regular auto-save for now. 
Frankly this is a ricidulously bad error, since the implications for users can be horrifying. Especially for a paid app!
