### ISSUE TITLE
Smart Quotes option is not saved

### ISSUE THREAD

**Issue by rtrn** [typora/typora-issues#137] opened 2016-04-21 20:26 UTC
If `Edit -> Substitutions -> Smart Quotes` is selected, it is kept only for the current document.
It has to be re-enabled for every new document, which is tedious.

**Comment by spencerclrk** [comment] 2016-11-24 14:18
I've noticed this as well and would appreciate the tweak. It's visually superior to the basic "quotes"

**Comment by davidgolding** [comment] 2017-11-15 17:53
I've had to customize a keyboard shortcut in System Preferences for the Smart Quotes menu item. This has helped me minimize the annoyance, but this menu item should conform to Apple's software design standards. (Any menu item with a check mark should persist across windows/documents.)

**Comment by dajare** [comment] 2018-01-28 14:36
Perhaps there's value in a "me too!", since this Issues "repo" doubles in some sense as a forum. 
I'm using:

- Typora  v. 0.9.9.12 (latest as I type);
- Mac OSX 10.10.5 (MacBook, early 2015) (also "as I type"; I also regularly use Typora on an Ubuntu machine, but haven't checked this behaviour on that machine yet).

Steps to reproduce:

- enable "Smart Quotes" option \[✓\] in the "Edit >  Substitutions" dropdown menu;
- happily use this feature;
- close document, end session;
- re-launch Typora ... and notice that "Smart Quotes" substitutions are no longer enabled (although "Smart Dashes" and "Text Replacement" *are* persistent).

It would be very helpful for this bug to be squashed! 😁  (I also hope that #291 which is sort of related can also be implemented at some point.) Thanks!

**Comment by abnerlee** [comment] 2018-05-28 02:40
Fixed in new release

**Closed by abnerlee** 2018-05-28 02:40 UTC
Labels: bug, enhancement

**Comment by davidgolding** [comment] 2018-05-30 21:11
It appears the substitution does not occur even when the Smart Quotes option is selected and Convert on Input is selected. This may be a break with 0.9.9.16.1, as 0.9.9.16 worked for double quotes (but not single).

**Comment by abnerlee** [comment] 2018-05-31 02:26
In my testing it will be converted after you input chars or whitespaces after the quote.
