### ISSUE TITLE
Open multi files dont refresh the Outline

### ISSUE THREAD

**Issue by josseve** [typora/typora-issues#1716] opened 2018-08-23 11:15 UTC
version 0.9.56
I have a tree of several directory and configuration files big enough.

I open first.md file... I see its contents in the right window…
I select outline… I see the outline of first.md file… No problem.
I open second.md file, when I want to see the outline, I see the outline of first.md file, not the outline of second.md.
I can change many times of files… Nothing change… Always the bad outline appear

This problem does not occur with version 0.9.53

**Comment by abnerlee** [comment] 2018-08-23 13:37
Hi, I'm not able to reproduce this. 

What's your OS version?
If you close & reopen the file, are the outline be correctly rendered?

**Comment by josseve** [comment] 2018-08-23 13:56
Windows 10 pro 17134.228

I use  now the 0.9.53

 

So.. with 0.9.56

 

I select first.md file, i see good outline

I select second.md file, i see good outline

I select first.md, i see outline of second.md

 

I select third.md (without outline)… outline is refreshed

I select second.md, outline is good

I select first.md, i see outline of second.md

 

Joss

 

 

 

De : AbnerLee <notifications@github.com> 
Envoyé : jeudi 23 août 2018 15:37
À : typora/typora-issues <typora-issues@noreply.github.com>
Cc : josseve <joss.eve@free.fr>; Author <author@noreply.github.com>
Objet : Re: [typora/typora-issues] Open multi files dont refresh the Outline (#1716)

 

Hi, I'm not able to reproduce this.

What's your OS version?
If you close & reopen the file, are the outline be correctly rendered?

**Comment by josseve** [comment] 2018-08-23 14:13
I reproduce the bug with this.. test it.. tell me…

 

I have perso css and shortcut, very limited, just one line on each !

 

De : AbnerLee <notifications@github.com> 
Envoyé : jeudi 23 août 2018 15:37
À : typora/typora-issues <typora-issues@noreply.github.com>
Cc : josseve <joss.eve@free.fr>; Author <author@noreply.github.com>
Objet : Re: [typora/typora-issues] Open multi files dont refresh the Outline (#1716)

 

Hi, I'm not able to reproduce this.

What's your OS version?
If you close & reopen the file, are the outline be correctly rendered?

**Comment by abnerlee** [comment] 2018-08-23 15:05
So it seems only switch to first.md, the outline won't refresh ?

**Comment by abnerlee** [comment] 2018-08-23 15:12
> I reproduce the bug with this.. test it.. tell me…
> I have perso css and shortcut, very limited, just one line on each !

Sorry, I'm not so clear about this. Could you give some more explanation?

**Comment by josseve** [comment] 2018-08-23 15:17
:) github doesnt like attachment email...
[_test_temp.zip](https://github.com/typora/typora-issues/files/2315085/_test_temp.zip)

**Comment by josseve** [comment] 2018-08-25 11:56
you tested ?

**Comment by abnerlee** [comment] 2018-08-25 15:02
Does the file content being correctly rendered after you switch?

I tried but unable to reproduce it.  After the outline get "not update", could you open DevTool from menubar (View->Toggle DevTools) and send us the log in the console?

**Comment by josseve** [comment] 2018-08-25 15:29
Yes, the content rendered correctly, just the plan. I reproduce the bug with the exemple files i send you (_test_temp.zip)

frame.js:1 start monitoring folder change.
frame.js:1 start monitoring folder change.
**nodeMap not clean frame.js:1**
		f.reset @ frame.js:1
		onSwitchDocumentTarget @ frame.js:1
		(anonymous) @ frame.js:1
		o @ frame.js:1
		y @ frame.js:1
		openFile @ frame.js:1
		(anonymous) @ frame.js:1
		dispatch @ frame.js:1
		g.handle @ frame.js:1
**nodeMap not clean frame.js:1**
		f.reset @ frame.js:1
		onSwitchDocumentTarget @ frame.js:1
		(anonymous) @ frame.js:1
		o @ frame.js:1
		y @ frame.js:1
		openFile @ frame.js:1
		(anonymous) @ frame.js:1
		dispatch @ frame.js:1
		g.handle @ frame.js:1

**Comment by abnerlee** [comment] 2018-09-01 06:43
Fixed in new release

**Closed by abnerlee** 2018-09-01 06:43 UTC
Labels: bug
