### ISSUE TITLE
"no valid printers available" error when there are printers available

### ISSUE THREAD

**Issue by jdalbey** [typora/typora-issues#3744] opened 2020-07-28 23:44 UTC
I'm using version 0.9.93 beta on Linux.  Choosing the Print function shows an error dialog with the message "no valid printers available".  However, using any similar application (text editor, word processor) and choosing Print shows a standard print dialog with available printers.

**Comment by abnerlee** [comment] 2020-08-04 16:41
relates electron/electron#24664

**Comment by abnerlee** [comment] 2020-10-07 15:25
caused by https://github.com/electron/electron/issues/25498

fixed in https://github.com/electron/electron/pull/25607

**Comment by stevenov** [comment] 2020-11-07 20:54
Should this be fixed now? I'm still seeing it in Ubuntu 16.04.

**Comment by abnerlee** [comment] 2020-12-14 03:45
should be fixed

**Closed by abnerlee** 2020-12-14 03:45 UTC
Labels: 3rd party lib, import/export

**Comment by jdalbey** [comment] 2020-12-14 18:24
Can confirm this now works for me.  Thanks!
