### ISSUE TITLE
Flowchart

### ISSUE THREAD

**Issue by nic-juncheng** [typora/typora-issues#241] opened 2016-07-28 04:49 UTC
have you ever thought about to add FlowChart and SequenceChart in your roadmap?

**Comment by vassudanagunta** [comment] 2016-07-31 07:18
Not only is this a dupe of Issue #12, it has the EXACT same wording. Rather fishy!

Issue #12: "have you ever thought about to add FlowChart and SequenceChart in your roadmap?"

**Closed** 2016-07-31 07:28 UTC
