### ISSUE TITLE
Copy Pasting line with multiple links corrupts second link

### ISSUE THREAD

**Issue by allohakdan** [typora/typora-issues#1889] opened 2018-10-22 15:18 UTC
Copying the following line of code 

```[Google](http://www.google.com) - [Yahoo](http://www.yahoo.com)```

will corrupt the second link such that pasting it results in

```[Google](http://www.google.com) - [Yahoo](```

I'm using 0.0.0.18.1 on OSX 10.12.6.

**Comment by abnerlee** [comment] 2018-10-27 13:19
I cannot reproduce this on 0.9.9.19, please reopen it if it still exists on latest version

**Comment by allohakdan** [comment] 2018-10-27 13:37
It doesn't look like I cannot reopen the ticket.

I just tried this with 0.9.9.19 and I'm still seeing the problem.

This is what the file looks like before I start trying to highlight.

![image](https://user-images.githubusercontent.com/119465/47604693-252b8e00-d9cb-11e8-95eb-9f0379fa9b73.png)

If I drag the cursor from left to right to highlight the line, it looks like this

<img width="254" alt="highlighting from left to right" src="https://user-images.githubusercontent.com/119465/47604704-3b394e80-d9cb-11e8-8384-d84ac4f8c564.png">

Pressing Apple-C (copy) changes the highlighting to look like this (note the non-expanded yahoo link and missing square bracket on google).

<img width="256" alt="screen shot 2018-10-27 at 9 28 17 am" src="https://user-images.githubusercontent.com/119465/47604710-4db38800-d9cb-11e8-9142-248365093e23.png">

Pasting ends up looking like this

<img width="273" alt="screen shot 2018-10-27 at 9 28 36 am" src="https://user-images.githubusercontent.com/119465/47604713-6623a280-d9cb-11e8-99aa-5c315c4ab86b.png">

I think the reason you may have had trouble reproducing this is that there are multiple ways of highlighting. For example, if you drag downwards while going from left to right, and additional amount of space gets highlighted below the line you are on like in the image below

<img width="345" alt="screen shot 2018-10-27 at 9 29 36 am" src="https://user-images.githubusercontent.com/119465/47604734-b864c380-d9cb-11e8-8058-0340b2ebf75a.png">

In the case above, if I were to try copying and pasting it would work as expected (both links would remain intact.

**Comment by th3ragex** [comment] 2019-05-28 07:35
![Typora#1889](https://user-images.githubusercontent.com/15040273/58459373-85cea500-812b-11e9-8ca4-e2dd16bd5f6d.gif)
with v0.9.70 (beta) on Windows 10 1809

**Comment by justnealpatel** [comment] 2019-06-07 03:36
I can replicate this when I have a list of links and I'm trying to copy them to move to another location, the last link gets cut off.

**Comment by abnerlee** [comment] 2019-10-13 17:34
should be fixed

**Closed by abnerlee** 2019-10-13 17:34 UTC
Labels: Need more info
