### ISSUE TITLE
Add option to allow lines separated by a single newline character to be gathered into a single paragraph

### ISSUE THREAD

**Issue by KyrychukD** [typora/typora-issues#364] opened 2016-10-19 14:56 UTC
Typora puts a whole paragraph into a single line in the output file. It is not very good for version control, because when I make a change in a paragraph, the whole paragraph would be highlighted as changed, instead of a small part of it. 

If I want the diffs to be meaningful, I later have to open the file in a plain text editor and put some line breaks across the text, so that it fits into the screen. After this the document is rendered on bitbucket almost exactly as it was shown in Typora's live-preview before adding the line breaks. But after I open the edited document in Typora again (after the line breaks addition), I see actual line breaks across the text in places where I put them.

I would like to suggest an option that enables non-empty lines that follow a paragraph to become a part of the paragraph when rendering a live preview or exporting a document to HTML or PDF.

**Comment by orgkhnargh** [comment] 2016-10-19 15:16
Implementing this would actually make Typora behavior more compatible with CommonMark specification. See the Paragraphs section [here](http://spec.commonmark.org/0.26/#paragraphs).

**Comment by TripleFire** [comment] 2017-03-31 12:51
+1

**Comment by dlepilin** [comment] 2017-04-12 13:57
+1

**Comment by abnerlee** [comment] 2017-07-03 16:45
also relates https://github.com/typora/typora-issues/issues/522

**Comment by abnerlee** [comment] 2017-07-03 16:47
> I would like to suggest an option that enables non-empty lines that follow a paragraph to become a part of the paragraph when rendering a live preview or exporting a document to HTML or PDF.

This seems a bug, the exported HTML or PDF should following Markdown's rule for line break. (relates https://github.com/typora/typora-issues/issues/665)

**Comment by orgkhnargh** [comment] 2017-07-03 17:31
I'll try to clarify this a bit.

Consider the following markwown sample:

```
First
paragraph.

Second
paragraph.
```

When exported to HTML:

```
<title>First.md</title></head>
<body><p>First
paragraph.</p>
<p>Second
paragraph.</p>
``` 

As you can see, the line breaks are preserved. But when rendered by a browser, it appears as follows:

![selection_357](https://user-images.githubusercontent.com/699961/27802291-7a50c4d8-602b-11e7-8842-1d8c9168e21f.png)

When exported to PDF, lines are not squashed the way browsers do that for HTML:

![selection_358](https://user-images.githubusercontent.com/699961/27802318-be85303a-602b-11e7-9024-f2321e124b8d.png)

A GIF on Typora website claims that Typora supports Github Flavored Markdown and more. According to [the spec](https://github.github.com/gfm/#soft-line-breaks), a renderer may provide an **option** to render soft line breaks as hard line breaks. Typora does not currently expose such option to the end user, which might be considered a bug, in my opinion.

I think soft line breaks should not be rendered as hard line breaks by default. I assume that Typora calls pandoc with `--wrap=preserve` argument. If that is the cause of the described behavior, then it will only be necessary to stop passing the `--wrap=preserve` argument to pandoc in order to fix this issue.

**Comment by vassudanagunta** [comment] 2017-07-03 20:15
We keep having debates around how Typora's markdown should work. This is why resolving Issue #369 is really important.

**Comment by abnerlee** [comment] 2017-07-04 10:16
The PDF export result is in your example is a bug. 

And you could use CSS to specify whether to ` render soft line breaks as hard line breaks` or not. 

```css
.typora-export p {
  white-space: nowrap // no line break
  word-break: pre // keep the line break
}
```

I would mention this on some doc

**Comment by Eli4ph** [comment] 2017-08-02 08:46
@abnerlee I would like to make typora's behaviour consistent with plain markdown. And I create a `base.user.css` containing your code, but nothing happens. Single line-break still causes line-breaking. Is there a solution? (v0.9.9.9.4.2 on macOS)

**Comment by abnerlee** [comment] 2017-08-02 17:00
@Eli4ph The css above is to fix export behavior. Avoid line-break by single line-break is still not supported. 

You could use this for **preview** purpose, but it is buggy for editing in my testing, so I won't recommend it.
```css
display: inline-block;
width: auto;
margin-right: 1ch;
```

**Comment by moof2k** [comment] 2017-12-29 00:10
See also:

* https://daringfireball.net/projects/markdown/syntax#p
* http://spec.commonmark.org/0.26/#paragraphs
* https://github.github.com/gfm/#paragraphs

"A paragraph is one or more consecutive lines of text separated by one or more blank lines"

**Comment by vassudanagunta** [comment] 2017-12-29 06:28
Currently Typora renders lines separated by a single newline character as a single paragraph in HTML output. This is correct as it conforms to GFM/CommonMark. But in the editor itself, Typora renders them as hard-wrapped lines, **thus spoiling the reason Typora is so popular**: It is a WYSIWYG editor, avoiding the need for separate edit and preview views that other editors employ. 

@abnerlee please take note! Sometimes Typora acts like a WYSIWYG editor, but sometimes it acts like *source code mode* even when not in source code.

Is there a better way of doing this? Options:

1. Keep it as is, which violates the WYSIWYG expectations of some or most users.
2. Only render the single line-breaks in source code mode
3. Only render the single line-breaks when the paragraph has focus (similar to how you do so for other things like bold/italics and links) and in source code mode.

Maybe this issue should be merged with #1026 as the underlying problem is the same. Option 3 might be the best for both of them.

**Comment by KirkMunro** [comment] 2018-02-01 15:00
@vassudanagunta Thanks for pointing out the duplicate issue. I would vote strongly for #3.

While considering this issue, line break handling/options should be considered.

GFM treats line breaks
as actual hard line breaks
and renders them with
`<br/>` tags at the end.

CommonMark treats regular line breaks as soft line breaks. To get [hard line breaks in CommonMark](http://spec.commonmark.org/0.28/#hard-line-breaks) you either need to leave two or more trailing whitespace at the end (invisible, yuck) of your line or end your line with a backslash (visible, better).

Typora should have options allowing users to choose how soft/hard line breaks work in their document (GFM-style or CommonMark)., and paragraphs should only show the markdown when they have focus or when Typora is in source code mode.

**Comment by vassudanagunta** [comment] 2018-02-01 16:40
@KirkMunro Glad you, me and @abnerlee are on the same page 😄 .

Just so everybody is clear, CommonMark and GFM do not differ in this regard. GitHub states:

> GFM is a strict superset of CommonMark. All the features which are supported in GitHub user content and that are not specified on the original CommonMark Spec are hence known as extensions, and highlighted as such.

I just diffed http://spec.commonmark.org/0.28/#hard-line-breaks and https://github.github.com/gfm/#hard-line-breaks). They are identical.

I confirmed that GitHub's rendering of Markdown in their repo web interface is identical to CommonMark's. Where they differ is right here, in GitHub Issues. [This is known and apparently intended behavior](https://github.com/isaacs/github/issues/1013#issuecomment-329000809). But *both* the CommonMark and GFM specs say:

> A conforming parser may render a soft line break in HTML either as a line break or as a space.
>
> A renderer may also provide an option to render soft line breaks as hard line breaks.

So your idea is consistent with that!

**Comment by KirkMunro** [comment] 2018-02-01 21:09
@vassudanagunta Thank you for pointing that out, that is so helpful. I write Markdown in so many places, it's hard to keep track, and I hadn't thought to check for a difference between the experience when creating content for issue discussion vs the experience when editing markdown files in GitHub. It was driving me crazy, because I was sure I saw different behavior but couldn't find it, and you solved that puzzle for me, so thanks!

**Comment by abnerlee** [comment] 2018-02-20 12:22
duplicate with https://github.com/typora/typora-issues/issues/233

**Closed by abnerlee** 2018-02-20 12:22 UTC

**Comment by raacampbell** [comment] 2023-04-25 11:55
What is the current status on this? I know the issue is closed but it's an import point and it seems not resolved (unless I'm missing something).
