### ISSUE TITLE
Error updating Typora on Windows

### ISSUE THREAD

**Issue by fluxvx** [typora/typora-issues#5739] opened 2023-05-27 05:42 UTC
"An error occurred while trying to replace the existing file: DeleteFile failed; code 5. Access is denied."

![image](https://github.com/typora/typora-issues/assets/22137020/8eee41e2-58d6-492f-8172-850db6316122)

Restarting after cancelling installation results in an error.

![image](https://github.com/typora/typora-issues/assets/22137020/1139967f-1a05-4ad8-ae12-a50a2449bbd7)

**Comment by Starmania** [comment] 2023-05-28 11:08
Are you sure the installer was run as admin ?

**Comment by fluxvx** [comment] 2023-05-29 01:28
This happens when updating Typora, not the installer directly, so I don't think it was run as admin when I initially tried to update. When I re-ran Typora as administrator after the update failed I got the same error. The way I fixed it was with a fresh installation.

**Comment by abnerlee** [comment] 2023-05-30 04:51
Please try a clean uninstall and reinstall. It may caused by Typora not successfully exited when updater.exe is running, or updater requires an admin privilege but denied. We will close this for now since we did not receive other similar reports and also not able to reproduce this.

**Closed by abnerlee** 2023-05-30 04:51 UTC
Labels: windows
