### ISSUE TITLE
internal link is broken on PDF export in version 0.9.78

### ISSUE THREAD

**Issue by changhenry2** [typora/typora-issues#2941] opened 2019-10-22 10:35 UTC
As title,  internal link is broken after update.
I tested the function in version 0.9.77 is fine.

**Comment by abnerlee** [comment] 2019-10-27 08:44
Could you provide a sample file?

**Comment by changhenry2** [comment] 2019-10-30 13:13
Sure, link is [here](https://send.firefox.com/download/74d46f7bb73227eb/#wVHnmm5T3VPpZO-9VWX-VQ)
In [exported PDF file](https://send.firefox.com/download/de1328becd43f414/#NtBaeQk5hW7NceyYHmLOkQ), there is no hyperlink at all.

**Comment by BrandoZhang** [comment] 2019-11-11 13:04
Version 0.9.9.29.2 (3650)

**Comment by changhenry2** [comment] 2019-11-30 12:13
Seems be fixed in 0.9.80 (Windows version)

**Comment by mdlockyer** [comment] 2019-12-14 20:49
I have the same issue on 0.9.81-1 on Linux. 

The following link will not persist when exported to PDF:

```
[some-header](#some-header)
## Some Header <a name="some-header"></a>
```

**Comment by abnerlee** [comment] 2019-12-26 16:12
should be fixed

**Closed by abnerlee** 2019-12-26 16:12 UTC
Labels: bug, import/export

**Comment by rishoocplace** [comment] 2020-04-15 07:02
They are still broken in version 0.9.86 - windows version. Will appreciate if someone can help provide a fix?

**Comment by regomne** [comment] 2021-02-03 08:00
It is still broken in version 0.9.98 - windows version.

**Comment by uo269450** [comment] 2021-05-10 11:41
Still broken in version 0.10.9(beta) -  windows version

**Comment by abnerlee** [comment] 2021-05-12 15:47
Provide a sample file, please

**Comment by MikeLin2018** [comment] 2021-05-14 00:15
[example.md](https://github.com/typora/typora-issues/files/6475684/example.md)
[example.pdf](https://github.com/typora/typora-issues/files/6475686/example.pdf)

Typora: Version 0.10.9 (5330)
MacOS: Catalina Version 10.15.7

**Comment by MikeLin2018** [comment] 2021-06-27 05:55
Do we have any update on this issue?

**Comment by abnerlee** [comment] 2021-07-04 07:30
try 0.10.11 ?

**Comment by MikeLin2018** [comment] 2021-07-04 09:14
Still observe this issue in version 0.10.11 with the same example. https://github.com/typora/typora-issues/issues/2941#issuecomment-840910125

**Comment by hollowshiroyuki** [comment] 2021-12-10 10:06
Good evening, the issue is still here in 1.0.3 👋
