### ISSUE TITLE
After installing beta 0.9.6, Windows reports malware

### ISSUE THREAD

**Issue by somelinguist** [typora/typora-issues#171] opened 2016-05-27 17:24 UTC
I just installed version 0.9.6, and Windows started reporting it had found malware during the install as well as after. I hadn't seen this using version 0.9.5 or before. All downloaded from the link at http://www.typora.io/#windows

Here is the it reported:

Detected item: Trojan:Win32/Gatrid.E!cl
Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
file:E:\Downloads\typora-setup.exe
file:C:\Program Files (x86)\Typora\bin\typora.exe
file:C:\Program Files (x86)\Typora\bin\is-2B8V7.tmp

**Comment by smallx** [comment] 2016-05-28 00:24
It's no problem in my favourite Windows 8 64bit(Chinese version). 😃

**Comment by abnerlee** [comment] 2016-05-28 02:16
@somelinguist which windows version could report this ?

**Comment by abnerlee** [comment] 2016-05-28 02:17
@somelinguist btw, could you try download from the `https` link? 
<https://www.typora.io/#windows>

**Comment by smallx** [comment] 2016-05-28 04:27
@abnerlee Why I can't download the **latest** version in https://www.typora.io/#windows or http://www.typora.io/#windows ?

**Comment by abnerlee** [comment] 2016-05-28 07:13
@smallx so you mean you install Typora 0.9.6 from auto update (<https://www.typora.io/windows/typora-update0527.exe>), but windows reports some file from typora are malware?

And which windows version/anti-virus software did you use ?

**Comment by smallx** [comment] 2016-05-28 07:17
@abnerlee I do not have this problem. Just is @somelinguist , not me. :smiley:

**Comment by abnerlee** [comment] 2016-05-30 15:14
The misreport may be caused by runtime unpack. This is fixed in v0.9.7

**Closed by abnerlee** 2016-05-30 15:14 UTC
Labels: bug

**Comment by somelinguist** [comment] 2016-05-30 16:01
Sorry, didn't see the request for more info until this morning. Thanks for the fix!

**Comment by smallx** [comment] 2016-05-30 16:04
Haha, I will go to bed. Good morning to you, good night to me.

**Comment by abnerlee** [comment] 2016-05-31 09:50
For solid reference: https://analysis.avira.com/en/status?uniqueid=NTVxcJfDFXNGOMI4r4y9QQfZ5PkQ67LN&incidentid=2044019
