### ISSUE TITLE
Sidebar doesn't stay closed on 0.9.87

### ISSUE THREAD

**Issue by mmelvin0** [typora/typora-issues#3531] opened 2020-05-22 23:31 UTC
In 0.9.86 the sidebar would stay in the exact state I left it (e.g. usually closed) if I closed and re-opened Typora.

After updating to 0.9.87 the sidebar always opens every time I open a document. If it was previously closed it shows outline view.

Minor issue, but I the previous behavior was perfect and minimal thus I think this new behavior might be an unintended regression.

This is on Windows 10 x64 installed via Scoop.

**Comment by afkbrb** [comment] 2020-05-23 01:04
I can confirm, it seems there is no preference setting to close the sidebar by default.

**Comment by theproductiveprogrammer** [comment] 2020-05-24 02:10
I hope this is a bug and not a feature. The reason I like Typora is because it is minimal and 'clean'. The outline is nicely designed but I don't want it to keep opening because I'd like to quickly open my editor and begin typing. I don't want to have to keep closing the outline as it is distracting.

**Comment by abnerlee** [comment] 2020-05-24 08:20
released a fix

**Closed by abnerlee** 2020-05-24 08:20 UTC
Labels: bug

**Comment by theproductiveprogrammer** [comment] 2020-05-24 13:45
Wonderful! Thanks 👍
