### ISSUE TITLE
Scrollbar styling looks out of place when in Seamless mode (OSX)

### ISSUE THREAD

**Issue by jackwlee01** [typora/typora-issues#336] opened 2016-10-06 11:08 UTC
The scrollbar styling looks out of place in Seamless mode, especially when the Night theme is chosen.

![screen shot 2016-10-06 at 9 10 05 pm](https://cloud.githubusercontent.com/assets/1698407/19150291/555d764a-8c09-11e6-8b15-1097f55e4314.png)

**Comment by abnerlee** [comment] 2016-10-06 12:47
Seamless view for dark theme is not supported yet. 

But I haven't met this, so what is your OS version ?

**Comment by jackwlee01** [comment] 2016-10-07 00:54
I have 10.11.3.

Also, for some reason the scrollbar changed. It now looks like this.

![screen shot 2016-10-07 at 10 52 04 am](https://cloud.githubusercontent.com/assets/1698407/19175683/3fbc1508-8c7c-11e6-9d11-f81f4a648d28.png)

**Comment by abnerlee** [comment] 2016-10-10 14:08
@jackwlee01 I tested under 10.11 and Typora 0.9.9.8, and scrollbar is at its correct position. 

So could you share with me the steps to reproduce this bug ?

**Comment by abnerlee** [comment] 2017-02-25 17:12
Closing it since I cannot reproduce this problem

**Comment by mgeorgetw** [comment] 2017-10-31 05:52
I'm on macOS High Sierra(10.13) with Typora 0.9.9.10.9, and the scrollbar looks like what @jackwlee01 had shown in the first place. I went on to select "Show scroll bars: While scrolling" in System Preference, and now it looks right.

**Comment by abnerlee** [comment] 2017-10-31 07:00
>  I went on to select "Show scroll bars: While scrolling" in System Preference, and now it looks right.

Thi sis helpful information, we will check again

**Comment by abnerlee** [comment] 2018-04-03 04:12
Please reopen this if this still exists in newest version of Typora

**Closed by abnerlee** 2018-04-03 04:12 UTC
