### ISSUE TITLE
Can not open Preferences

### ISSUE THREAD

**Issue by athenashavoc** [typora/typora-issues#682] opened 2017-05-05 21:18 UTC
Win 10, ver 0.9.29 beta

Can't open using either menu or keyboard shortcut. Doing so causes the file to lock and a slight memory leak to occur. Closing by clicking 'X' works but take a minute.

While one file is locked, I can still open and use other files in Typora.

I can access everything in the menu except Preferences.

**Comment by abnerlee** [comment] 2017-05-07 13:40
Could you send `typora.log` and `Preferences` under `C:\Users\{your user}\AppData\Roaming\Typora\` to <hi@typora.io> after you click Menu->Preference?

And if you "New" a file, is Preferences also not accessible?

For hot fix, you could try backup your custom theme/css (if you have), and then remove the folder `C:\Users\{your user}\AppData\Roaming\Typora\`

**Comment by athenashavoc** [comment] 2017-05-07 16:18
Files have been sent.

If you are asking if clicking Menu->Preference in a new file causes it to lock, the answer is yes. I also get the same response if I try Menu->Import

I tried removing the folder form AppData but still had the same problem.

**Comment by abnerlee** [comment] 2017-08-11 08:28
I cannot reproduce this bug, would you try update Typora and check if the bug still exists?

**Comment by abnerlee** [comment] 2017-08-14 06:03
should be fixed in the newest version

**Closed by abnerlee** 2017-08-14 06:03 UTC
Labels: bug

**Comment by CbcWestwolf** [comment] 2017-12-22 03:03
I have a same problem ,  and my version is 0.9.41.
